# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AbortImageMultipartUploadRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    ImageID: str  # 镜像ID，上传镜像后返回目标镜像ID

    Region: str  # 地域ID，用于标识资源所属的地理区域

    UploadID: Optional[str] = None  # 上传ID，本地上传时返回的上传任务编号，若为空则使用系统记录的UploadID

