# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AliasSetRequest:
    """"""

    Alias: str  # 集群类型别名，为计算集群类型设置的自定义名称，用于更易读的展示，通过调用RenameResource接口修改资源名称实现，别名长度限制为1-128个字符

    Region: str  # 地域ID，指定计算集群所属的物理区域

    SetType: str  # 计算集群类型，用于唯一标识计算集群的类型

