# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AliasStorageSetRequest:
    """"""

    Alias: str  # 存储集群类型别名，为存储集群类型设置的自定义名称，用于更易读的展示，通过调用RenameResource接口修改资源名称实现，别名长度限制为1-128个字符

    Region: str  # 地域ID，指定存储集群所属的物理区域

    StorageSetType: str  # 存储集群类型，用于唯一标识存储集群的类型

