# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateK8SSessionRequest:
    """"""

    ClusterID: str  # 集群Id

    PodName: str  # Pod名称

    Region: str  # 地域

    CmdName: Optional[str] = None  # 执行命令

    CompanyID: Optional[int] = None  # 租户ID

    ContainerName: Optional[str] = None  # 容器名称

    NameSpace: Optional[str] = None  # 名字空间

