# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateRedisConsoleSessionResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SessionID: Optional[str] = None  # 控制台会话ID，用于建立Redis控制台连接的会话标识
