# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateVIPResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    VIPID: Optional[str] = None  # VIPID，VIP的唯一标识符，用于后续管理操作
