# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateVMVNCSessionRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待获取VNC会话的虚拟机标识

