# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AttachPlatformStorageDiskRequest:
    """"""

    DiskID: str  # 磁盘ID，待绑定的平台通用存储云盘ID

    Region: str  # 地域ID，指定资源所属的物理区域

