# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class BindStorageToDBSResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    StorageID: Optional[str] = None  # 备份存储池ID，创建成功后返回的存储池ID
