# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CancelInstallTaskV2Request:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    SN: str  # 序列号，裸金属的硬件序列号

    TaskID: str  # 任务ID，指定要取消的装机任务

    CleanOnCancel: Optional[str] = None  # 取消后是否清理已安装的系统，true 或 false，默认值为 false

