# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CloneCustomImageToBaseImageRequest:
    """"""

    DestImageName: str  # 目标镜像名称，用于创建基础镜像资源，长度1-128个字符，仅支持中英文、数字、点、下划线和中划线

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SourceImageID: str  # 源镜像ID，作为复制来源的自制镜像标识，用于生成基础镜像

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

