# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateASGroupResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    GroupID: Optional[str] = None  # 伸缩组ID，新创建的伸缩组的唯一标识符
