# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOPLogNotifyRuleRequest:
    """"""

    CompanyID: int  # 租户ID，操作日志通知规则所属租户

    MonitorLevel: List[str]  # 监控级别列表，取值：success/failure

    MonitorModule: List[str]  # 监控模块列表，指定监控哪些资源模块的操作日志

    MonitorRegion: str  # 监控地域，指定监控地域的操作日志

    NotifyGroupID: str  # 通知组ID，操作日志触发通知目标组ID

