# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateUserRequest:
    """"""

    Audit: str  # 审批开关，请求传入并设置租户资源变动是否进入人工审批流程；开通租户策略配置场景使用；取值'1','Y','Yes','YES','True','true'为开启，其它为关闭

    AutoAudit: str  # 自动审批开关，请求传入并设置满足条件的资源申请是否自动通过；开通租户策略配置场景使用；取值'1','Y','Yes','YES','True','true'为开启，其它为关闭

    Email: str  # 租户邮箱，请求传入并写入租户与主账号邮箱字段，作为租户身份全局唯一标识，用于登录、找回密码和接收系统通知；创建租户场景使用；邮箱重复会导致创建失败

    Name: str  # 租户名称，请求传入并写入租户及主账号显示名称，用于组织识别与展示；创建租户场景使用，长度为1-30个字符，只能包含中英文、数字、点、下划线和中划线

    PassWord: str  # 登录密码，请求传入并设置为主账号初始登录密码，作为后续登录凭据；创建租户场景使用；采用Base64(AES-CBC加密)编码传入；密码长度和复杂度由系统配置决定（PASSWORD_LENGTH、PASSWORD_COMPLEXITY），支持字符包括：大小写字母、数字、特殊符号()、反引号、~!@#$%^&*-+=_|{}[]:;'<>,.?/

    UserName: str  # 管理员姓名，历史兼容字段，请求传入但当前创建逻辑忽略该值并以Name为准；旧客户端兼容场景使用，长度为1-30个字符，只能包含中英文、数字、点、下划线和中划线

    Phone: Optional[str] = None  # 手机号，请求传入并写入租户与主账号联系方式，用于短信验证码及敏感操作二次验证；创建或安全校验场景使用；需符合手机号校验规则

    Remark: Optional[str] = None  # 备注，说明或备注信息

    ResetPassword: Optional[str] = None  # 重置密码开关，请求传入并控制租户首次登录是否必须修改初始密码；初始化安全策略场景使用；取值'1','Y','Yes','YES','True','true'为开启，其它为关闭；默认No

    UserEmail: Optional[str] = None  # 管理员邮箱，历史兼容字段，请求传入但当前创建逻辑忽略该值并以Email为准；旧客户端兼容场景使用

