# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVPNTunnelRequest:
    """"""

    IKEAuthenticationAlgorithm: str  # IKE认证算法，IKE阶段使用的认证算法，取值：md5、sha1、sha256

    IKEEncryptionAlgorithm: str  # IKE加密算法，IKE阶段使用的加密算法，取值：3des、aes128、aes192、aes256

    IKESALifetime: int  # IKE SA生存时间，IKE安全关联的生存时间（秒），超时后将重新协商，取值范围：3600-86400

    IKEVersion: str  # IKE协议版本，Internet Key Exchange协议版本，取值：v1（IKEv1）、v2（IKEv2）

    IPSecAuthenticationAlgorithm: str  # IPSec认证算法，IPSec阶段使用的认证算法，取值：md5、sha1、sha256

    IPSecProtocol: str  # IPSec安全协议，IPSec使用的安全传输协议，取值：AH（仅认证）、ESP（认证加密）

    LocalSubnetIDs: List[str]  # 本端子网ID列表，指定通过隧道互通的本端子网，子网需存在且归属当前租户与地域，且需有可用IP；本端子网与对端网段、VPN网关外网网段不可重叠，且与已有隧道组合不可重复

    Name: str  # VPN隧道名称，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符

    PreSharedKey: str  # 预共享密钥，用于IPSec隧道协商，长度1-128字符，不能包含空格或?

    Region: str  # 地域ID，用于标识资源所属的地理区域

    RemoteSubnets: List[str]  # 对端子网CIDR列表，指定通过隧道互通的对端网段，每个网段需为合法CIDR且为网络地址，列表内网段不可重叠；不得与本端子网网段或VPN网关外网网段重叠，同一VPC内不得与已有隧道对端网段重叠

    RemoteVPNGWID: str  # 对端网关ID，对端VPN网关唯一标识

    VPNGWID: str  # VPN网关ID，本地VPN网关唯一标识，需处于Running状态且资源可用，单个VPN网关隧道数量受系统上限限制

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    IKEDhGroup: Optional[int] = None  # IKE DH组，IKE阶段使用的Diffie-Hellman密钥交换组，取值范围：0、1、2、5、14、24（0为历史兼容值）

    IKEExchangeMode: Optional[str] = None  # IKE交换模式，仅当IKEVersion为v1时生效，取值：main（主模式）、aggressive（野蛮模式），为空时默认main

    IKELocalLabel: Optional[str] = None  # IKE本端标识，IKE协商时本端身份标识，为空时使用本端IP地址作为标识

    IKERemoteLabel: Optional[str] = None  # IKE对端标识，IKE协商时对端身份标识，为空时使用对端IP地址作为标识

    IPSecEncryptionAlgorithm: Optional[str] = None  # IPSec加密算法，IPSec阶段使用的加密算法，仅当IPSecProtocol为ESP时生效，若不指定则默认为aes128，取值：3des、aes128、aes192、aes256

    IPSecPFSDhGroup: Optional[int] = None  # IPSec PFS DH组，Perfect Forward Secrecy使用的Diffie-Hellman组，0表示不启用PFS，取值范围：0、1、2、5、14、24

    IPSecSALifetime: Optional[int] = None  # IPSec SA生存时间，IPSec安全关联生存时间（秒），超时后重新协商，取值范围：3600-86400，若不指定则默认为86400

    ProjectID: Optional[str] = None  # 项目ID，用于标识资源所属项目分组，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注，长度0-100字符，禁止http://或https://等非法字符

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

