# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDBSGatewayResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DBSGatewayID: Optional[str] = None  # DBS网关ID，DBS网关的ID
