# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateMemberTagRequest:
    """"""

    MemberID: int  # 成员ID，用于指定被授权的账号

    RoleIDs: List[str]  # 角色ID列表，用于指定要授予的角色集合

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，租户级别用户必填且至少一个项目组ID；系统级/区域级授权可为空

