# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateResourceFromTemplateRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    TemplateID: str  # 模板ID，指定基于哪个模板创建资源，当前仅支持VM类型的模板

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Name: Optional[str] = None  # 资源名称，若指定则覆盖模板中的Name字段

    Password: Optional[str] = None  # 资源密码，若指定则覆盖模板中的Password字段，用于虚拟机登录，采用Base64编码

