# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDBSBackupPlanRequest:
    """"""

    BackupType: str  # 备份类型，取值Logical/Physical/Snapshot/Incremental；Incremental仅支持MySQL且ScheduleType必须为Timer，并需提供IncrementalSrcResourceID与RelatedPlanID

    CompanyID: int  # 租户ID，备份计划所属租户

    Name: str  # 名称，备份计划名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    RetentionTime: int  # 保留时间，备份保留时长

    ScheduleType: str  # 调度类型，取值Manual或Timer

    SrcResourceID: str  # 备份源ID，备份源资源ID

    SrcResourceRegion: str  # 备份源地域，备份源资源所属地域

    SrcResourceType: str  # 备份源类型，备份源的资源类型

    BackupTables: Optional[str] = None  # 备份库表，指定备份库表范围，格式为db.table用逗号分隔，仅Logical且MySQL时生效，*.*表示全库

    IncrementalInterval: Optional[int] = None  # 增量备份间隔，单位分钟，增量备份时必填，且必须≥5分钟，

    IncrementalSrcResourceID: Optional[str] = None  # 增量备份源ID，增量备份源资源ID，BackupType为Incremental时必填

    RelatedPlanID: Optional[str] = None  # 关联的全量备份计划ID，增量备份关联的全量备份计划ID，BackupType为Incremental时必填

    Remark: Optional[str] = None  # 备注，备份计划描述信息，长度0-100字符，禁止http://或https://等非法字符

    StorageID: Optional[str] = None  # 存储池ID，非快照备份时必填

    TimerDays: Optional[List[int]] = None  # 执行日期，TimerType为TIMER_TYPE_MONTHLY时必填

    TimerHours: Optional[List[int]] = None  # 执行小时，TimerType为TIMER_TYPE_DAILY/TIMER_TYPE_WEEKLY/TIMER_TYPE_MONTHLY时必填

    TimerType: Optional[str] = None  # 定时器类型，ScheduleType为Timer时必填

    TimerWeeks: Optional[List[int]] = None  # 执行星期，TimerType为TIMER_TYPE_WEEKLY时必填

