# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateLBRequest:
    """"""

    ChargeType: str  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR

    LBType: str  # 负载均衡类型，决定负载均衡的网络访问范围；取值LAN（内网，仅VPC内部访问）、WAN（外网，可从公网访问）

    Name: str  # 负载均衡名称，用于标识负载均衡，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符

    Quantity: int  # 计费数量，用于指定购买时长的数量；按月/年计费时表示购买的月/年数

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SubnetID: str  # 子网ID，指定负载均衡所属的子网，决定负载均衡的内网IP地址段

    VMType: str  # 计算集群类型，指定负载均衡实例运行的计算集群

    VPCID: str  # VPCID，指定负载均衡所属的私有网络

    ApplicationName: Optional[str] = None  # 审批名称，用于标识此次资源申请的审批流程

    ApplicationReason: Optional[str] = None  # 审批理由，说明申请此负载均衡资源的业务原因

    CPU: Optional[int] = None  # CPU核数，指定负载均衡实例的CPU规格，取值范围：1、2、4、8，若不指定则默认为2核

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    DiskSetType: Optional[str] = None  # 存储集群类型，指定负载均衡实例使用的存储集群，若不指定则系统自动选择最空闲的存储集群

    EIPID: Optional[str] = None  # 弹性公网IP的ID，为WAN类型负载均衡提供公网访问能力；LBType为WAN时必填且EIP必须未绑定

    HighAvailability: Optional[str] = None  # 高可用模式，指定负载均衡部署架构；取值ActiveStandy（双活高可用）、Standalone（单机模式）

    ProjectID: Optional[str] = None  # 项目ID，负载均衡所属项目分组标识，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注信息，长度0-100字符，禁止http://或https://等非法字符

    SGID: Optional[str] = None  # 安全组ID，用于控制负载均衡的网络访问规则，当LBType为WAN时必填，LBType为LAN时必须为空

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

    TerminationPolicy: Optional[int] = None  # 删除保护开关，用于防止误删除；0表示开启删除保护，1表示关闭删除保护

