# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSnapshotRequest:
    """"""

    DiskID: str  # 磁盘ID，要创建快照的源磁盘标识，系统会检查单盘手动快照数量上限

    Name: str  # 快照名称，支持中英文、数字、点、下划线和中划线，长度1-128个字符

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    ProjectID: Optional[str] = None  # 项目组ID，资源所属项目组，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注，用于说明，长度0-100个中英文字符，禁止包含http://或https://等非法字符

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码

    Type: Optional[str] = None  # 快照类型，系统内部使用，创建接口固定为Manual（手动快照），传入无效

