# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNativeNodeRequest:
    """"""

    BootDiskSetType: str  # 系统盘集群ID

    BootDiskSpace: int  # 系统盘大小

    ClusterID: str  # 集群Id

    ComputeclassType: str  # 计算集群类型

    ImageID: str  # 镜像ID

    NodeName: str  # 节点名称

    Region: str  # 地域

    CPU: Optional[int] = None  # 原生节点CPU数量

    CompanyID: Optional[int] = None  # 租户ID

    DataDiskSetType: Optional[str] = None  # 数据盘集群ID

    DataDiskSpace: Optional[int] = None  # 数据盘大小

    EIPID: Optional[str] = None  # 原生节点外网IP

    GPU: Optional[int] = None  # GPU数量

    GPUMdevName: Optional[str] = None  # GPU型号

    MaxPods: Optional[int] = None  # 原生节点pod数量

    Memory: Optional[int] = None  # 原生节点内存容量

    Password: Optional[str] = None  # 密码

    SGID: Optional[str] = None  # 

    SubnetIDs: Optional[List[str]] = None  # 容器子网Id 列表

