# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVSRequest:
    """"""

    HealthcheckType: str  # 健康检查类型，健康检查的类型，取值范围：Port（端口检查）、Path（HTTP检查），TCP和UDP协议只支持Port类型

    LBID: str  # 负载均衡ID，用于定位需要创建监听器的负载均衡实例

    Port: int  # 虚拟服务器端口，VServer的监听端口，端口范围为1~65535，其中323、9102~9105、60909~60910被系统占用

    Protocol: str  # 虚拟服务器协议，VServer的监听协议，取值范围：TCP、UDP、HTTP、HTTPS

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SSLMode: str  # SSL认证模式，SSL的认证模式，取值范围：simplex（单向认证）、duplex（双向认证），必填字段，仅HTTPS协议时生效

    Scheduler: str  # 调度算法，负载均衡的调度算法，取值范围：wrr（加权轮训）、least_conn（最小连接数）、hash（原地址,四层lb使用）、ip_hash（七层lb使用）

    BackendProtocol: Optional[str] = None  # 后端协议，后端使用的协议，取值范围：空（默认HTTP）、HTTP、HTTPS，仅在协议为HTTPS时有效

    CACertificateID: Optional[str] = None  # CA证书ID，用于验证客户端证书的签名，仅当协议为HTTPS且SSLMode为双向认证时有效

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Domain: Optional[str] = None  # HTTP健康检查域名，HTTP检查时校验的HOST字段域名，当健康检查类型为Path时可配置，且需满足validate.IsValidDomain规则（与Nginx server_name一致，支持*.example.com/mail.*等通配）

    HttpClientMaxBodySizeMB: Optional[int] = None  # 请求体大小限制，单位MB，最大512；仅HTTP/HTTPS协议有效，0表示不配置，继承负载均衡全局默认值

    HttpClientMaxHeaderSizeKB: Optional[int] = None  # 请求头大小限制，单位KB，最大512；仅HTTP/HTTPS协议有效，0表示不配置，继承负载均衡全局默认值

    KeepaliveTimeout: Optional[int] = None  # 连接空闲超时时间，负载均衡的连接空闲超时时间，单位为秒，默认值为60s

    Path: Optional[str] = None  # HTTP健康检查路径，HTTP检查时的请求路径，当健康检查类型为Path时可配置，且必须指定以/开头的合法URL路径

    PersistenceKey: Optional[str] = None  # 会话保持KEY，会话保持的键，当类型为Manual时为必填，仅当协议为HTTP时有效

    PersistenceType: Optional[str] = None  # 会话保持类型，会话保持的类型，取值范围：None（关闭）、Auto（自动生成）、Manual（手动生成），TCP协议不生效，UDP协议Auto表示开启会话保持，若不指定则使用系统默认值None

    ProxyProtocolEnable: Optional[str] = None  # TCP Proxy Protocol开关，是否开启TCP Proxy Protocol，取值范围：On、Off，协议为TCP时推荐配置

    RedirectEnable: Optional[str] = None  # HTTP重定向开关，是否开启HTTP重定向，仅HTTP协议有效；取值范围：On、Off

    RedirectVsID: Optional[str] = None  # HTTP重定向目标VSID，重定向到的虚拟服务器ID，仅当RedirectEnable=On时必填，其余情况下必须为空

    ServerCertificateID: Optional[str] = None  # 服务器证书ID，用于证明服务器的身份，仅当协议为HTTPS时有效

