# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOPLogNotifyRuleResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    RuleID: Optional[str] = None  # 操作日志通知规则ID，规则唯一标识
