# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateExternalStorageSetResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SetID: Optional[str] = None  # 存储集群ID，创建成功后返回的外置存储集群ID
