# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNATGWRuleResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    RuleID: Optional[str] = None  # SNAT规则ID，创建成功的SNAT规则唯一标识
