# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOSMediaV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    ImageID: Optional[str] = None  # 镜像ID
    MediaID: Optional[str] = None  # 系统镜像ID
