# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateAlertNotifyWebhookRequest:
    """"""

    Method: str  # HTTP请求方法，取值：GET/POST

    Name: str  # Webhook名称，Webhook名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    NotifyGroupID: str  # 通知组ID，Webhook所属通知组ID

    Url: str  # Webhook URL，告警触发时系统将向该地址发送HTTP请求

