# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDirectConnectRequest:
    """"""

    Device: str  # 网卡名称，指定专线接入绑定的物理网卡，格式为bond0、bond1等，若不确定请联系部署人员或网络管理员

    LocalGatewayIP: str  # 本端网关IP，UCloudStack侧网络接口互联的带掩码IP地址，必须为CIDR格式

    Name: str  # 专线接入名称，长度为1-50个字符，名称只能包含中英文、数字、点（.）、下划线（_）和中划线（-）

    Region: str  # 地域ID，指定专线接入所属的物理区域

    RemoteGatewayIP: str  # 远端网关IP，用户本地数据中心侧网络的互联的带掩码IP地址，必须为CIDR格式，且必须与本端网关在同一网段

    RemoteSubnetCIDRs: List[str]  # 远端子网网段列表，用户数据中心需要通过专线互连的网段，必须为CIDR格式

    TagKeyValuePairs: List[str]  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串

    Bandwidth: Optional[int] = None  # 带宽限制，单位为Mbps，取值范围：1-20000，实际不超过物理带宽上限

    Permission: Optional[str] = None  # 权限范围，指定该专线接入的租户访问权限，当PermissionMode为whitelist或blacklist时，传入租户ID列表（逗号分隔，如200000230,200000232）

    PermissionMode: Optional[str] = None  # 权限模式，控制租户访问权限的模式，可选值：all（所有租户可用，默认值）、whitelist（白名单，仅指定租户可用）、blacklist（黑名单，仅指定租户不可用）

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符

    VLAN: Optional[str] = None  # VLAN ID，虚拟局域网标识，可选，取值范围1-4094，不传或传0表示不设置VLAN

