# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateRedisConfigFileRequest:
    """"""

    Name: str  # 名称，模板名称，长度为1-128个字符，名称只能包含中英文、数字、点、下划线和中划线

    Region: str  # 地域ID，模板所属地域

    Version: str  # 版本，Redis版本

    CompanyID: Optional[int] = None  # 租户ID，模板所属租户

    ConfigID: Optional[str] = None  # 原配置ID，从已有模板复制

    Description: Optional[str] = None  # 描述，模板描述信息

    Params: Optional[str] = None  # 配置项，自定义配置项；当ConfigID为空时必填

