# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreatePMV2Request:
    """"""

    Name: str  # 资源名称，长度为1-128个字符，名称只能包含中英文、数字、点（.）、下划线（_）和中划线（-）

    Region: str  # 地域ID，指定资源所属的物理区域

    BMCTypeName: Optional[str] = None  # BMC类型名称，标识硬件厂商的BMC类型（如Dell iDRAC、HP iLO等）

    CompanyID: Optional[int] = None  # 租户ID，指定裸金属所属的租户，若为0或超级管理员ID则表示未分配租户

    CustomMetricsPath: Optional[str] = None  # 自定义监控地址，用于Prometheus等监控系统采集指标

    ExpireTime: Optional[int] = None  # 过期时间，Unix时间戳（秒），到期后资源可能被回收

    IPMIIP: Optional[str] = None  # IPMI管理IP地址，用于带外管理访问

    IPMIPassword: Optional[str] = None  # IPMI密码，用于IPMI身份验证

    IPMIUsername: Optional[str] = None  # IPMI用户名，用于IPMI身份验证

    ProjectID: Optional[str] = None  # 项目ID，用于实现资源的逻辑分组管理，当CompanyID为超级管理员或0时不需要ProjectID

    RackLocation: Optional[str] = None  # 机架位置，标识裸金属在数据中心的物理位置

    Reason: Optional[str] = None  # 申请原因，说明申请该裸金属资源的用途和目的

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，可为空

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串

