# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreatePortGroupResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    PortGroupID: Optional[str] = None  # 端口组ID，创建成功后返回的端口组唯一标识符
