# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreatePMV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    PMID: Optional[str] = None  # 裸金属ID，创建成功的裸金属实例标识
    SN: Optional[str] = None  # 序列号，从硬件获取的物理机唯一序列号
