# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateIPGroupResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    IPGroupID: Optional[str] = None  # IP组ID，创建成功后返回的IP组唯一标识符
