# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateKickstartTemplateRequest:
    """"""

    Name: str  # 模板名称

    OSDistribution: str  # 操作系统发行版

    Region: str  # 地域

    Content: Optional[str] = None  # 模板内容

    Description: Optional[str] = None  # 模板描述

    IsDefault: Optional[bool] = None  # 是否设为默认模板

    Variables: Optional[List[str]] = None  # 支持的变量列表

