# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteProductSpecificationRequest:
    """"""

    SpecificationID: str  # 规格ID，要删除的产品规格唯一标识符

