# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteAlertTemplateRuleRequest:
    """"""

    RuleID: str  # 告警规则ID，待删除的规则ID；当规则所属模板为REGION类型时不允许删除

