# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteDOSTokenRequest:
    """"""

    Name: str  # 令牌名称，令牌展示名称

    OSSID: str  # OSSID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[str] = None  # 租户ID，用于标识令牌所属的租户上下文；公司级账号需填写自身CompanyID，系统/地域管理员可不填或指定目标租户

