# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteDirectConnectRequest:
    """"""

    DirectConnectID: str  # 专线接入ID，指定要删除的专线接入资源ID，删除时会：1）先删除底层Huanghe DC资源；2）删除Taishan资源表记录；3）删除相关配额记录（DeleteSpecificationByDimension），删除失败会返回相应错误码

    Region: str  # 地域ID，指定要删除的专线接入所属的物理区域

