# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteDBSBackupRequest:
    """"""

    BackupID: str  # 备份ID，待删除的备份ID

    Region: str  # 地域ID，备份源资源所属地域

    CompanyID: Optional[int] = None  # 租户ID，备份所属租户

