# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteContainerImageTagRequest:
    """"""

    CompanyID: int  # 租户ID，用于权限验证，仅允许删除该租户拥有的标签

    ContainerImageName: str  # 镜像名称，镜像名称

    ContainerImageRepositoryID: str  # 镜像仓库ID，镜像所属仓库ID

    Region: str  # 地域，镜像仓库所属地域

    Tag: str  # 标签名称，待删除的标签名称

