# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteResourceEventNotifyRuleRequest:
    """"""

    RuleID: str  # 规则ID，资源事件通知规则ID

