# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteSecurityGroupRuleRequest:
    """"""

    CompanyID: int  # 租户ID，标识安全组所属的租户组织，用于多租户资源隔离与权限控制

    Region: str  # 地域ID，用于标识安全组所属的地理区域

    SGID: str  # 安全组ID，指定规则所属的安全组唯一标识符

    SGRuleID: str  # 安全组规则ID，指定要删除的规则唯一标识符

