# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteTrafficMirrorRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    TrafficMirrorID: str  # 流量镜像ID，待删除的流量镜像唯一标识符，资源状态必须为Available或Failed

