# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteTagRequest:
    """"""

    Key: str  # 标签键名，指定要删除的标签键，删除前会检查是否有资源绑定该标签，如有绑定则返回StatusTagHasBoundResource错误

    Values: List[str]  # 标签值列表，指定要删除的标签值，若为空则删除整个标签键及其所有值，删除时会检查该标签值是否还有资源绑定（通过uerrors.Error_TagHasBoundResource），若有绑定则无法删除并返回StatusTagHasBoundResource错误，可以批量删除多个值

    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离

