# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeletePMV2Request:
    """"""

    PMID: str  # 裸金属ID，指定要删除的裸金属实例，删除前会先在Kunlun中删除，然后解绑所有EIP，最后删除Taishan资源记录

    Region: str  # 地域ID，指定资源所属的物理区域

