# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeMySQLParamTplsRequest:
    """"""

    Region: str  # 地域ID，配置模板所属地域

    CompanyID: Optional[int] = None  # 租户ID，模板所属租户

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，默认0

    TplIDs: Optional[List[str]] = None  # 模板ID列表，筛选指定模板

