# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeNativeNodeRequest:
    """"""

    ClusterID: str  # 集群Id

    Region: str  # 地域

    CompanyID: Optional[int] = None  # 租户ID

    Limit: Optional[int] = None  # 

    NodeNames: Optional[List[str]] = None  # 节点名称列表

    Offset: Optional[int] = None  # 

