# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeRechargeRequest:
    """"""

    BeginTime: int  # 查询起始时间，充值记录创建时间的起始时间戳，单位为秒，必须小于结束时间

    EndTime: int  # 查询结束时间，充值记录创建时间的结束时间戳，单位为秒，必须大于起始时间

    CompanyID: Optional[int] = None  # 租户ID，过滤指定租户的充值记录，普通租户传自身CompanyID；系统管理员可传0或留空以查询所有租户

    FromType: Optional[str] = None  # 来源类型，保留字段，当前不会根据该字段过滤，典型值：ALIPAY/WECHAT_PAY/INNER/OFFLINE

    Limit: Optional[int] = None  # 分页大小，指定每页返回的充值记录数量

    Offset: Optional[int] = None  # 分页偏移量，指定从第几条记录开始返回

    RechargeType: Optional[str] = None  # 充值类型，保留字段，当前接口不会根据该字段过滤，填写1（现金）或2（赠金）不会影响查询结果

    UserAccountID: Optional[int] = None  # 用户账号ID，保留字段，与CompanyID等价，当前不会影响查询结果

