# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeNodeHostDeviceRequest:
    """"""

    NodeID: str  # 物理机节点ID，指定要扫描设备的物理机标识

    Region: str  # 地域ID，用于标识外置设备所在的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识请求发起租户

