# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeVMWareVMsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[VMWareVM]] = None  # VMWare虚拟机信息列表，返回VMware虚拟机详情
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的记录总数
