# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeDBSBackupPlanRequest:
    """"""

    Region: str  # 地域ID，备份计划所属地域

    BackupID: Optional[str] = None  # 备份ID，筛选指定备份

    CompanyID: Optional[int] = None  # 租户ID，用于筛选指定租户的计划

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，默认0

    PlanID: Optional[str] = None  # 备份计划ID，筛选指定计划

    SrcResourceID: Optional[str] = None  # 备份源ID，筛选指定备份源

