# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeVPNGWRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Keyword: Optional[str] = None  # 搜索关键词，模糊匹配VPN网关名称或ID

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量，取值范围：1-100

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询，取值范围：≥0

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，按项目过滤VPN网关，支持多个项目

    Status: Optional[List[str]] = None  # 状态列表，按状态过滤VPN网关，取值与VPN网关状态一致

    VPNGWIDs: Optional[List[str]] = None  # VPN网关ID列表，指定要查询的VPN网关ID，支持批量查询

