# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeFSFileResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[FileInfo]] = None  # 文件信息列表，返回目录下的文件与子目录
    TotalCount: Optional[int] = None  # 总记录数，符合条件的文件数量
