# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeRecycledResourceRequest:
    """"""

    Region: str  # 地域ID，指定回收站资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，指定回收站资源所属的租户

    Keyword: Optional[str] = None  # 搜索关键词，用于回收站资源全文检索

    Limit: Optional[int] = None  # 分页大小，默认10

    Offset: Optional[int] = None  # 分页偏移量，默认0

    ParentResourceID: Optional[str] = None  # 父资源ID，用于按父资源查询回收站资源，支持VPC/子网/网段父资源；VPC返回子网，子网返回VM，网段返回EIP

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，筛选项目维度的回收站资源

    ResourceIDs: Optional[List[str]] = None  # 资源ID列表，指定需要查询的回收站资源ID，未指定时返回该租户在该地域的全部回收站资源

    Status: Optional[str] = None  # 状态，保留字段，当前不参与过滤

