# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeNATGWRuleResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[NATGWRuleInfo]] = None  # SNAT规则详情列表
    TotalCount: Optional[int] = None  # 总记录数，用于分页计算
