# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeBucketsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[BucketInfo]] = None  # 桶信息列表，查询到的桶信息
    TotalCount: Optional[int] = None  # 总记录数，符合条件的桶数量
