# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeDBSBackupRequest:
    """"""

    BackupIDs: Optional[List[str]] = None  # 备份ID列表，筛选指定备份

    BackupType: Optional[str] = None  # 备份类型，取值Logical/Physical/Snapshot/Incremental

    CompanyID: Optional[int] = None  # 租户ID，用于筛选指定租户的备份

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，默认0

    PlanID: Optional[str] = None  # 计划ID，筛选指定备份计划

    SrcResourceID: Optional[str] = None  # 源资源ID，备份源资源ID

    SrcResourceRegion: Optional[str] = None  # 源数据地域，备份源资源所属地域

    StorageID: Optional[str] = None  # 存储池ID，筛选指定存储池

