# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeSnapshotResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[SnapshotInfo]] = None  # 快照信息列表，查询到的快照信息
    TotalCount: Optional[int] = None  # 总记录数，符合条件的快照数量
