# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeAuditLogResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    AuditEvents: Optional[str] = None  # 审计日志事件，从资源注解hhpaas.AK_AUDIT_EVENTS中读取的当前配置
    Infos: Optional[List[AuditLogInfos]] = None  # 审计日志列表，包含所有匹配的审计日志详细信息，按执行时间倒序排列
    TotalCount: Optional[int] = None  # 总数，成功解析且未被IgnoreQuery过滤的审计日志条目数
