# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeNetworkTopologyResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[InspectionNetwork]] = None  # 网络拓扑信息列表，包含资源的网络连接详情
    SummaryInfos: Optional[List[ResourceUsageInfo]] = None  # 资源使用总计，按资源类型统计的汇总信息，ResourceType对应InspectionNetwork.ResourceTypeAttr
    TotalCount: Optional[int] = None  # 总数，符合条件的网络拓扑记录总数量
