# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeBindableTagResourceRequest:
    """"""

    Key: str  # 标签键名，用于查询可绑定该标签键的资源列表

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceType: str  # 资源类型，标识要查询的资源种类，支持包括DISK、VM等多种资源类型，如果传入无效类型会返回StatusResourceTypeInvalid错误

    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离，普通租户需填写自身CompanyID；当CompanyID=200000231（系统管理员租户）时仅能查询SEGMENT/DIRECTCONNECT/FLATNETWORK/TRAFFICMIRROR等运维资源

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询

