# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeComputeClassVMsAddToDRSRuleRequest:
    """"""

    Region: str  # 地域ID

    SetID: str  # 计算集群ID，指定要查询候选虚拟机的ComputeClass

    CompanyID: Optional[int] = None  # 租户ID

    Keyword: Optional[str] = None  # 关键词，可按虚拟机ID或名称模糊过滤结果

    Limit: Optional[int] = None  # 分页大小，默认10

    Offset: Optional[int] = None  # 分页偏移量，默认0

