# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeOPLogNotifyRuleRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，过滤指定租户的操作日志通知规则

    Keyword: Optional[str] = None  # 搜索关键字，按规则名称模糊搜索

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，Limit为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

