# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeFSRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    FSIDs: Optional[List[str]] = None  # 文件存储实例ID列表，用于查询指定文件存储信息

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊匹配文件存储名称或备注

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，用于筛选指定项目组下的文件存储资源

    Status: Optional[List[str]] = None  # 文件存储状态列表，用于筛选指定状态的文件存储资源

