# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeComputeClassDRSScoreRequest:
    """"""

    Region: str  # 地域ID

    SetID: str  # 计算集群ID

    CompanyID: Optional[int] = None  # 租户ID

