# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeExternalStorageTypeResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ExternalStorageTypeInfo]] = None  # 
    TotalCount: Optional[int] = None  # 
