# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeWithdrawRequest:
    """"""

    BeginTime: int  # 查询起始时间，提现记录创建时间的起始时间戳，单位为秒，必须小于结束时间

    EndTime: int  # 查询结束时间，提现记录创建时间的结束时间戳，单位为秒，必须大于起始时间

    CompanyID: Optional[int] = None  # 租户ID，过滤指定租户的提现记录，不指定则查询所有租户（需系统管理员权限）

    Limit: Optional[int] = None  # 分页大小，指定每页返回的提现记录数量

    Offset: Optional[int] = None  # 分页偏移量，指定从第几条记录开始返回

