# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeParametersHistoriesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ParametersHistoriesInfos]] = None  # 参数修改历史列表，来源于审计日志解析结果，按更新时间倒序排列
    TotalCount: Optional[int] = None  # 总数，匹配条件的参数修改条目数量，按照更新时间倒序统计
