# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribePaaSInstanceRequest:
    """"""

    CompanyID: int  # 租户ID，必须与资源所属租户一致；普通租户携带该字段用于权限校验，平台管理员可填写任意值

    Region: str  # 地域ID，指定资源所在地域

    ResourceID: str  # PaaS资源ID，支持所有PaaS产品（MySQL、Redis、LB、NATGW、VPNGW、OSS、FS等），若租户不匹配将返回错误

