# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeOPLogsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[OPLogInfo]] = None  # 操作日志详情列表，返回符合筛选条件的日志集合
    TotalCount: Optional[int] = None  # 总记录数，匹配条件的日志数量
