# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeTrafficMirrorResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[TrafficMirrorInfo]] = None  # 流量镜像信息列表，包含流量镜像的详细信息
    TotalCount: Optional[int] = None  # 流量镜像总数，符合查询条件的记录总数
