# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeExternalDiskRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    AttachResourceID: Optional[str] = None  # 挂载的资源ID，筛选指定资源挂载的外置存储盘

    CompanyID: Optional[int] = None  # 租户ID，筛选指定租户的外置存储资源

    CompanyOnly: Optional[int] = None  # 租户过滤标识，非0仅返回已分配给租户的记录

    ComputeSetID: Optional[str] = None  # 计算集群ID，用于筛选指定计算集群下的外置存储盘

    Keyword: Optional[str] = None  # 搜索关键词，支持资源名称模糊匹配

    Limit: Optional[int] = None  # 分页大小，默认10

    Offset: Optional[int] = None  # 分页偏移量，默认0

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，筛选项目内的外置存储资源

    SetID: Optional[str] = None  # 存储集群ID，筛选指定存储集群下的外置存储盘

    SetType: Optional[str] = None  # 存储集群类型，用于过滤指定类型的存储集群

    ShareAbleFilter: Optional[str] = None  # 共享盘筛选标识，true仅返回共享盘，false仅返回普通盘，空值返回全部

