# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeProductResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ProductTypeInfo]] = None  # 产品列表，返回产品类型与授权启用信息
    TotalCount: Optional[int] = None  # 总记录数，匹配条件的产品数量
