# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeResourceTemplateRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Keyword: Optional[str] = None  # 查询关键字，用于模糊搜索模板名称或备注

    Limit: Optional[int] = None  # 分页大小，用于限制单次返回条数

    Offset: Optional[int] = None  # 分页偏移量，用于指定返回结果起始位置

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于筛选指定项目下的模板

    Region: Optional[str] = None  # 地域ID，用于筛选模板所属地域

    TemplateIDs: Optional[List[str]] = None  # 模板ID列表，用于精确查询指定的模板

