# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeApplicationRequest:
    """"""

    ApplicationID: Optional[str] = None  # 审批工单ID，指定时返回单个审批详情（包含所有审批节点信息），不指定时返回审批列表，指定此参数时会忽略其他查询条件，直接返回该审批的完整信息

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，管理员租户CompanyID固定为200000231，普通租户必须填写自身的CompanyID，系统会结合登录态判定可见的审批范围

    Keyword: Optional[str] = None  # 搜索关键字，用于通过搜索引擎查找匹配的审批工单，支持模糊搜索审批名称、ID等信息

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量

    MemberID: Optional[int] = None  # 子账号ID，兼容历史接口的保留字段，接口会根据当前登录用户自动识别MemberID并按权限过滤审批记录，建议填写当前子账号ID以便审计

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询

    ResourceType: Optional[str] = None  # 资源类型，用于过滤指定资源类型的审批工单，如DISK、VM、FS等，不指定时返回所有类型

