# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeSetAllocateUsageRequest:
    """"""

    IncludeAllClusters: Optional[bool] = None  # 当为true时，即使不指定Region也返回所有地域下的所有集群信息

    Region: Optional[str] = None  # 地域ID，若不指定则查询所有有权限访问的地域，返回结果以地域为维度；若指定则查询单个地域，返回结果以地域下的集群为维度

