# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribePlatformStorageDiskResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[PlatformStorageDiskInfo]] = None  # 磁盘信息，平台通用存储云盘列表
    TotalCount: Optional[int] = None  # 
