# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeCIStatusRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    ResourceIDs: List[str]  # 资源ID列表，精确匹配需要查询的资源标识

    ResourceType: str  # 资源类型，查询状态的目标资源类别

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于资源分组管理

    States: Optional[List[str]] = None  # 状态列表，过滤资源的运行状态

