# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeUserResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[TenantTenantInfoRes]] = None  # 租户详细信息列表，查询结果返回并用于展示租户基础信息、状态与额度等信息
    TotalCount: Optional[int] = None  # 查询到的租户总记录数，用于分页展示；当使用产品类型筛选时已排除禁用租户
