# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class DescribeAlertTemplateTargetResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[AlertTemplateTargetInfo]] = None  # 绑定关系详细信息列表，绑定关系列表
    TotalCount: Optional[int] = None  # 绑定关系总数，满足查询条件的绑定关系总数
