# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeAlertNotifyReceiverRequest:
    """"""

    NotifyGroupID: str  # 通知组ID，查询指定通知组下的接收人，若指定则查询该组的所有接收人

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，取值范围1-100，Limit为0时默认10，结果按创建时间倒序返回

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，与Limit配合遍历所有接收人

