# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeNATGWPolicyRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Keyword: Optional[str] = None  # 搜索关键词，用于按规则关键字模糊搜索DNAT规则

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量

    NATGWID: Optional[str] = None  # NAT网关ID，用于筛选指定NAT网关的DNAT规则

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询

    PolicyIDs: Optional[List[str]] = None  # DNAT规则ID列表，用于筛选指定DNAT规则

