# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DetachDiskRequest:
    """"""

    DiskID: str  # 磁盘ID，要解绑的磁盘标识，共享盘解绑时只会移除当前ResourceID的绑定，不会影响其他绑定实例

    Region: str  # 地域ID，指定资源所属的地域

    ResourceID: str  # 资源ID，要解绑磁盘的目标资源标识

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    ResourceType: Optional[str] = None  # 资源类型，挂载目标的资源类型，当前仅用于兼容调用

