# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DetectBMCTypeV2Request:
    """"""

    IPMIIP: str  # IPMI管理IP地址，用于连接BMC进行类型检测，必须是有效的IPv4地址

    IPMIPassword: str  # IPMI密码，用于IPMI身份验证

    IPMIUsername: str  # IPMI用户名，用于IPMI身份验证

    Region: str  # 地域ID，指定资源所属的物理区域

