# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DisableCompanyProductTypeRequest:
    """"""

    CompanyIDs: List[int]  # 租户ID列表，用于指定要关闭服务的租户；仅支持单个租户，实际取CompanyIDs[0]

    ProductType: str  # 产品类型，指定要关闭的产品服务

    Region: str  # 地域ID，指定产品服务所属区域

