# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DowngradeLBRequest:
    """"""

    CPU: int  # CPU核数，负载均衡降级后的CPU核数，必须小于当前CPU核数，且负载均衡必须处于Stopped状态

    LBID: str  # 负载均衡ID，用于定位需要降级规格的负载均衡实例，负载均衡必须处于Stopped状态才能降级

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

