# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class EnableASGroupRequest:
    """"""

    GroupID: str  # 伸缩组ID，要启用的伸缩组的唯一标识符，启用后伸缩组将开始自动伸缩功能，根据监控指标触发扩缩容操作

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Region: Optional[str] = None  # 地域ID，指定伸缩组所属的物理区域

