# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FlushBucketRequest:
    """"""

    BucketName: str  # 桶名称，存储桶名称

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，用于匹配被清理桶所属的租户并清理该租户在本地的上传缓存；公司级账号需填写自身CompanyID，系统/地域管理员可不填或传0

