# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FSLoginResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SessionID: Optional[str] = None  # 会话ID，用于后续操作的会话标识，有效期10分钟
