# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GenerateVMWareConsoleTicketRequest:
    """"""

    ConfigName: str  # vmware配置名称，指定VMware连接配置标识

    Datacenter: str  # 数据中心名称，VMware数据中心标识

    VMID: str  # 虚拟机ID，VMware虚拟机标识

    VMName: str  # 虚拟机名称，VMware虚拟机显示名称

