# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class GetRegionConfigResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Info: Optional[RegionConfigBaseInfo] = None  # 地域配置信息
