# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetWithdrawableAmountResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Amount: Optional[float] = None  # 现金余额，租户账户中的外部账户（现金）余额，单位为元，精确到分
    AmountFree: Optional[float] = None  # 赠金余额，租户账户中的内部账户（赠金）余额，单位为元，精确到分
    WithdrawableAmount: Optional[float] = None  # 可提现现金余额，外部账户中可提现的金额，单位为元，精确到分，当前等于现金余额
    WithdrawableAmountFree: Optional[float] = None  # 可提现赠金余额，内部账户中可提现的金额，单位为元，精确到分，当前等于赠金余额
