# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetPMJNLPFileV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    JNLPContent: Optional[str] = None  # JNLP文件内容，XML格式的JNLP文本
