# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetResourceUsageRequest:
    """"""

    ResourceUsageID: str  # 资源用量ID，指定要查询的资源用量报告

