# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class GetPriceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Info: Optional[VpnPriceInfo] = None  # VPN价格信息，用于展示VPN网关询价结果
