# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetMigratePaaSInstancePriceRequest:
    """"""

    CompanyID: int  # 租户ID，保留字段

    InstanceID: str  # 实例ID，要查询差价的虚拟机，必须属于该PaaS资源

    Region: str  # 地域ID，指定资源所属地域

    ResourceID: str  # 资源ID，需为支持计算迁移的PaaS资源且处于AVAILABLE状态

    AbortMigrate: Optional[bool] = None  # 是否为取消迁移，true表示按照旧集群（AK_MIGRATE_OLD_SET_HOST_IP记录）计算回滚差价；false表示按MigrateComputeSetID计算迁移差价

    MigrateComputeSetID: Optional[str] = None  # 目标计算集群ID，AbortMigrate为false时必填并会被校验；为true时忽略此字段

    MigrateHostIP: Optional[str] = None  # 目标宿主机IP，可选字段；当前计费逻辑未使用，当AbortMigrate为true时忽略此值

