# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetRedisPriceRequest:
    """"""

    HighAvailability: str  # 高可用类型，影响价格计算，取值范围：Standalone（单机版）、ActiveStandy（高可用/主备版）；与订单中副本数一致

    Memory: int  # 内存大小，单位MiB

    Region: str  # 地域ID，资源所属的物理区域

    VMType: str  # 计算集群类型，用于计算价格

    ChargeType: Optional[str] = None  # 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户

    DiskSetType: Optional[str] = None  # 存储集群类型，实例数据盘所属存储集群类型

    Quantity: Optional[int] = None  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1

    RedisID: Optional[str] = None  # Redis实例ID，用于查询升级/变更价格

    Threads: Optional[int] = None  # 线程数量，Redis7.0有效

