# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetVIPDiffPriceRequest:
    """"""

    Bandwidth: int  # 目标带宽，单位Mbps，取值范围由线路规格配置确定，默认为1-20000，用于计算调整到目标带宽的价格差异

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VIPID: str  # VIPID，VIP的唯一标识符，用于指定需要调整带宽的外网VIP

