# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class GetSSOConfigResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Info: Optional[SSOConfigInfo] = None  # SSO单点登录配置信息
