# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetClusterPaymentOfPremiumRequest:
    """"""

    Region: str  # 地域

    ClusterID: Optional[str] = None  # ClusterID

    CompanyID: Optional[int] = None  # 租户ID

    GPU: Optional[int] = None  # GPU的颗数

    GPUMdevName: Optional[str] = None  # GPU的规格

    SuperNode: Optional[str] = None  # 超级节点名称

