# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetOSSPriceRequest:
    """"""

    DiskSetType: str  # 存储集群类型，数据盘所在存储集群类型

    DiskSpace: int  # 存储容量，单位GiB，最小值100

    Region: str  # 地域ID，指定资源所属的地域

    VMType: str  # 计算集群类型，系统会根据集群架构自动确定系统盘大小

    CPU: Optional[int] = None  # CPU核数，用于价格计算，取值范围：2、4、6、8、10、12、14、16

    ChargeType: Optional[str] = None  # 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    OSSID: Optional[str] = None  # 对象存储ID，空表示新建价格，非空表示升级价格

    Quantity: Optional[int] = None  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1

