# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class GetKickstartTemplateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Template: Optional[KickstartTemplateInfo] = None  # 模板信息
