# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetConfigRequest:
    """"""

    ConfigKey: str  # 配置键，要查询的全局配置项唯一标识符

