# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class GetRedisPriceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Info: Optional[RedisPriceInfo] = None  # 价格信息，计费价格信息
