# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListRegionConfigSyncStatusRequest:
    """"""

    Region: str  # 地域ID，指定要查询配置同步状态的地域

    ConfigKeys: Optional[List[str]] = None  # 配置键列表，指定要查询同步状态的地域配置项；不传则返回指定地域全部配置项的同步状态

