# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class ListMemberTagsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[AuthorizationInfo]] = None  # 角色授权信息详情，返回账号授权关系列表
    TotalCount: Optional[int] = None  # 总记录数，匹配条件的授权数量
