# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class ListProductResourcesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ProductResource]] = None  # 产品资源详情列表，返回产品与资源类型关系
    TotalCount: Optional[int] = None  # 总记录数，匹配条件的产品资源数量
