# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ustack.services.models import *


@dataclass
class ListRegionConfigsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[RegionConfigCategoryInfo]] = None  # 地域配置分类列表，按类别分组的地域配置信息
    TotalCount: Optional[int] = None  # 分类总数
