# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListProjectsRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，用于限定查询的租户范围

    Keyword: Optional[str] = None  # 关键词，用于按项目名称检索

    Limit: Optional[int] = None  # 分页大小，控制单次返回数量

    Offset: Optional[int] = None  # 分页偏移量，用于分页起点

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，用于筛选指定项目集合

