# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MigrateMgrVMStorageRequest:
    """"""

    DstSetID: str  # 目标存储集群ID，迁移的目标存储池标识

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待迁移存储的虚拟机标识

    Bandwidth: Optional[int] = None  # 迁移带宽，限制迁移速率，单位：MiB/s

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

