# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PrometheusQueryRequest:
    """"""

    Query: str  # PromQL查询表达式，用于查询即时监控指标数据

    Region: str  # 地域，指定查询哪个地域的Prometheus监控数据；若地域不存在将返回StatusRegionNotExist错误

    Limit: Optional[int] = None  # 返回结果数量限制，预留字段，当前实现未对Prometheus返回结果做截断限制

    Time: Optional[str] = None  # 查询时间点，支持Unix时间戳（秒）或RFC3339格式；解析失败或不填写时会自动使用当前时间

    Timeout: Optional[str] = None  # 查询超时时间，支持Go duration格式（如30s、1m），若解析失败、<=0或超过2m将返回参数错误

