# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RechargeRequest:
    """"""

    Amount: float  # 充值金额，单位：元；现金充值取值范围：100.00-500000.00，内部赠金充值取值范围：100.00-10000000.00

    CompanyID: int  # 租户ID，指定要充值的租户唯一标识

    FromType: str  # 来源类型，现金充值时必须明确渠道：ALIPAY/WECHAT_PAY/OFFLINE/SINPAY；内部赠金充值时该字段忽略并自动视为INNER

    RechargeType: int  # 充值类型，1表示现金充值（REAL），2表示内部赠金（FREE），仅当选择现金充值时才会校验凭证唯一性

    SerialNo: Optional[str] = None  # 序列号，充值的序列号或凭证号，现金充值必须唯一；若重复会返回序列号重复的错误

