# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ReleaseEIPRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    EIPID: str  # EIP资源ID，要释放的弹性IP唯一标识符，释放前会校验是否允许删除及是否绑定弹性伸缩组

    Region: str  # 地域ID，用于标识资源所属的地理区域

