# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RenameProjectRequest:
    """"""

    Name: str  # 项目名称，用于更新项目显示名称，长度为1-50个字符，只能包含中英文、数字、点、下划线和中划线

    ProjectID: str  # 项目组ID，用于指定要重命名的项目

    Remark: Optional[str] = None  # 备注，用于补充说明项目用途和范围，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，

