# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RenewResourceRequest:
    """"""

    Region: str  # 地域ID，必须与资源实际所在地域一致，用于匹配历史订单

    ResourceID: str  # 资源ID，要续费的资源唯一标识；若传入虚拟机启动盘（ID以-boot结尾）会自动改为对应虚拟机ID并同时续费启动盘

    ChargeType: Optional[str] = None  # 计费类型，取值：Dynamic/Month/Year，后台会阻止降级（例如Year改为Month），安全产品只允许Month；同时兼容传入大写值HOUR/MONTH/YEAR

    CompanyID: Optional[int] = None  # 租户ID，从该租户账户扣费

    Quantity: Optional[int] = None  # 续费时长，按Hour续费时系统固定为1小时；按Month续费最多11个月，按Year续费最多5年

