# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResetMySQLPasswordRequest:
    """"""

    CompanyID: int  # 租户ID，资源所属租户

    MySQLID: str  # MySQL实例ID，指定要修改密码的MySQL实例；注意：资源必须为AVAILABLE且状态为Running

    Password: str  # root密码，满足paaspassword校验规则

    Region: str  # 地域ID，指定资源所属的物理区域

