# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResizePlatformStorageDiskRequest:
    """"""

    DiskID: str  # 磁盘ID，待扩容的平台通用存储云盘ID

    DiskSpace: int  # 磁盘大小，扩容后的目标容量，单位GiB

    Region: str  # 地域ID，指定资源所属的物理区域

