# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResumeDBSBackupRequest:
    """"""

    PlanID: str  # 计划ID，备份计划的ID；仅支持ScheduleType=Timer的计划

    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离

    Region: Optional[str] = None  # 地域，备份源的地域

