# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RetryInstallTaskV2Request:
    """"""

    CompanyID: int  # 租户ID，标识当前执行重试操作的租户，后台会校验任务所属租户与裸金属当前租户一致，不允许管理员租户（0或超级管理员）直接重试

    Region: str  # 地域ID，指定任务所在地域，系统会基于地域选择Kunlun集群执行重试

    TaskID: str  # 装机任务ID，重试目标任务的唯一标识，后台将基于该ID读取任务详情、核验裸金属状态并重新下发装机流程

