# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class S3LoginRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的地域

    Scenes: str  # 使用场景，ImageUpload 表示镜像上传使用 S3（系统自动使用 mirror 桶），OSS 表示访问指定对象存储实例并复用请求中的桶信息

    Bucket: Optional[str] = None  # 桶名称，Scenes=OSS 时指定目标桶；Scenes=ImageUpload 场景固定登录 mirror 桶，可不填

    CompanyID: Optional[int] = None  # 租户ID，标识请求所属租户，Scenes=OSS 且当前登录账号为公司级权限时必须填写，用于校验对象存储资源归属

    ID: Optional[str] = None  # 目标S3资源ID，Scenes=OSS 时必填且必须以 oss- 开头，对应对象存储实例ID

