# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SetComputeClassDRSVMRuleRequest:
    """"""

    Region: str  # 地域ID，指定要操作的物理区域

    SetID: str  # 计算集群ID，指定要更新黑名单的ComputeClass

    Add: Optional[bool] = None  # 是否添加黑名单，true为新增或更新黑名单，false表示删除指定VM规则

    CompanyID: Optional[int] = None  # 租户ID，用于按租户范围筛选可操作的DRS配置

    Reason: Optional[str] = None  # 备注信息，可选字段，后台会对内容进行Base64编码后写入Huanghe

    Type: Optional[str] = None  # 规则类型，Manual表示手工迁移保护，Ignore表示忽略DRS迁移，仅在Add为true时必填

    VMID: Optional[str] = None  # 虚拟机ID，指定需要添加或移除的虚拟机，必须存在于当前集群

