# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SetAccountQuotaRequest:
    """"""

    FactorType: str  # 配额因子，指定配额计量维度，取值范围：FACTOR_AMOUNT（资源个数）、FACTOR_CPU（vCPU核数）、FACTOR_MEMORY（内存GB）、FACTOR_DISK（磁盘容量GB）、FACTOR_EIP（公网带宽Mbps）、FACTOR_VGPU（虚拟GPU数）、FACTOR_GPU（GPU卡数）

    Quota: int  # 配额值，要设置的配额数量，不能小于当前已使用量

    Region: str  # 地域ID，指定要设置配额的地域

    ResourceType: str  # 资源类型，指定配额的资源类型，如VM、DISK、IP等

    Allocation: Optional[str] = None  # 集群配额分配JSON字符串，指定计算或存储集群的配额分配，若不指定则默认为空对象{}，格式如{"cluster-1":50,"cluster-2":50}

    CompanyID: Optional[int] = None  # 租户ID，指定要设置配额的租户，用于多租户环境下的配额管理，0表示设置默认配额

