# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TestPMIPMIV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    BMCInfo: Optional[str] = None  # BMC信息，包含BMC版本、厂商等详细信息
    SerialNumber: Optional[str] = None  # 序列号，从IPMI接口获取的物理机序列号
    Success: Optional[bool] = None  # 测试是否成功，true表示IPMI连接成功，false表示连接失败
