# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnbindEIPFromVPNRequest:
    """"""

    EIPID: str  # 弹性公网IPID，待解绑的EIP，需与当前绑定一致

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VPNGWID: str  # VPN网关ID，待解绑EIP的VPN网关唯一标识，需处于Running或Stopped状态且资源为最新版本

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

