# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnbindStorageFromDBSRequest:
    """"""

    StorageID: str  # 备份存储池ID，待解绑的存储池ID；注意：存储池存在备份数据或绑定备份计划时不可解绑

    CompanyID: Optional[int] = None  # 租户ID，存储池所属租户

