# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnbindAlertTemplateRequest:
    """"""

    Region: str  # 地域，目标资源所属地域

    TargetID: str  # 目标资源ID，待解绑告警模板的资源ID，非管理员租户需验证资源归属权限

