# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMSetBoundStorageSetRequest:
    """"""

    Region: str  # 地域ID，指定计算集群所属的物理区域

    SetID: str  # 计算集群ID，指定要绑定存储集群的计算集群唯一标识

    StorageSetIDs: List[str]  # 存储集群ID列表，指定要绑定到该计算集群的存储集群ID列表，必须从该计算集群的物理绑定存储列表（StorageClassList）中选择，用于限制虚拟机可使用的存储资源，支持RBD、CJFS、Ustorbs、UDisk、QoL等存储Provider类型

