# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateAuditLogRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceID: str  # 资源ID，指定要开关审计日志的数据库资源，如MySQL实例，资源状态必须为AVAILABLE且运行状态为Running

    ResourceType: str  # 资源类型，目前仅支持MYSQL，传入其他取值会被校验拒绝

    AuditEvents: Optional[str] = None  # 审计日志事件，写入资源注解的事件列表，多个事件用逗号分隔；未填写时默认写入QUERY

    AuditStatus: Optional[int] = None  # 审计状态，0表示关闭审计日志，1表示开启审计日志，状态必须为以下两个值之一

