# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateLBLogRequest:
    """"""

    LBID: str  # 负载均衡ID，用于定位需要更新访问日志配置的负载均衡实例

    LogAccessEnable: str  # 访问日志开关，是否开启访问日志，取值范围：On、Off

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    LogOssID: Optional[str] = None  # 日志存储OSS ID，用于存储访问日志的OSS实例ID，当访问日志开关为On时必填，该OSS实例必须存在、状态可用，且与负载均衡位于同一VPC

