# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateIsolationGroupRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    IGID: str  # 隔离组ID，指定要更新的隔离组

    Region: str  # 地域ID，用于标识资源所属的地理区域

    IsEnable: Optional[bool] = None  # 是否启用，设置策略是否生效，不传表示不修改

    IsForce: Optional[bool] = None  # 是否强制执行，设置策略执行方式，不传表示不修改

    PolicyObj: Optional[List[str]] = None  # 策略对象列表，用于更新隔离组策略对象

    PolicyType: Optional[str] = None  # 策略类型，用于更新隔离组策略类型，取值VMAffinity/VMAntiAffinity

