# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateCompanyNameRequest:
    """"""

    CompanyID: int  # 租户ID，请求传入用于定位要更新名称的租户

    Name: str  # 租户名称，请求传入并更新租户及主账号显示名称；仅在租户与主账号为可用状态时可更新

