# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateBucketLifecycleRuleRequest:
    """"""

    BucketName: str  # 桶名称，存储桶名称

    ExpirationDays: int  # 过期天数，对象过期天数

    ExpirationType: str  # 过期类型，生命周期规则适用对象，取值范围：CurrentVersion（当前版本）、NonCurrentVersion（非当前版本）、Multipart（碎片）

    LifeCycleID: str  # 生命周期规则ID，生命周期规则标识

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    ObjectKeyPrefix: Optional[str] = None  # 对象名前缀，用于匹配生命周期规则

    TransitionStorageClass: Optional[str] = None  # 归档存储类，生命周期转储的存储类型

