# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateLoginWhitelistRequest:
    """"""

    CompanyID: int  # 租户ID，请求传入用于设置登录白名单的租户

    Whitelist: Optional[str] = None  # IP白名单，请求传入并设置允许登录的IP或网段，多个值用逗号分隔；为空表示不限制；安全控制场景使用，仅主账号或系统管理员可设置

