# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMCPUHypervisorRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID

    CPUHypervisorDisable: Optional[bool] = None  # 是否隐藏虚拟化标记，true表示隐藏，false表示不隐藏

    CompanyID: Optional[int] = None  # 租户唯一标识ID

