# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMSetBoundImageRequest:
    """"""

    ImageIDs: str  # 镜像ID列表，指定要绑定到该计算集群的镜像ID，支持两种格式：1）特殊值all表示绑定所有镜像；2）以逗号分隔的多个镜像ID（不支持空字符串），通过UpdateVMSetBoundImage接口实现镜像绑定限制

    Region: str  # 地域ID，指定计算集群所属的物理区域

    SetID: str  # 计算集群ID，指定要绑定镜像的计算集群唯一标识

