# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateDiscountRequest:
    """"""

    ChargeType: str  # 计费类型，指定计费方式，Dynamic表示按小时计费（兼容传HOUR）、Month表示按月计费（兼容MONTH）、Year表示按年计费（兼容YEAR）

    CompanyID: int  # 租户ID，指定要更新折扣的租户唯一标识，为该租户设置专属折扣

    Discount: float  # 折扣比例，设置的折扣百分比，100表示无折扣，50表示五折，设置为0表示免费

    ProductID: str  # 产品ID，指定要更新折扣的产品唯一标识

    Region: str  # 地域ID，指定价格所属的物理区域

    SetType: str  # 集群类型，指定资源所属的集群类型标识，从DescribeSet接口获取

