# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateIPGroupRequest:
    """"""

    IPGroupID: str  # IP组ID，指定要更新的IP组唯一标识符

    Region: str  # 地域ID，用于标识IP组所属的地理区域

    Rules: str  # IP地址规则，新的IP地址列表，将替换现有规则；逗号分隔，支持单个IP或CIDR地址段

    CompanyID: Optional[int] = None  # 租户ID，标识IP组所属的租户组织，用于多租户资源隔离与权限控制

