# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateASGroupRequest:
    """"""

    AsMetric: str  # 伸缩指标，用于触发自动伸缩的监控指标名称，支持的指标：cpu（CPU使用率）、memory（内存使用率，需镜像支持QGA）、vs_connection_l7（七层连接数）、vs_qps_l7（七层QPS）、vs_rt_l7（七层响应时间）、vs_connection_l4（四层连接数）、vs_cps_l4（四层CPS）、bandwidth（EIP带宽），水平伸缩支持所有指标除bandwidth外，垂直伸缩支持cpu、memory、bandwidth，HTTP/HTTPS协议的VServer仅支持L7指标，TCP/UDP协议仅支持L4指标

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    GroupID: str  # 伸缩组ID，要更新的伸缩组的唯一标识符

    Region: str  # 地域ID，指定伸缩组所属的物理区域

    Threshold: str  # 伸缩阈值，当监控指标超过此阈值时触发扩容，低于此阈值时触发缩容（若AllowDecrease为true），单位：cpu/memory为百分号（0-100），vs_connection_l7/vs_connection_l4为连接数（个），vs_qps_l7为请求数（requests/s），vs_rt_l7为毫秒（ms），vs_cps_l4为连接数（connections/s），bandwidth为Mbps

    AllowDecrease: Optional[bool] = None  # 是否允许缩容，当伸缩模式为Horizontal或Vertical时可更新，控制伸缩组是否可以自动缩减资源规模或规格

    MaxInstance: Optional[int] = None  # 最大实例数，当伸缩模式为Horizontal时可更新，伸缩组允许的最大成员数量，必须大于等于MinInstance，取值范围0-100

    MaxSpecification: Optional[str] = None  # 最大规格，当伸缩模式为Vertical时可更新，指定资源可扩容的最大规格上限，对于VM类型，若AsMetric为cpu则表示最大CPU核数，若AsMetric为memory则表示最大内存GB数；对于EIP类型，表示最大带宽Mbps，必须大于当前资源的规格，且资源必须支持热升级（镜像需支持Hotplug）

    MinInstance: Optional[int] = None  # 最小实例数，当伸缩模式为Horizontal时可更新，伸缩组维持的最小成员数量，取值范围0-100

    Port: Optional[int] = None  # 监听端口，当伸缩组类型为VS时可更新，用于指定伸缩成员加入负载均衡后端服务节点时使用的端口号

    TemplateID: Optional[str] = None  # 虚拟机模板ID，当伸缩模式为Horizontal时可更新，用于创建新伸缩成员时的虚拟机配置模板，更新模板时新模板的VPC必须与旧模板一致，且若AsMetric为memory则模板使用的镜像必须支持QGA

    WarmTime: Optional[int] = None  # 预热时间，当伸缩模式为Horizontal时可更新，新创建的伸缩成员从加入伸缩组到开始参与指标计算的等待时长（秒），取值范围1-3600秒

    Weight: Optional[int] = None  # 负载均衡权重，当伸缩组类型为VS时可更新，用于指定伸缩成员加入负载均衡后端服务节点时的权重值

