# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMISOSlotRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待修改配置的虚拟机标识

    ISOTotal: Optional[int] = None  # ISO插槽配额，配置的ISO挂载插槽数量，需重启生效

