# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VerifyEmailAvailabilityRequest:
    """"""

    Receiver: str  # 收件人邮箱地址，用于验证邮件服务器是否可用

