# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class WithdrawRequest:
    """"""

    CompanyID: int  # 租户ID，指定要提现的租户唯一标识，从该租户账户扣除提现金额

    SrcAccountType: str  # 源账户类型，指定提现的账户类型，FREE表示从内部账户（赠金）提现，REAL表示从外部账户（现金）提现

    WithdrawAmount: float  # 提现金额，要提现的金额，单位为元，必须大于0且不能超过账户可提现余额

