# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AddVMNICRequest:
    """"""

    FlatNetworkID: str  # 扁平网络ID

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    IP: Optional[str] = None  # ip地址，可选参数，为空则由平台分配

    InAverageBandwidth: Optional[int] = None  # 入向平均带宽，用于QoS流量整形；0表示不限制，单位Mbps

    LinkState: Optional[str] = None  # 启用状态，可选值：up（默认），down，可选参数

    MAC: Optional[str] = None  # mac地址，可选参数，为空则由平台分配

    Model: Optional[str] = None  # 网卡型号，支持e1000，virtio（默认），可选参数

    OutAverageBandwidth: Optional[int] = None  # 出向平均带宽，用于QoS流量整形；0表示不限制，单位Mbps

    Queues: Optional[int] = None  # 网卡队列数，可选参数，为0则根据cpu计算

    SGID: Optional[str] = None  # 安全组ID，可选参数

