# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AddVMNICResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    NICID: Optional[str] = None  # 网卡ID
