# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocatePMRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    PMID: str  # 裸金属ID，目标裸金属必须处于可分配状态（Status为Available/Enrolled），且必须先由管理员通过RecyclePM接口回收（CompanyID设置为超级管理员）才能重新分配给租户

    Region: str  # 地域ID，指定资源所属的物理区域

    ProjectID: Optional[str] = None  # 项目ID，用于实现资源的逻辑分组管理，可选

