# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateVMVNCSessionResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SessionID: Optional[str] = None  # VNC会话ID，用于建立VNC连接的会话标识
