# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ApplyMySQLParamTplRequest:
    """"""

    MySQLID: str  # MySQL实例ID，实例唯一标识

    Region: str  # 地域ID，实例所属地域

    TplID: str  # 模板ID，参数模板ID

    CompanyID: Optional[int] = None  # 租户ID，实例所属租户

