# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class CloneBMCTypeResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    BMCType: Optional[BMCType] = None  # BMC类型信息
