# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ClonePartitionTemplateRequest:
    """"""

    ID: str  # 源模板ID

    NewName: str  # 新模板名称

    Region: str  # 地域

