# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CloneDiskResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DiskID: Optional[str] = None  # 磁盘ID，磁盘标识
