# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOSSResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    OSSID: Optional[str] = None  # 对象存储ID，创建得到的对象存储标识
