# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateInstallProfileRequest:
    """"""

    InstallMode: str  # 安装模式，kickstart：Kickstart自动化安装；clone：克隆安装

    Name: str  # 模板名称，同租户内唯一

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，可选；用于记录模板归属，不传时由登录上下文推断

    Description: Optional[str] = None  # 模板描述，可选

    ImageID: Optional[str] = None  # 镜像ID，clone模式必填

    ImageName: Optional[str] = None  # 镜像名称，clone模式必填

    ImageOSDistribution: Optional[str] = None  # 镜像操作系统发行版，clone模式必填

    ImageOSName: Optional[str] = None  # 镜像操作系统名称，clone模式必填

    KickstartTemplateID: Optional[str] = None  # Kickstart模板ID，kickstart模式必填

    OSMediaID: Optional[str] = None  # 系统镜像ID，kickstart模式必填

    PartitionTemplateID: Optional[str] = None  # 分区模板ID，kickstart模式必填

