# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSubnetRouteRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Destination: str  # 目的地址，IPv4CIDR格式，创建时会自动格式化并校验冲突，最多50条自定义路由

    NextHop: str  # 下一跳标识，VIP/VM类型为资源ID，Custom类型为IPv4地址且必须属于当前子网

    NextHopType: str  # 下一跳类型，取值VIP/VM/Custom，VIP/VM会验证资源存在性和子网归属

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SubnetID: str  # 子网ID

    Remark: Optional[str] = None  # 备注，用于补充说明

