# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateMySQLParamTplResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    TplID: Optional[str] = None  # 模板ID，参数模板ID
