# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateRSResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    RSID: Optional[str] = None  # 真实服务器ID，用于标识服务节点
