# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateMySQLSlaveResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    MySQLID: Optional[str] = None  # MySQL从库ID，创建成功后返回的从库实例ID
