# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVPCRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Name: str  # VPC名称，用于标识虚拟私有网络，长度为1-128个字符，仅支持中英文、数字、点、下划线和中划线

    Network: str  # VPC主网段，IPv4CIDR格式的地址范围，使用10.0.0.0/8需在全局配置中放开策略

    Region: str  # 地域ID，用于标识资源所属的地理区域

    ProjectID: Optional[str] = None  # 项目ID，资源所属项目分组标识，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，可为空

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为Base64的key:value

