# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNICResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    NICID: Optional[str] = None  # 弹性网卡ID，新创建的网卡资源的唯一标识
