# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSnapshotResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SnapshotID: Optional[str] = None  # 快照ID，创建得到的快照标识
