# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOnSiteInspectionRequest:
    """"""

    Name: str  # 一键巡检报告名称，用于标识和管理巡检任务

