# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateAlertTemplateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    TemplateID: Optional[str] = None  # 告警模板ID，系统生成的唯一标识符，格式为tpl-前缀加14位随机字符
