# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteOSSRequest:
    """"""

    OSSID: str  # 对象存储ID，要删除的对象存储标识，若启用删除保护（TerminationPolicy=0）则拒绝删除，需先解绑DBS备份存储和负载均衡

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

