# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteAdminRequest:
    """"""

    MemberID: int  # 成员ID，指定要删除的管理员账号标识

