# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteVMSnapshotResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SPIDs: Optional[List[str]] = None  # 快照ID列表，被删除的快照标识列表
