# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteRedisRequest:
    """"""

    RedisID: str  # Redis实例ID，指定要删除的实例；注意：开启删除保护或版本升级中的资源不可删除

