# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteInstallTaskV2Request:
    """"""

    Region: str  # 地域

    TaskID: str  # 任务ID

