# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteOrchTaskRequest:
    """"""

    Region: str  # 地域，编排任务所属地域

    TaskID: str  # 任务ID，待删除的编排任务ID，仅允许删除资源类型为编排任务且状态为Available的任务

    CompanyID: Optional[int] = None  # 租户ID，任务所属租户

