# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeApplicationNodeRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，管理员租户（CompanyID=200000231）可查看所有租户的审批节点，普通租户仅能查看自己租户内的审批节点

    Keyword: Optional[str] = None  # 搜索关键字，用于模糊搜索审批节点相关信息，如审批名称、申请人等

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量，未指定时默认返回100条记录

    MemberID: Optional[int] = None  # 子账号ID，兼容历史接口的保留字段，接口会根据当前登录账号自动识别MemberID并按权限过滤审批节点，此入参建议填写当前子账号ID以便审计

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询

    Sort: Optional[str] = None  # 排序方式，指定返回结果的排序顺序，Descending：降序排列，Ascending：升序排列，默认Descending

    SortBy: Optional[str] = None  # 排序字段，指定按哪个字段进行排序，目前仅支持审批节点的创建时间CreateTime

    States: Optional[List[str]] = None  # 审批节点状态列表，用于筛选指定状态的审批节点，可选值：Undo、Committed、Rejected、Aborted、Approved、Handling、Succeed、Failed，已办常用传Approved、Rejected，待办常用传Handling

