# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribePMAURLRequest:
    """"""

    MySQLID: str  # MySQL实例ID，指定要获取PMAURL的实例；注意：资源必须为AVAILABLE

    Region: str  # 地域ID，实例所属地域

    CompanyID: Optional[int] = None  # 租户ID，实例所属租户

