# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeSMCResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[SMCInfo]] = None  # SMC任务信息列表
    TotalCount: Optional[int] = None  # 符合条件的SMC任务总数量
