# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeBillDetailResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[BillDetailInfo]] = None  # 详情，账单详情信息列表
    TotalCount: Optional[int] = None  # 总数量，符合条件的记录总数
