# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeFlatNetworkRouteRequest:
    """"""

    FlatNetworkID: str  # 扁平网络ID，指定要查询路由的扁平网络唯一标识

    Region: str  # 地域ID，用于标识资源所属的地理区域

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

