# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeTransactionRequest:
    """"""

    BeginTime: int  # 查询起始时间，Unix秒时间戳，必须早于EndTime

    EndTime: int  # 查询结束时间，Unix秒时间戳，必须大于BeginTime

    ProjectIDs: List[str]  # 项目组ID列表，保留字段，当前接口不会根据项目过滤

    Limit: Optional[int] = None  # 分页大小，指定每页返回的交易记录数量

    Offset: Optional[int] = None  # 分页偏移量，指定从第几条记录开始返回

    Region: Optional[str] = None  # 地域ID，指定交易所属地域；传入all或空字符串会查询所有地域（充值/提现类交易本身无地域概念）

    TransactionType: Optional[str] = None  # 交易类型，取值：CHARGE/RECHARGE/REFUND/WITHDRAW/FREE_RECHARGE/FREE_WITHDRAW，不填写则返回所有交易类型

    UserAccountID: Optional[int] = None  # 用户账号ID（即CompanyID），交易查询依据的唯一租户标识

