# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeRedisSlowlogResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[RedisSlowlog]] = None  # 慢日志信息，慢日志记录列表
    TotalCount: Optional[int] = None  # 总数，查询得到的记录总数
