# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeEIPResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[EIPInfo]] = None  # EIP信息列表，包含普通EIP、弹性网卡EIP和外网VIP的信息
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的EIP总数，用于分页计算
