# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeMulticastGroupResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[MulticastGroupInfo]] = None  # 组播组详细信息列表，融合资源中心与黄河Networking的配置数据（如VPC名称、网段、源/目的成员）
    TotalCount: Optional[int] = None  # 总记录数，满足查询条件的组播组总数量
