# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeMySQLRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，用于过滤指定租户的资源，实现多租户环境下的资源隔离，若不指定则查询当前用户有权限访问的所有租户的资源

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊搜索MySQL实例名称或ID

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    MySQLIDs: Optional[List[str]] = None  # MySQL实例ID列表，用于查询指定的MySQL实例，若同时提供Keyword，则取两者的交集

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于按项目过滤资源，支持多项目查询

    Status: Optional[List[str]] = None  # MySQL状态列表，用于按状态过滤实例，可选值包括：Running（运行中）、Stopped（已停止）、Creating（创建中）等

