# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeImageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ImageInfo]] = None  # 镜像详情列表，包含符合查询条件的镜像完整信息
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的镜像资源总量
