# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeDirectConnectResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[DirectConnectDetailInfo]] = None  # 专线接入的信息详情
    TotalCount: Optional[int] = None  # 查询得到的总数
