# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeHostPodsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[PodInfo]] = None  # Pod信息列表，返回Pod详细信息
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的Pod总数
