# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeComputeClassDRSSuggestionsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[VMMigrationReport]] = None  # drs建议列表
    TotalCount: Optional[int] = None  # 总数
