# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeRechargeResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[Recharge]] = None  # 充值信息列表，包含查询条件范围内的所有充值记录
    TotalCount: Optional[int] = None  # 充值记录总数量，用于分页计算
