# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeVMInstanceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[VMInfo]] = None  # 虚拟机列表，包含符合查询条件的虚拟机详情
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的资源总量
