# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeAlertTemplateTargetRequest:
    """"""

    Region: str  # 地域，指定查询该地域下的绑定关系

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，Limit为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    TargetID: Optional[str] = None  # 目标资源ID，精确查询指定资源ID，若指定则Limit自动设为1

    TemplateID: Optional[str] = None  # 告警模板ID，过滤指定模板绑定的资源列表

