# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeContainerImageRepositoryResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ContainerImageRepositoryInfo]] = None  # 详情，镜像仓库信息列表
    TotalCount: Optional[int] = None  # 总数，查询到的镜像仓库总数
