# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribePlatformStorageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DefaultSetType: Optional[str] = None  # 默认存储集群类型，平台通用存储使用的默认集群类型
    Status: Optional[str] = None  # 状态，平台通用存储的运行状态
    Total: Optional[int] = None  # 总量，平台通用存储总容量，单位GiB
    Used: Optional[int] = None  # 已使用，平台通用存储已使用容量，单位GiB
