# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeStorageSetResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[StorageSetInfo]] = None  # 存储集群信息列表，包含存储集群的详细信息，如容量、使用量、冗余策略、绑定的计算集群等
    TotalCount: Optional[int] = None  # 存储集群总数，返回符合查询条件的存储集群总数量
