# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeComputeClassDRSRequest:
    """"""

    Region: str  # 地域ID

    CompanyID: Optional[int] = None  # 租户ID

    SetID: Optional[str] = None  # 计算集群ID，不填返回全部集群，可指定ComputeClass缩小范围

