# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeSegmentRouteRequest:
    """"""

    Region: str  # 地域ID，指定查询外网线路路由所属的物理区域

    SegmentID: str  # 外网线路ID，指定要查询路由规则的外网线路

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，取值范围：1-100，默认值：10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询，默认值：0

