# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeLBRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Keyword: Optional[str] = None  # 关键词，用于搜索负载均衡实例

    LBIDs: Optional[List[str]] = None  # 负载均衡ID列表，用于筛选指定负载均衡实例

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于过滤指定项目的负载均衡

    Status: Optional[List[str]] = None  # 负载均衡状态，用于筛选指定状态的负载均衡实例

    SubnetID: Optional[str] = None  # 子网ID，用于筛选指定子网内的负载均衡

    VPCID: Optional[str] = None  # VPCID，用于筛选指定VPC内的负载均衡

