# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeTenantResourcesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[TenantResourceInfo]] = None  # 租户关联资源列表，返回该租户下未终止资源信息用于展示
    TotalCount: Optional[int] = None  # 查询到的资源总记录数，用于分页展示；仅统计未终止资源
