# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeProductSpecificationTemplateRequest:
    """"""

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProductType: Optional[str] = None  # 产品类型，用于过滤特定产品的规格模板

    ResourceType: Optional[str] = None  # 资源类型，用于过滤特定资源的规格模板

    SpecificationName: Optional[str] = None  # 规格名称，用于精确匹配规格模板名称

