# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeDBSBackupResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[DBSBackupInfo]] = None  # 备份列表，备份信息列表
    TotalCount: Optional[int] = None  # 总数，查询得到的记录总数
