# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeVMSetResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[SetInfo]] = None  # 计算集群信息列表，包含计算集群的详细信息，如CPU、内存、GPU资源使用情况、绑定的存储集群、CPU型号等
    TotalCount: Optional[int] = None  # 计算集群总数，返回符合查询条件的计算集群总数量
