# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribePMAURLResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    PMAURL: Optional[str] = None  # PMAURL，Web管理地址
