# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class DescribeOrderResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[Order]] = None  # 返回开始时间到结束时间租户所有的订单信息列表
    TotalCount: Optional[int] = None  # 返回开始时间到结束时间租户所有的订单数量
