# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeFlatNetworkRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，用于过滤指定租户可访问的扁平网络资源

    FlatNetworkIDs: Optional[List[str]] = None  # 扁平网络ID列表，指定要查询的扁平网络唯一标识

    IPVersion: Optional[str] = None  # IP协议版本，用于过滤IPv4或IPv6网络，预留字段

    Keyword: Optional[str] = None  # 关键词，用于按扁平网络名称或ID进行模糊搜索

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

