# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DOSLoginResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    AccessKey: Optional[str] = None  # 密钥ID，用于访问桶的认证标识
    DOSAuth: Optional[str] = None  # S3会话认证信息，用于客户端临时认证
    Endpoint: Optional[str] = None  # 访问地址，S3访问端点
    SecretKey: Optional[str] = None  # 密钥，用于访问桶的认证密钥
