# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DowngradeMySQLRequest:
    """"""

    CompanyID: int  # 租户ID，资源所属租户

    Memory: int  # 内存大小，单位MiB，最小2048 MiB（2GB），必须是1024的倍数，且必须小于当前内存

    MySQLID: str  # MySQL实例ID，指定要降级的实例；注意：资源必须为AVAILABLE且状态为Stopped

    Region: str  # 地域ID，实例所属地域

