# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ForwardClusterResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Info: Optional[ResponseInfo] = None  # 响应信息
