# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ForwardClusterRequest:
    """"""

    ClusterID: str  # 集群名称

    Region: str  # Region

    Accept: Optional[str] = None  # 响应体格式

    CompanyID: Optional[int] = None  # 租户ID

    ContentType: Optional[str] = None  # 请求体格式

    EncodedBody: Optional[bool] = None  # 转发Body数据是否被编码

    Language: Optional[str] = None  # 语言

    Method: Optional[str] = None  # 请求类型

    Path: Optional[str] = None  # 请求路径

    RequestBody: Optional[str] = None  # 转发Body数据

    Version: Optional[str] = None  # 请求版本

