# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GenerateVMWareConsoleTicketResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Link: Optional[str] = None  # VMware控制台访问链接，用于打开VMware控制台
