# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class GetLatestInstallConfigResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    CompanyID: Optional[int] = None  # 任务所属租户ID
    Config: Optional[PMInstallConfig] = None  # 裸金属安装配置详情
    CreatedAt: Optional[int] = None  # 创建时间
    Metadata: Optional[InstallMetadata] = None  # 元数据
    SchemaVersion: Optional[str] = None  # 配置模式版本
    Version: Optional[int] = None  # 配置版本
