# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetInstallTaskV2Request:
    """"""

    Region: str  # 地域ID，指定要查询装机任务所属的地域，系统会基于地域选择Kunlun集群并仅返回该地域的任务数据

    TaskID: str  # 装机任务ID，来源于CreateInstallTaskV2/ListInstallTasksV2返回值，后台依据该ID从Kunlun查询任务详情，需与地域保持一致

