# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class GetDHCPNetworkResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Pools: Optional[List[DHCPPoolInfo]] = None  # DHCP 地址池列表，每个机房一条
    Server: Optional[DHCPServerInfo] = None  # DHCPServer 配置
