# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetWithdrawableAmountRequest:
    """"""

    CompanyID: int  # 租户ID，指定要查询可提现金额的租户唯一标识，查询该租户账户余额信息

