# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetVIPPriceRequest:
    """"""

    Bandwidth: int  # 带宽，单位为Mbps，取值范围由线路规格配置确定，默认为1-20000

    ChargeType: str  # 计费类型，取值范围：Dynamic（动态）、Month（按月计费）、Year（按年计费），兼容hour/month/year，计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Count: int  # VIP数量，指定需要计算价格的外网VIP数量

    Quantity: int  # 计费数量，指定计费周期的数量；按月/年计费表示购买Quantity个月/年

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SegmentID: str  # 运营商网段ID，指定外网VIP所使用的运营商网段

