# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetCreateNICPriceRequest:
    """"""

    Bandwidth: int  # 带宽，单位Mbps，指定网卡的带宽规格

    ChargeType: str  # 计费类型，用于指定计费模式；取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year；计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Count: int  # 购买数量，指定一次性购买的网卡数量，用于批量询价

    OpertatorName: str  # 外网线路ID，指定外网网卡使用的线路，用于计算价格

    Quantity: int  # 计费数量，按月/年计费时表示购买Quantity个月/年

    Region: str  # 地域ID，用于标识资源所属的地理区域

