# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class GetDHCPServerStateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Results: Optional[List[DHCPServerStateResult]] = None  # DHCP 服务器状态. dead: 未运行, running: 运行中
