# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetInstallLogsV2Request:
    """"""

    PMID: str  # 裸金属ID，物理机唯一标识

    Region: str  # 地域

    TaskID: str  # 任务ID，安装任务唯一标识

    Lines: Optional[int] = None  # 日志行数，限制返回的日志行数，0表示不限制

    Since: Optional[str] = None  # 起始时间，RFC3339格式时间戳，例如2024-01-01T00:00:00Z，若不指定则从日志开始返回

