# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetInstallStatusByTaskIDV2Request:
    """"""

    Region: str  # 地域ID，指定装机任务所在地域，系统会在对应Kunlun集群查询最新状态

    TaskID: str  # 装机任务ID，接口根据该ID返回任务状态及最近一次执行信息

