# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class GetVIPDiffPriceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[VipPriceInfo]] = None  # VIP价格信息列表，包含不同计费类型的差价信息
