# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetRenewPriceRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceID: str  # 资源ID，要查询续费价格的资源唯一标识，必须是存在的资源ID

    ChargeType: Optional[str] = None  # 计费类型，续费的计费方式，Dynamic表示按小时计费（兼容HOUR）、Month表示按月计费（兼容MONTH）、Year表示按年计费（兼容YEAR）；若填写必须不低于资源当前计费模式，留空则沿用当前值

    CompanyID: Optional[int] = None  # 租户ID，保留字段，续费价格始终根据资源所属租户的折扣计算，管理员可留空

    Quantity: Optional[int] = None  # 续费时长，按Hour查询时系统固定为1小时且最多24小时，按Month最多11个月，按Year最多5年，不指定则默认为1

