# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ListResourceUsagesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ResourceUsageBaseInfo]] = None  # 资源用量信息列表，包含资源用量报告的基本信息
    TotalCount: Optional[int] = None  # 资源用量总数，返回符合条件的资源用量报告总数量
