# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ListOnSiteInspectionsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[InspectionInspectionInfo]] = None  # 一键巡检报告信息列表，包含巡检报告的基本信息
    TotalCount: Optional[int] = None  # 一键巡检报告总数，返回符合条件的巡检报告总数量
