# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListExpiredResourcesRequest:
    """"""

    Region: str  # 地域ID，指定要查询过期资源的地域

    ResourceType: List[str]  # 资源类型列表，指定要查询的资源类型，若不指定则查询所有类型

    CompanyID: Optional[int] = None  # 租户ID，指定要查询过期资源的租户

