# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ListKVMSessionsV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[KVMSessionInfoV2]] = None  # 会话列表
    TotalCount: Optional[int] = None  # 总数
