# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ListExpiredResourcesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ExpiredResourceInfo]] = None  # 过期资源信息列表，按资源类型分组，包含符合条件的所有过期资源的详细信息
