# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListGlobalConfigsRequest:
    """"""

    ConfigType: str  # 配置类型，用于筛选全局配置的分类，如系统配置、安全配置等

