# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ListPMV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[PMInfoV2]] = None  # 裸金属列表，返回符合条件的裸金属实例信息
    TotalCount: Optional[int] = None  # 总数，符合条件的裸金属总数量
