# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListInstallTasksV2Request:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，过滤指定租户下的装机任务，若不指定则返回所有租户的任务

    Keyword: Optional[str] = None  # 关键词搜索，支持按任务ID、裸金属ID、序列号、安装模式、状态进行关键词搜索

    Limit: Optional[int] = None  # 每页数量，指定每页返回的记录数，默认值为20，最大值为100

    MachineSN: Optional[str] = None  # 机器序列号过滤，支持精确匹配

    Offset: Optional[int] = None  # 偏移量，指定跳过的记录数，最小值为0

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，过滤指定项目下的装机任务

    Status: Optional[str] = None  # 状态过滤，可选值：waiting（待安装）、installing（安装中）、completed（已完成）、failed（失败）、canceled（已取消）

