# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class ListProductPermissionsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ProductPermission]] = None  # 产品权限信息列表，返回可授权的产品与动作集合
    TotalCount: Optional[int] = None  # 总记录数，匹配条件的产品权限数量
