# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class LockHostRequest:
    """"""

    HostID: str  # 物理机ID，用于锁定指定计算节点，仅计算节点可锁定

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    MemberID: Optional[int] = None  # 用户账号ID，标识操作用户的身份

