# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RetryInstallTaskV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Status: Optional[str] = None  # 状态
    TaskID: Optional[str] = None  # 任务ID
