# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SaveVMInstanceRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待暂存/快照的虚拟机标识

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Remark: Optional[str] = None  # 备注信息，对快照的补充说明，长度0-100个字符，禁止包含<script>标签或javascript链接

    SPName: Optional[str] = None  # 快照名称，自定义的快照标识，长度1-128，支持中英文、数字、点、下划线、中划线

    WithoutDisk: Optional[bool] = None  # 排除磁盘，标识是否暂存虚拟机而不创建快照，true：暂存虚拟机；false：创建快照

    WithoutMemory: Optional[bool] = None  # 排除内存，标识是否不包含内存数据，暂存虚拟机时需设为false

