# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnbindEIPFromLBRequest:
    """"""

    EIPID: str  # 弹性公网IP ID，用于从负载均衡实例解绑

    Region: str  # 地域ID，用于标识资源所属的地理区域

    ResourceID: str  # 负载均衡ID，用于定位需要解绑EIP的负载均衡实例

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

