# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateSegmentRouteRequest:
    """"""

    Destination: str  # 目的地址，路由的目标网段，必须为CIDR格式，用于定位要更新的路由规则，若该路由不存在则返回错误StatusRouteNotFound

    NextHop: str  # 下一跳IP地址，必须为合法的IP地址格式，且必须在外网线路网段范围内

    Region: str  # 地域ID，指定要更新的外网线路路由所属的物理区域

    SegmentID: str  # 外网线路ID，指定要更新路由规则的外网线路

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符

