# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateNICTrafficShapingRequest:
    """"""

    NICID: str  # 网卡ID，指定要修改流量整形策略的网卡资源；网卡启用SR-IOV时不可修改

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，用于多租户资源隔离与权限控制

    InAverageBandwidth: Optional[int] = None  # 入向平均带宽，单位Mbps，用于限制入向流量；-1表示取消限速，0表示保持不变，正数表示设置为指定带宽，取值范围由网卡规格配置确定，

    OutAverageBandwidth: Optional[int] = None  # 出向平均带宽，单位Mbps，用于限制出向流量；-1表示取消限速，0表示保持不变，正数表示设置为指定带宽，取值范围由网卡规格配置确定，

