# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateDigitalCertRequest:
    """"""

    CertIDs: Optional[str] = None  # 证书ID列表，多个ID用逗号分隔，总长度不超过255字符且数量不超过系统限制

