# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from openapi.services.models import *


@dataclass
class UpdateSecurityGroupRuleResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[SGRuleInfo]] = None  # 更新后的规则详情列表，包含更新后的所有规则信息
    TotalCount: Optional[int] = None  # 规则总数，更新后的规则总数量
