# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVFLogicCountRequest:
    """"""

    HostIP: str  # 节点IP地址，用于指定需要调整VF数量的物理机

    PCI: str  # 网卡PCI地址，用于指定需要调整的物理网卡

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VFLogicCount: int  # 逻辑VF数量限制，需满足已使用VF数量<=VFLogicCount<=物理VF数量限制

