# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateMemberPhoneRequest:
    """"""

    MemberID: int  # 成员ID，指定要更新手机号的账号标识

    PhoneNum: str  # 手机号，用于安全通知或验证码接收，需为合法手机号

