# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateDirectConnectRemoteSubnetCIDRsRequest:
    """"""

    CIDRs: List[str]  # 远端子网网段列表，用户数据中心需要通过专线互连的网段，必须为CIDR格式，此操作会替换专线接入的所有远端子网网段

    DirectConnectID: str  # 专线接入ID，指定要更新远端子网网段的专线接入资源ID

    Region: str  # 地域ID，指定要更新的专线接入所属的物理区域

