# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateAlertNotifyGroupRequest:
    """"""

    Name: str  # 通知组名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    NotifyGroupID: str  # 通知组ID，待更新的通知组ID

