# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateBMCTypeRequest:
    """"""

    Name: str  # BMC类型名称

    Region: str  # 地域

    Description: Optional[str] = None  # 描述

    InitialDataRules: Optional[str] = None  # 初始数据准备规则

    JNLPTemplate: Optional[str] = None  # JNLP模板

    JnlpBodyTpl: Optional[str] = None  # JNLP请求体模板

    JnlpFileType: Optional[str] = None  # JNLP文件类型

    JnlpHeaders: Optional[str] = None  # JNLP请求头

    JnlpMethod: Optional[str] = None  # JNLP请求方法

    JnlpProcessType: Optional[str] = None  # JNLP获取方式类型

    JnlpURL: Optional[str] = None  # JNLP URL

    LoginBodyTpl: Optional[str] = None  # 登录请求体模板

    LoginHeaders: Optional[str] = None  # 登录请求头

    LoginMethod: Optional[str] = None  # 登录方法

    LoginURL: Optional[str] = None  # 登录URL

    SessionExtractor: Optional[str] = None  # 会话提取器

    Steps: Optional[str] = None  # 多步流程定义

