# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateNICIPBandwidthRequest:
    """"""

    Bandwidth: int  # 带宽，单位Mbps，指定网卡的新带宽值；WAN会触发计费差价

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    NICID: str  # 弹性网卡ID，指定要修改带宽的网卡资源；仅支持WAN/Flat类型

    Region: str  # 地域ID，用于标识资源所属的地理区域

