# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateOrchTaskRequest:
    """"""

    CompanyID: int  # 租户ID，任务所属租户

    Region: str  # 地域，编排任务所属地域

    Steps: List[str]  # 步骤列表，定义更新后的执行步骤，每个步骤为JSON字符串，格式：{"order":1,"delay":0,"resourceIDs":"vm-xx,vm-yy"}；delay取值范围0-3600；order在所有步骤中必须唯一；resourceIDs为逗号分隔的资源ID列表；仅保留AVAILABLE资源，且资源类型必须与任务ResourceType一致

    TaskID: str  # 任务ID，待更新的编排任务ID

    Condition: Optional[str] = None  # 资源筛选条件，用于动态选择资源

