# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ComponentStatus:
    """"""

    Details: Optional[List[ContainerStatus]] = None  # 组件列表
    Status: Optional[str] = None  # 组件状态
