# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ConfigInfo:
    """"""

    Category: Optional[str] = None  # 所属类别标识
    CategoryName: Optional[str] = None  # 所属类别名称，支持国际化
    ConfigKey: Optional[str] = None  # 配置键，配置项的唯一标识符
    ConfigPosition: Optional[int] = None  # 配置排序位置，用于前端展示排序
    ConfigType: Optional[str] = None  # 配置类型，用于分类过滤
    ConfigValue: Optional[str] = None  # 配置值，当前配置项的取值
    Description: Optional[str] = None  # 配置描述，说明配置项的用途和含义，支持国际化
    Editable: Optional[str] = None  # 是否可编辑，true表示可编辑，false表示只读
    Hint: Optional[str] = None  # 配置提示信息，帮助用户理解如何使用该配置，支持国际化
    Unit: Optional[str] = None  # 配置值单位，如秒、MB等，支持国际化
    ValueRange: Optional[str] = None  # 配置值范围，可选值或取值范围说明，支持国际化
    ValueType: Optional[str] = None  # 配置值类型，如string、int、bool等
