# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ContainerImageRepositoryInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，镜像仓库所属租户
    CompanyName: Optional[str] = None  # 租户名称，镜像仓库所属租户名称
    ContainerImageNumbers: Optional[int] = None  # 镜像数量，仓库内镜像数量
    ContainerImageRepositoryID: Optional[str] = None  # 镜像仓库ID，镜像仓库唯一标识
    CreateTime: Optional[int] = None  # 创建时间，镜像仓库创建时间戳
    Email: Optional[str] = None  # 租户邮箱，镜像仓库所属租户邮箱
    ImagePullNumbers: Optional[int] = None  # 镜像拉取次数，仓库镜像被拉取的总次数
    Name: Optional[str] = None  # 名称，镜像仓库名称
    ProjectID: Optional[str] = None  # 项目组ID，镜像仓库所属项目组
    ProjectName: Optional[str] = None  # 项目组名称，镜像仓库所属项目组名称
    Public: Optional[bool] = None  # 是否为公有仓库，是否对所有用户开放拉取
    Region: Optional[str] = None  # 地域，镜像仓库所属地域
    RegionAlias: Optional[str] = None  # 地域别名，镜像仓库所属地域别名
    RegistryAddress: Optional[str] = None  # 镜像仓库地址，仓库外网地址
    Remark: Optional[str] = None  # 备注，镜像仓库描述信息
    Status: Optional[str] = None  # 镜像仓库状态，镜像仓库当前状态
    Tags: Optional[List[UnifiedTag]] = None  # 标签，镜像仓库标签
    UpdateTime: Optional[int] = None  # 更新时间，镜像仓库更新时间戳
