# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ContainerImageTagInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，镜像所属租户
    ContainerImage: Optional[str] = None  # 镜像名，镜像名称
    ContainerImageRepositoryID: Optional[str] = None  # 镜像仓库ID，镜像所属仓库ID
    ContainerImageTagDigest: Optional[str] = None  # TagDigest，标签摘要
    ContainerImageTagPullNumbers: Optional[int] = None  # 镜像Tag拉取次数，标签被拉取的次数
    CreateTime: Optional[int] = None  # 创建时间，标签创建时间戳
    FullName: Optional[str] = None  # 镜像完整名字，标签外网完整地址
    InternalFullName: Optional[str] = None  # 镜像完整名字，标签内网完整地址
    Size: Optional[int] = None  # 镜像Size，镜像大小
    TagName: Optional[str] = None  # Tag名称，镜像标签名称
