# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CPUPowerInfo:
    """"""

    CurrentFrequency: Optional[str] = None  # CPU核心当前运行频率，显示当前频率值
    Driver: Optional[str] = None  # CPU频率驱动类型，表示当前驱动类型
