# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVMInstanceRequestDataDisk:
    """"""

    Bus: Optional[str] = None  # 总线类型，取值 virtio，ide，scsi
    CacheMode: Optional[str] = None  # 磁盘缓存模式，当前生效的磁盘I/O缓存策略
    DiskID: Optional[str] = None  # 磁盘ID，需挂载的已有数据盘标识
    DiskSetType: Optional[str] = None  # 磁盘集群类型，指定新建数据盘所属的存储集群
    DiskSpace: Optional[int] = None  # 磁盘容量，指定新建数据盘的大小，单位：GiB
    ImageID: Optional[str] = None  # 磁盘镜像ID
    ReadBandwidth: Optional[int] = None  # QoS限速读带宽，单位MB/s，0表示不限制
    ReadIOPS: Optional[int] = None  # QoS限速读IOPS，0表示不限制
    TotalBandwidth: Optional[int] = None  # QoS限速总带宽，单位MB/s，0表示不限制
    TotalIOPS: Optional[int] = None  # QoS限速总IOPS，0表示不限制
    WriteBandwidth: Optional[int] = None  # QoS限速写带宽，单位MB/s，0表示不限制
    WriteIOPS: Optional[int] = None  # QoS限速写IOPS，0表示不限制
