# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DataCheckTaskOverview:
    """"""

    EndTime: Optional[int] = None  # 结束时间，秒级Unix时间戳
    Result: Optional[str] = None  # 校验结果，取值范围：Consistent、Inconsistent
    SampleInterval: Optional[int] = None  # 采样频率，每多少条记录采样一次
    StartTime: Optional[int] = None  # 开始时间，秒级Unix时间戳
    Status: Optional[str] = None  # 任务状态，数据校验任务状态
    TaskID: Optional[str] = None  # 校验任务ID，数据校验任务唯一标识
