# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DBSBackupInfo:
    """"""

    BackupID: Optional[str] = None  # 备份ID，备份唯一标识
    BackupTables: Optional[List[str]] = None  # 备份库表，备份库表列表
    BackupType: Optional[str] = None  # 备份类型，备份类型字符串
    ClusterType: Optional[str] = None  # 集群类型，备份源实例集群类型
    CompanyEmail: Optional[str] = None  # 租户邮箱，租户联系邮箱
    CompanyID: Optional[int] = None  # 租户ID，备份所属租户
    CompanyName: Optional[str] = None  # 租户名称，租户显示名称
    CreateTime: Optional[int] = None  # 创建时间，备份创建时间戳
    DBSStorageStatus: Optional[str] = None  # 存储池状态，备份存储池状态
    ExpireTime: Optional[int] = None  # 过期时间，备份过期时间戳
    InstanceVersion: Optional[str] = None  # 备份实例版本，备份源实例版本
    Path: Optional[str] = None  # 备份存放路径，备份文件路径
    PlanID: Optional[str] = None  # 计划ID，备份计划ID
    PlanName: Optional[str] = None  # 计划名称，备份计划名称
    Reason: Optional[str] = None  # 失败原因，备份失败原因
    RetentionTime: Optional[int] = None  # 保留时间，备份保留时长
    ShardCount: Optional[int] = None  # 分片数，备份源实例分片数
    Size: Optional[int] = None  # 备份大小，备份文件大小
    SrcDiskSetType: Optional[str] = None  # 源存储集群，备份源存储集群类型
    SrcDiskSpace: Optional[int] = None  # 源磁盘空间，备份源磁盘空间
    SrcID: Optional[str] = None  # 备份源ID，备份源资源ID
    SrcName: Optional[str] = None  # 备份源名称，备份源资源名称
    SrcRegion: Optional[str] = None  # 备份源地域，备份源资源所属地域
    SrcType: Optional[str] = None  # 备份源类型，备份源资源类型
    Status: Optional[str] = None  # 备份状态，备份状态字符串
    StorageID: Optional[str] = None  # 存储池ID，备份存储池ID
    StorageName: Optional[str] = None  # 存储池名称，备份存储池名称
    UpdateTime: Optional[int] = None  # 更新时间，备份更新时间戳
