# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DBSStorageInfo:
    """"""

    AccessKey: Optional[str] = None  # 外部服务访问密钥，当StorageType为S3时使用
    BucketName: Optional[str] = None  # 外部服务存储桶名称，当StorageType为S3时使用
    CompanyID: Optional[int] = None  # 租户ID，存储池所属租户
    CreateTime: Optional[int] = None  # 创建时间，存储池创建时间戳
    Email: Optional[str] = None  # 租户邮箱，租户联系邮箱
    Endpoint: Optional[str] = None  # 外部服务地址，当StorageType为S3时使用
    Name: Optional[str] = None  # 名称，备份存储池名称
    OSSID: Optional[str] = None  # 对象存储ID，绑定的OSS资源ID
    OSSName: Optional[str] = None  # 对象存储名称，绑定的OSS名称
    Region: Optional[str] = None  # 地域ID，存储池所属地域
    RelatedPlanIDs: Optional[List[str]] = None  # 备份计划ID列表，关联的备份计划ID
    Remark: Optional[str] = None  # 备注，备份存储池描述信息
    SecretKey: Optional[str] = None  # 外部服务私钥，当StorageType为S3时使用
    Space: Optional[float] = None  # 总空间，存储池总容量
    SpaceUsed: Optional[float] = None  # 已用空间，存储池已使用容量
    Status: Optional[str] = None  # 状态，备份存储池状态
    StorageID: Optional[str] = None  # 备份存储池ID，存储池唯一标识
    StorageType: Optional[str] = None  # 存储类型，取值OSS或S3
    UpdateTime: Optional[int] = None  # 更新时间，存储池更新时间戳
