# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DHCPServerInfo:
    """"""

    EndIP: Optional[str] = None  # 探测 IP，绑定到 lo，如 192.170.60.66
    Mode: Optional[str] = None  # 配置模式：single=单网段，multi=多网段（DHCP Relay）
    Network: Optional[str] = None  # DHCP Server 所在网段 CIDR，如 192.170.60.64/28
    PoolEndIP: Optional[str] = None  # 兼容模式下的 dhcp-range 结束 IP（dhcp_pools 为空时使用）
    PoolStartIP: Optional[str] = None  # 兼容模式下的 dhcp-range 起始 IP（dhcp_pools 为空时使用）
    StartIP: Optional[str] = None  # DHCP Server IP，绑定到 bond0，如 192.170.60.65
    VLANID: Optional[int] = None  # VLAN ID
