# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DiskMapping:
    """"""

    Avail: Optional[float] = None  # 磁盘可用空间大小，单位GB，表示源端磁盘的剩余容量，用于迁移规划
    Device: Optional[str] = None  # 源端设备名称或分区标识，如/dev/sda1、/dev/vda1等，用于唯一标识待迁移的磁盘分区
    FsType: Optional[str] = None  # 文件系统类型，如ext4、xfs、ntfs等，用于指导目标云硬盘的初始化和配置
    IsRoot: Optional[bool] = None  # 是否为根分区，用于标识该分区是否为操作系统根分区（挂载点为/）
    MappingDiskID: Optional[str] = None  # 目标云硬盘ID，指定与源端磁盘映射的目标云硬盘，用于接收迁移数据，配置迁移任务时必填
    MountPoint: Optional[str] = None  # 源端挂载点路径，表示该分区在源端操作系统中的挂载位置，如/、/home、/data等；未挂载的分区可留空
    Size: Optional[float] = None  # 磁盘总大小，单位GB，表示源端磁盘的总容量，目标云硬盘需满足此容量要求
