# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DRSRuleVMInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID
    Email: Optional[str] = None  # 租户邮箱
    Name: Optional[str] = None  # 虚拟机名称
    Remark: Optional[str] = None  # 虚拟机备注
    Usage: Optional[str] = None  # 虚拟机用途
    VMID: Optional[str] = None  # 虚拟机ID
