# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ErrorLogInfo:
    """"""

    CreateTime: Optional[int] = None  # 记录时间，错误日志的记录时间戳
    LogContent: Optional[str] = None  # 日志内容，错误日志的内容
