# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FileInfo:
    """"""

    FilePath: Optional[str] = None  # 文件路径，文件或目录的绝对路径
    IsDir: Optional[bool] = None  # 是否为目录，用于区分文件与目录
    ModTime: Optional[int] = None  # 文件修改时间，Unix 时间戳（秒级）
    Name: Optional[str] = None  # 文件名，文件或目录的名称
    Size: Optional[int] = None  # 文件大小，单位：字节
