# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InspectionResourceUsageInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID
    Infos: Optional[List[InspectionResourceUsageDetail]] = None  # 资源用量详情列表，包含每个资源的详细用量信息
    ProjectID: Optional[str] = None  # 项目组ID
    Region: Optional[str] = None  # 地域ID
    ResourceType: Optional[str] = None  # 资源类型，指定资源的分类
    TotalCount: Optional[int] = None  # 总数，该资源类型的用量记录数
