# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InstallLogEntryV2:
    """"""

    Level: Optional[str] = None  # 级别
    Message: Optional[str] = None  # 消息
    Time: Optional[str] = None  # 时间
