# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ItemReport:
    """"""

    ItemDesc: Optional[str] = None  # 检查项描述，详细说明检查的内容和目的
    ItemName: Optional[str] = None  # 检查项名称，检查项的显示名称
    ItemNo: Optional[int] = None  # 检查项序号，用于排序和标识
    Results: Optional[List[Result]] = None  # 检查结果列表，包含该检查项的所有检查结果
    Suggest: Optional[str] = None  # 建议，针对检查结果的优化建议
