# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class LbCertificateInfo:
    """"""

    CertificateContent: Optional[str] = None  # 证书内容，证书的PEM格式内容
    CertificateID: Optional[str] = None  # 证书ID，用于标识证书
    CertificateType: Optional[str] = None  # 证书类型，证书的类型，取值范围：ServerCrt（服务器证书）、CACrt（CA证书）
    CommonName: Optional[str] = None  # 主域名，证书的主域名（CN字段）
    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
    CreateTime: Optional[int] = None  # 创建时间，证书在平台上的秒级Unix时间戳
    Email: Optional[str] = None  # 邮箱，资源所有者的邮箱地址，用于展示联系人信息
    ExpireTime: Optional[int] = None  # 过期时间，证书内容的秒级Unix时间戳
    Fingerprint: Optional[str] = None  # 证书指纹，证书的指纹（通常为SHA-1哈希值）
    Name: Optional[str] = None  # 名称，证书的名称
    Privatekey: Optional[str] = None  # 私钥内容，证书的私钥内容
    ProjectID: Optional[str] = None  # 项目ID，用于标识证书所属项目分组
    ProjectName: Optional[str] = None  # 项目名称，用于展示证书所属项目分组名称
    Region: Optional[str] = None  # 地域ID，用于标识资源所属的地理区域
    Remark: Optional[str] = None  # 备注，证书的描述信息
    State: Optional[str] = None  # 状态，证书的生命周期状态
    SubjectAlternativeNames: Optional[List[str]] = None  # 备选域名列表，证书的SANs（Subject Alternative Names）
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表，用于展示证书关联标签
    VSInfos: Optional[List[LbBindVSInfo]] = None  # 虚拟服务器绑定列表，证书关联的虚拟服务器列表
