# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MetricFilterCondition:
    """"""

    Key: Optional[str] = None  # 过滤条件的键名，指定要过滤的字段或标签名称
    Operation: Optional[str] = None  # 过滤操作类型，定义过滤时使用的比较操作，如等于、包含、正则匹配等
    Values: Optional[List[str]] = None  # 过滤条件的值列表，指定过滤时要匹配的具体值
