# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class NIC:
    """"""

    IPs: Optional[List[IP]] = None  # IP详情，网卡IP信息
    MAC: Optional[str] = None  # MAC地址，网卡MAC地址
    Name: Optional[str] = None  # 网卡名称，网卡设备名
