# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Order:
    """"""

    AmountFree: Optional[float] = None  # 内部账户金额，从内部账户（赠金）扣除的金额，单位为元
    AmountReal: Optional[float] = None  # 外部账户金额，从外部账户扣除的金额，单位为元
    AmountTotal: Optional[float] = None  # 总金额，订单的总金额，等于外部账户金额加内部账户金额，单位为元
    ChargeType: Optional[str] = None  # 计费类型，资源的计费方式，Hour表示按小时计费、Month表示按月计费、Year表示按年计费
    CompanyID: Optional[int] = None  # 租户ID，订单所属的租户唯一标识
    CompanyName: Optional[str] = None  # 租户名称，订单所属的租户显示名称
    CreateTime: Optional[int] = None  # 创建时间，订单的创建时间戳，单位为秒
    Email: Optional[str] = None  # 租户邮箱，订单所属的租户邮箱地址
    OrderDetails: Optional[List[OrderDetail]] = None  # 订单详情列表，包含订单中各个资源的详细计费信息
    OrderNO: Optional[str] = None  # 订单编号，订单的唯一标识
    OrderType: Optional[str] = None  # 订单类型，订单的业务类型，BUY表示购买、RENEW表示续费、REFUND表示退款
    Region: Optional[str] = None  # 地域，订单资源所属的地域标识
    RegionAlias: Optional[str] = None  # 地域别名，订单资源所属的地域显示名称，从DescribeRegion接口获取
    ResourceID: Optional[str] = None  # 资源ID，订单关联的资源唯一标识，例如磁盘订单对应磁盘ID
    ResourceName: Optional[str] = None  # 资源名称，订单关联资源的显示名称，若资源不存在则显示资源ID
