# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PendingChange:
    """"""

    Field: Optional[str] = None  # 字段名称，待生效的配置字段名
    Restart: Optional[bool] = None  # 需重启，标识更改是否需要重启电源才能生效
