# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PhysicalDisk:
    """"""

    Arch: Optional[str] = None  # 存储介质类型，取值范围：1-HDD、2-SSD
    DiskUsage: Optional[str] = None  # 磁盘用途，取值范围：1-boot、2-cache、3-data
    Drive: Optional[str] = None  # 设备名，操作系统识别的设备名
    HealthStatus: Optional[str] = None  # 磁盘健康状态，取值范围：1-healthy、2-unhealthy
    LVs: Optional[List[LogicalVolume]] = None  # 逻辑卷，磁盘逻辑卷信息
    Location: Optional[List[Location]] = None  # 磁盘厂商与位置信息，物理磁盘厂商及位置信息
    MountStatus: Optional[str] = None  # 磁盘挂载状态，取值范围：1-mounted、2-mounting、3-mount_failed、4-unmounted、5-unmounting、6-unmount_failed
    Partitions: Optional[List[PhysicalDiskPartition]] = None  # 磁盘分区，磁盘分区信息
    SerialNumber: Optional[str] = None  # 设备序列号，磁盘设备序列号
    Size: Optional[int] = None  # 磁盘大小，单位GiB
    WWID: Optional[str] = None  # WWID（全球唯一磁盘标识符），磁盘全局唯一标识
