# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Recharge:
    """"""

    AccountID: Optional[int] = None  # 账号ID，充值操作的账号ID，与CompanyID相同
    AccountName: Optional[str] = None  # 账号名称，充值操作的账号名称，与AccountID对应
    CompanyID: Optional[int] = None  # 租户ID，充值所属的租户ID
    CompanyName: Optional[str] = None  # 租户名称，充值所属的租户名称，与CompanyID对应
    CreateTime: Optional[int] = None  # 创建时间，充值记录的创建时间戳
    Email: Optional[str] = None  # 租户邮箱，充值所属的租户邮箱，与CompanyID对应
    FromType: Optional[str] = None  # 来源类型，充值的来源渠道，ALIPAY表示支付宝、WECHAT_PAY表示微信支付、INNER表示内部充值、OFFLINE表示线下充值
    RechargeType: Optional[str] = None  # 充值类型，充值的类型分类，FREE表示赠金，REAL表示现金
    SerialNo: Optional[str] = None  # 序列号，充值的序列号或凭证号，用于防止重复充值
    TradeAmount: Optional[float] = None  # 充值金额，本次充值的金额，单位为元，精确到分
    TransactonNO: Optional[str] = None  # 交易号，充值交易的唯一标识
    UpdateTime: Optional[int] = None  # 更新时间，充值记录的最后更新时间戳
