# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RegionConfigBaseInfo:
    """"""

    ConfigKey: Optional[str] = None  # 配置键，地域配置项的唯一标识符
    ConfigValue: Optional[str] = None  # 配置值，当前地域配置项的取值
