# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResourceInfos:
    """"""

    CompanyID: Optional[str] = None  # 租户ID，资源所属的租户，系统资源为0
    CreateTime: Optional[int] = None  # 资源创建时间，Unix时间戳
    Name: Optional[str] = None  # 资源名称，若资源不存在则可能为空或系统预定义名称
    Region: Optional[str] = None  # 地域ID
    ResourceID: Optional[str] = None  # 资源ID，资源的唯一标识符
    ResourceType: Optional[str] = None  # 资源类型，如VM、DISK、IP等
