# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResourceTemplateInfo:
    """"""

    BindAsGroupIDs: Optional[List[str]] = None  # 绑定的弹性伸缩组ID列表，模板绑定弹性伸缩组后不允许修改VPCID
    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
    CompanyName: Optional[str] = None  # 租户名称
    Content: Optional[str] = None  # 模板内容，JSON字符串格式，包含创建资源所需的完整配置参数
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    DeleteTime: Optional[int] = None  # 删除时间，秒级Unix时间戳，未删除时为0
    Email: Optional[str] = None  # 租户邮箱地址
    Name: Optional[str] = None  # 模板名称，用于展示模板的标识名称
    ProjectID: Optional[str] = None  # 项目ID，模板所属项目分组标识
    ProjectName: Optional[str] = None  # 项目名称
    Reason: Optional[str] = None  # 失败原因，当模板状态异常时记录失败原因
    Region: Optional[str] = None  # 地域ID，用于标识资源所属的地理区域
    RegionAlias: Optional[str] = None  # 地域别名，地域的人性化显示名称
    Remark: Optional[str] = None  # 备注，用于补充说明模板用途
    Status: Optional[str] = None  # 模板状态，取值Available/Deleted/Deleting/Failed等资源状态
    Tags: Optional[List[UnifiedTag]] = None  # 资源标签列表，用于资源分类和管理
    TemplateID: Optional[str] = None  # 模板ID
    TemplateType: Optional[str] = None  # 模板类型，取值：VM（虚拟机）
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
