# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SegmentInfo:
    """"""

    AvailableCount: Optional[int] = None  # 可用IP数量，剩余可分配的IP地址总数
    BoundedEIPCount: Optional[int] = None  # 已绑定的EIP数量，该外网线路中已绑定到资源的EIP总数，包括绑定到虚拟机、弹性网卡等资源的EIP
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳（秒级）
    DHCPServerIP: Optional[str] = None  # DHCP服务器IP地址，若启用DHCP则显示DHCP服务器的IP地址
    Description: Optional[str] = None  # 外网线路描述信息，即备注内容
    Device: Optional[str] = None  # 网卡名称，外网线路绑定的物理网卡标识
    FailedEIPCount: Optional[int] = None  # 失败状态的EIP数量，该外网线路中处于Failed状态的EIP总数
    Gateway: Optional[str] = None  # 网关地址，外网线路的默认网关IP
    IPRanges: Optional[str] = None  # 可用IP范围，网段内可分配的IP地址范围
    IPVersion: Optional[str] = None  # IP版本，外网线路使用的IP协议版本，可选值：IPv4、IPv6
    Name: Optional[str] = None  # 外网线路名称
    Permission: Optional[str] = None  # 访问权限，该外网线路可以被哪些租户访问，值为all表示所有租户可用，否则为租户ID列表（逗号分隔）
    PermissionMode: Optional[str] = None  # 权限模式，控制租户访问权限的模式，可选值：all（所有租户可用）、whitelist（白名单，仅指定租户可用）、blacklist（黑名单，仅指定租户不可用）
    Platform: Optional[bool] = None  # 是否为平台保留线路，true表示该线路为平台内部使用（如vm-taishan-app），不对外提供服务
    RecycledEIPCount: Optional[int] = None  # 回收站中的EIP数量，该外网线路中处于Deleted或Terminating状态的EIP总数
    Region: Optional[str] = None  # 地域ID，外网线路所属的物理区域标识
    RegionAlias: Optional[str] = None  # 地域别名，地域的显示名称
    Routing: Optional[str] = None  # 路由信息，外网线路的路由配置
    Segment: Optional[str] = None  # 外网网段，外网线路的网络地址范围，CIDR格式
    SegmentID: Optional[str] = None  # 外网线路ID，资源的唯一标识，系统自动生成的14位随机字符串
    Status: Optional[str] = None  # 当前外网线路状态，如Available（可用）、Deleting（删除中）等
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表，用于资源标记和分类管理
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳（秒级）
    UsedCount: Optional[int] = None  # 已用IP数量，已分配或占用的IP地址总数
    Vlan: Optional[str] = None  # VLAN ID，虚拟局域网标识，可选，取值范围1-4094，不传或传0表示不设置VLAN
