# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Service:
    """"""

    Authorized: Optional[str] = None  # 是否授权，标识子服务是否对租户开放
    Name: Optional[str] = None  # 子服务名称，子服务显示名称
    ServiceProductKey: Optional[str] = None  # 子服务产品ID，子服务唯一标识
    ServiceProductType: Optional[str] = None  # 子服务产品类型，子服务的类型标识
