# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SlowLogInfo:
    """"""

    DB: Optional[str] = None  # 执行查询操作的数据库名称，标识该慢日志记录属于哪个数据库
    InsertID: Optional[int] = None  # InsertID，INSERT查询语句中指定的INSERT_ID值
    LastInsertID: Optional[int] = None  # 最后一次INSERT操作生成的AUTO_INCREMENT值，用于追踪新插入的记录ID
    LockTime: Optional[float] = None  # SQL查询获取锁的时间，单位为秒，表示在锁等待上花费的时间
    QueryTime: Optional[float] = None  # SQL查询执行耗时，单位为秒，精确到小数点后多位，用于识别性能瓶颈
    RowsExamined: Optional[int] = None  # MySQL服务器执行查询过程中扫描的总行数，包括被WHERE条件过滤掉的行，用于判断查询效率
    RowsSent: Optional[int] = None  # 查询返回给客户端的行数，即查询结果集的行数
    SQLText: Optional[str] = None  # 完整的SQL查询语句文本，包含所有执行的SQL命令
    ServerID: Optional[int] = None  # MySQL服务器的唯一标识符，在主从复制环境中用于区分不同的MySQL实例
    StartTime: Optional[int] = None  # 记录时间，慢查询日志的记录时间戳
    ThreadID: Optional[int] = None  # 执行查询的MySQL线程ID，用于在MySQL日志中跟踪和关联相关操作
    UserHost: Optional[str] = None  # 客户端名称及地址，标识执行查询的客户端来源
