# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StorageSetBlockBackupStatus:
    """"""

    AbnormalVolumeIDs: Optional[List[str]] = None  # 异常备份卷ID列表，处于异常状态的备份卷ID列表
    BackupVolumeTotalCount: Optional[int] = None  # 备份卷总数，该存储集群中卷备份的总数量
    Health: Optional[str] = None  # 健康状态，卷备份的整体健康状态，如healthy、degraded、error等
