# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StorageSetInfo:
    """"""

    Authorized: Optional[str] = None  # 授权标识，表示该存储集群的授权状态
    BlockBackupPeerSetID: Optional[str] = None  # 卷备份对端集群ID，用于卷备份的对端存储集群标识
    BlockBackupStatus: Optional[StorageSetBlockBackupStatus] = None  # 集群卷备份状态，包含备份健康状态、备份卷总数、异常卷列表等信息
    BoundVMSetList: Optional[List[VmSetItem]] = None  # 逻辑绑定计算集群列表，当前存储集群绑定的计算集群列表，软限制，可通过UpdateVMSetBoundStorageSet修改
    Cache: Optional[str] = None  # 缓存状态，表示是否开启了OpenCAS缓存加速，值为true或false
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳，单位为秒
    DOSMultisiteRole: Optional[str] = None  # DOS多站点角色，分布式对象存储多站点角色，值为master、slave或空字符串
    Redundancy: Optional[str] = None  # 存储集群冗余策略，数据冗余保护策略，如三副本、纠删码等
    Region: Optional[str] = None  # 地域ID，存储集群所属的物理区域
    SetAlias: Optional[str] = None  # 集群别名，存储集群的自定义名称
    SetArch: Optional[str] = None  # 集群架构，存储集群的硬件架构类型
    SetBlockBackupRole: Optional[str] = None  # 卷备份角色，当前存储集群在卷备份中的角色，值为master、slave或空字符串
    SetID: Optional[str] = None  # 集群ID，存储集群的唯一标识，由底层Huanghe系统生成和管理
    SetProvider: Optional[str] = None  # 集群制备器，存储集群的底层存储提供商类型
    SetType: Optional[str] = None  # 集群类型，存储集群的类型标识
    StorageCap: Optional[int] = None  # 存储集群总容量，集群的总存储容量，单位为GB
    StorageMaxOverCommitRatio: Optional[float] = None  # 存储集群最大超分比例
    StoragePhysicAvailable: Optional[int] = None  # 存储集群物理可用量，物理层面可用的存储空间，单位为GB
    StoragePhysicOther: Optional[int] = None  # 存储集群其他用量，非PVC占用的其他存储空间，如元数据等，单位为GB
    StoragePhysicUsed: Optional[int] = None  # 存储集群物理使用量，实际占用的物理存储空间，单位为GB
    StorageUsed: Optional[int] = None  # 存储集群PVC总容量，已分配给持久化卷声明的总容量，单位为GB
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳，单位为秒
    VmSetList: Optional[List[VmSetItem]] = None  # 物理绑定计算集群列表，可以使用该存储集群的计算集群列表，硬限制，由底层物理网络拓扑决定
