# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TagInfo:
    """"""

    CompanyEmail: Optional[str] = None  # 租户邮箱地址，用于联系和通知的邮箱
    CompanyID: Optional[int] = None  # 租户ID，标识标签所属的租户账户
    CompanyName: Optional[str] = None  # 租户名称，标签所属租户的显示名称
    Key: Optional[str] = None  # 标签键名，用于标识标签的名称
    ResourceCount: Optional[int] = None  # 资源数量，使用该标签的资源总数
    Value: Optional[str] = None  # 标签值，与键名配对使用的标签值
