# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TaskTypeInfo:
    """"""

    ResourceTypes: Optional[List[str]] = None  # 支持的资源类型列表，任务可作用的资源类型
    TaskName: Optional[str] = None  # 任务名称，编排任务名称
    TaskType: Optional[str] = None  # 任务类型，编排任务类型标识
