# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TenantTenantInfoRes:
    """"""

    Amount: Optional[float] = None  # 租户余额，计费账户可用资金额度，用于余额展示与审核
    AmountCredit: Optional[float] = None  # 信用额度，授予的欠费限制额度，用于信用额度展示
    AmountFree: Optional[float] = None  # 免费额度，系统发放的免额余额，用于抵扣展示
    Audit: Optional[int] = None  # 审批开关，标识资源申请是否需审批；1表示开启审批，0表示关闭
    AutoAudit: Optional[int] = None  # 自动审批开关，标识资源申请是否自动通过；1表示开启自动审批，0表示关闭
    CompanyID: Optional[int] = None  # 租户ID，查询结果返回的租户唯一标识，用于资源归属与权限隔离
    CreateTime: Optional[int] = None  # 创建时间，租户创建的Unix时间戳，用于时间排序与审计展示
    Email: Optional[str] = None  # 租户邮箱，查询结果返回的主账号邮箱，用于登录与通知展示
    ManagerEmail: Optional[str] = None  # 管理员邮箱，后台管理联系邮箱字段，当前与Email一致
    MemberID: Optional[int] = None  # 成员ID，查询结果返回的租户主账号成员ID，用于账号级权限与状态展示
    MemberStatus: Optional[str] = None  # 成员状态，主账号生命周期状态；AVAILABLE可用、FREEZE冻结、LOCKED锁定
    Name: Optional[str] = None  # 租户名称，组织显示名称，用于租户识别与展示
    Phone: Optional[str] = None  # 手机号，查询结果返回的主账号安全手机号，用于短信验证码及敏感操作二次验证展示
    PrivateKey: Optional[str] = None  # API私钥，API调用请求签名RSA私钥，用于请求签名
    PublicKey: Optional[str] = None  # API公钥，API调用身份验证RSA公钥，用于签名验证
    Remark: Optional[str] = None  # 备注，说明或备注信息
    Status: Optional[str] = None  # 租户状态，租户生命周期状态；AVAILABLE可用、FREEZE冻结
    UpdateTime: Optional[int] = None  # 更新时间，租户信息最近变更的Unix时间戳，用于展示最近变更时间
    UserID: Optional[int] = None  # 用户ID，查询结果返回的租户主账号ID；当前与CompanyID一致
