# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TimerResources:
    """"""

    ResourceID: Optional[str] = None  # 资源ID，定时器绑定的目标资源唯一标识符
    ResourceName: Optional[str] = None  # 资源名称，资源显示名称
