# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TrafficMirrorSource:
    """"""

    AssociatedResourceID: Optional[str] = None  # 关联的资源ID，源设备所绑定的虚拟机ID
    AssociatedResourceName: Optional[str] = None  # 关联的资源名称，源设备所绑定的虚拟机名称
    AssociatedResourceStatus: Optional[str] = None  # 关联的资源状态，虚拟机的当前状态
    Direction: Optional[str] = None  # 流量方向，可能值：inbound入方向、outbound出方向、all双向
    SrcDevice: Optional[str] = None  # 源设备ID，网卡资源的唯一标识符
    SrcDeviceName: Optional[str] = None  # 源设备名称，网卡资源的显示名称
    SrcDeviceStatus: Optional[str] = None  # 源设备状态，网卡的当前状态，可能值：Available可用、Terminated已终止，若关联虚拟机被删除或销毁，该字段会置为Terminated以提示后续需要更新源设备
