# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class USBInfo:
    """"""

    AttachedType: Optional[str] = None  # 加载类型，取值Passthrough、redir
    AttachedVMID: Optional[str] = None  # 已加载的虚拟机ID，当状态为Attached时有效
    Class: Optional[str] = None  # 产品类型，USB设备类型
    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
    CompanyName: Optional[str] = None  # 租户名称，资源归属租户的可读名称
    ComputeSetID: Optional[str] = None  # 计算集群ID，USB设备所在计算集群标识
    CreateTime: Optional[int] = None  # 创建时间，USB设备纳管的秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱，归属租户的联系电子邮箱
    HostIP: Optional[str] = None  # 宿主机IP，USB设备所在宿主机IP
    Name: Optional[str] = None  # 设备名称，USB设备在平台中的显示名称
    Product: Optional[str] = None  # 产品名称，USB设备产品名称
    ProjectID: Optional[str] = None  # 项目ID，资源所属的项目分组标识
    ProjectName: Optional[str] = None  # 项目名称，资源归属项目的显示名称
    Reason: Optional[str] = None  # 加载失败原因，USB设备加载失败时的错误说明
    Region: Optional[str] = None  # 地域ID，USB设备所属的地理标识
    RegionAlias: Optional[str] = None  # 地域别名，地域的人性化显示名称
    Remark: Optional[str] = None  # 备注信息，USB设备的补充说明
    Serial: Optional[str] = None  # 序列号，USB设备的硬件序列号
    Status: Optional[str] = None  # 加载状态，取值Attached、Detached、Lost
    USBDeviceID: Optional[str] = None  # USB设备ID，USB设备资源标识
    Vendor: Optional[str] = None  # 厂商名称，USB设备厂商名称
    Version: Optional[str] = None  # USB协议版本
