# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VmDiskInfo:
    """"""

    Bus: Optional[str] = None  # 总线类型
    CacheMode: Optional[str] = None  # 缓存类型，取值 directsync、none、writeback
    DiskID: Optional[str] = None  # 磁盘ID，虚拟机绑定的磁盘唯一标识
    Drive: Optional[str] = None  # 设备名，磁盘在操作系统内的设备路径
    Encrypted: Optional[bool] = None  # 加密标识，标识磁盘数据是否经过加密
    IsElastic: Optional[str] = None  # 弹性标识，标识是否为弹性可挂载设备
    IsSharedblock: Optional[bool] = None  # 共享块存储，标识是否为外置存储设备
    Name: Optional[str] = None  # 磁盘名称，磁盘的可视化显示名称
    ReadBandwidth: Optional[int] = None  # QoS限速读带宽，单位MB/s
    ReadIOPS: Optional[int] = None  # QoS限速读IOPS
    SetID: Optional[str] = None  # 存储集群ID，磁盘所属存储集群的唯一标识
    ShareAble: Optional[bool] = None  # 共享标识，标识磁盘是否支持多点挂载
    Size: Optional[int] = None  # 磁盘容量，单位：GiB
    SnapshotCount: Optional[int] = None  # 快照数量，基于该磁盘创建的快照个数
    StorageSetArch: Optional[str] = None  # 存储架构，存储集群的介质架构，取值：HDD、SSD
    StorageSetProvider: Optional[str] = None  # 存储制备器，存储后端驱动类型
    StorageSetType: Optional[str] = None  # 存储集群类型，磁盘所属的存储集群标识
    TotalBandwidth: Optional[int] = None  # QoS限速总带宽，单位MB/s
    TotalIOPS: Optional[int] = None  # QoS限速总IOPS
    Type: Optional[str] = None  # 磁盘类型，标识引导盘或数据盘，取值：boot（启动盘）、data（数据盘）
    WriteBandwidth: Optional[int] = None  # QoS限速写带宽，单位MB/s
    WriteIOPS: Optional[int] = None  # QoS限速写IOPS
