# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VmNICInfo:
    """"""

    FlatNetworkID: Optional[str] = None  # 扁平网络ID
    FlatNetworkName: Optional[str] = None  # 扁平网络名称
    IP: Optional[str] = None  # ip地址
    InAverageBandwidth: Optional[int] = None  # 入向平均带宽，单位Mbps
    LinkState: Optional[str] = None  # 启用状态
    MAC: Optional[str] = None  # mac地址
    Model: Optional[str] = None  # 网卡型号
    NICID: Optional[str] = None  # 网卡ID，网卡资源的唯一标识
    OutAverageBandwidth: Optional[int] = None  # 出向平均带宽，单位Mbps
    Queues: Optional[int] = None  # 网卡队列数
    SGID: Optional[str] = None  # 安全组ID
    SGName: Optional[str] = None  # 安全组名称
