# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VPCInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，VPC所属的租户唯一标识，用于实现多租户环境下的资源隔离
    Email: Optional[str] = None  # 租户邮箱，租户注册时提供的用于接收通知和联系的邮箱地址
    Name: Optional[str] = None  # VPC名称
    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符
    VPCID: Optional[str] = None  # VPC ID，VPC资源的唯一标识
