# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class WorkflowNodeMemberInfo:
    """"""

    Email: Optional[str] = None  # 用户邮箱地址，可以是审批人或观察人的邮箱
    MemberID: Optional[int] = None  # 用户账号ID，可以是审批人或观察人的账号标识
