# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AbortMigratePaaSInstanceRequest:
    """"""

    CompanyID: int  # 租户ID，保留字段

    InstanceID: str  # 实例ID，只有迁移已报错( MigrationError=true )时才允许取消；其他状态会返回状态错误

    Region: str  # 地域ID，指定资源所属地域

    ResourceID: str  # 资源ID，仅当资源处于计算迁移中时才能取消迁移

