# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AddRegionRequest:
    """"""

    RegionID: str  # 地域ID，请求传入待纳管物理地域唯一标识码，用于区分不同数据中心区域；纳管地域场景使用

    RegionIP: str  # 地域IP地址，请求传入地域管理平面入口地址，用于下载地域配置文件并上传告警回调配置

    RegionToken: str  # 认证令牌，请求传入用于地域纳管身份认证，确保只有授权地域可加入系统；纳管地域场景使用

    CMPIP: Optional[str] = None  # 中心管理平台IP，用于地域向中心注册和心跳上报；未传入时优先使用系统配置CMPIP，仍为空时通过UDP连接RegionIP获取本地IP

