# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AddVPCNetworkRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Network: str  # IPv6网段，CIDR格式的IPv6地址范围，用于扩展VPC的IPv6地址空间

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VPCID: str  # VPCID，虚拟私有网络的唯一标识符

