# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateExternalStorageSetDiskRequest:
    """"""

    DiskID: str  # 硬盘ID，待分配的外置存储盘资源ID

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户的权限上下文

    ProjectID: Optional[str] = None  # 项目ID，资源分配到目标租户后的项目归属

    TargetCompanyID: Optional[int] = None  # 目标租户ID，指定资源分配后的归属租户

