# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateRedisConsoleSessionRequest:
    """"""

    RedisID: str  # Redis实例ID，待获取控制台会话的实例ID

    Region: str  # 地域ID，地域，一批可共享的物理资源使用集合

    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离

