# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateEIPResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    EIPID: Optional[str] = None  # EIP资源ID，弹性IP的唯一标识符，申请成功后系统自动生成
