# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateVIPRequest:
    """"""

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Name: str  # VIP名称，用于标识VIP，长度1-128个字符，仅支持中英文、数字、点、下划线和中划线

    Quantity: int  # 计费数量，WAN类型VIP时使用；按月/年计费表示购买Quantity个月/年

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VIPType: str  # VIP类型，LAN为内网VIP，WAN为外网VIP；不同类型VIP的网络配置要求不同

    VPCID: str  # VPCID，指定VIP所属的VPC网络

    AssociatedResourceIDs: Optional[List[str]] = None  # 关联资源ID列表，指定需要绑定的虚拟机或弹性网卡资源ID；为空表示仅创建不绑定资源；绑定数量上限由配置GlobalConfigKeyVIPBoundLimit控制；关联资源为VM时，LAN要求与VIP同子网，WAN要求所有VM同VPC且不能已绑定NAT模式EIP

    AssociatedResourceType: Optional[str] = None  # 关联资源类型，指定绑定资源类型；VM表示虚拟机，ELASTIC_NIC表示弹性网卡；为空时默认VM

    Bandwidth: Optional[int] = None  # 带宽，单位Mbps，WAN类型VIP必填；LAN类型VIP带宽由系统配置内网带宽上限确定，

    ChargeType: Optional[str] = None  # 计费类型，WAN类型VIP必填；取值范围：Dynamic（动态）、Month（按月计费）、Year（按年计费），兼容hour/month/year；计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR

    IP: Optional[str] = None  # IP地址，指定VIP使用的IP地址；为空时系统自动从子网或外网网段分配可用地址

    IPVersion: Optional[str] = None  # IP协议版本，支持IPv4/IPv6/ALL或空值；为空时使用所选子网或外网网段的默认协议；LAN类型VIP会据此匹配对应协议版本子网

    ProjectID: Optional[str] = None  # 项目ID，资源所属项目分组标识，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注，用于说明和注释，长度0-100个字符，禁止包含<script>标签或javascript链接

    SegmentID: Optional[str] = None  # 运营商网段ID，WAN类型VIP必填，用于指定外网VIP所使用的运营商网段

    SubnetID: Optional[str] = None  # 子网ID，LAN类型VIP必填，用于从该子网分配VIP地址且与绑定资源处于同一子网；WAN类型VIP不填

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

