# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocateVMSSHSessionRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待获取SSH会话的虚拟机标识

    CmdName: Optional[str] = None  # 执行命令，连接后自动执行的命令

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    IdentityContent: Optional[str] = None  # 私钥内容，用于SSH认证的私钥

    Password: Optional[str] = None  # 密码，SSH登录密码

    Port: Optional[str] = None  # 端口号，SSH服务的端口

    User: Optional[str] = None  # 用户名，SSH登录的用户名

