# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AllocatePMVNCSessionResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SessionID: Optional[str] = None  # VNC会话ID，用于标识创建的VNC远程控制会话
