# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AttachUSBRequest:
    """"""

    AttachType: str  # 加载类型，取值Passthrough、redir

    Region: str  # 地域ID，用于标识资源所属的地理区域

    USBDeviceID: str  # USB设备ID，指定要加载到虚拟机的USB设备

    VMID: str  # 虚拟机ID，USB设备要加载到的目标虚拟机

    CompanyID: Optional[int] = None  # 租户唯一标识ID，用于验证USB设备归属权限，确保只能操作属于当前租户的设备

