# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AttachNICRequest:
    """"""

    NICID: str  # 网卡ID，指定要绑定的网卡资源

    Region: str  # 地域ID，用于标识资源所属的地理区域

    ResourceID: str  # 资源ID，指定网卡要绑定的目标资源ID，通常为虚拟机ID

    ResourceType: str  # 资源类型，指定网卡要绑定的目标资源类型；取值VM

    CompanyID: Optional[int] = None  # 租户ID，AttachNIC接口中可选，用于权限校验

    PFCode: Optional[str] = None  # 物理网卡型号标准编号，用于SR-IOV直通场景；为空表示不启用SR-IOV；与网卡QoS流量整形互斥

