# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AttachISORequest:
    """"""

    ImageID: str  # ISO镜像ID，要挂载的ISO镜像标识

    Region: str  # 地域ID，指定资源所属的地域

    ResourceID: str  # 资源ID，要挂载ISO镜像的目标资源标识

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    SetType: Optional[str] = None  # 存储集群类型，指定ISO镜像存储的集群类型，未指定则默认使用系统盘所在存储集群

