# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AttachDiskRequest:
    """"""

    DiskID: str  # 磁盘ID，要挂载的磁盘标识，共享盘仅在Detached/Shareabling/Shareabled状态下允许绑定，否则会返回StatusDiskStatusNotStable；共享盘绑定数量受到RegionConfigKeyDiskShareAbleLimit限制，超限返回StatusDiskShareAbleLimit

    Region: str  # 地域ID，指定资源所属的地域

    ResourceID: str  # 资源ID，要挂载磁盘的目标资源标识；根据磁盘和虚拟机状态，底层接口可能返回StatusDiskOverflowAttachLimit等挂载限制错误

    CacheMode: Optional[str] = None  # 缓存类型，取值 directsync、none、writeback

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    ResourceType: Optional[str] = None  # 资源类型，挂载目标的资源类型，当前仅用于兼容调用

