# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class BindSecurityGroupRequest:
    """"""

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    NICType: str  # 网卡类型，取值LAN/WAN；对于MySQL/Redis/OSS/FS仅支持WAN

    Region: str  # 地域ID，用于标识资源和安全组所属的地理区域

    ResourceID: str  # 资源ID，指定要绑定安全组的资源唯一标识符，支持VM、ELASTIC_NIC、OSS、FS、MySQL、Redis等资源类型

    SGID: str  # 安全组ID，指定要绑定的安全组唯一标识符；安全组需处于Available状态

