# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class BindAlertTemplateRequest:
    """"""

    Region: str  # 地域，目标资源所属地域

    TargetID: str  # 目标资源ID，待绑定告警模板的资源ID

    TemplateID: str  # 告警模板ID，待绑定的告警模板ID，非管理员租户需验证模板归属权限，仅允许绑定自有模板

