# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class BindStorageToDBSRequest:
    """"""

    CompanyID: int  # 租户ID，备份存储池所属租户

    Name: str  # 名称，备份存储池名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    Region: str  # 地域ID，备份存储池所属地域

    StorageType: str  # 存储类型，取值OSS或S3

    AccessKey: Optional[str] = None  # 外部服务访问密钥，当StorageType为S3时必填

    BucketName: Optional[str] = None  # 外部服务存储桶名称，当StorageType为S3时可选，空值默认dbs

    Endpoint: Optional[str] = None  # 外部服务地址，当StorageType为S3时必填

    OSSID: Optional[str] = None  # 对象存储ID，当StorageType为OSS时必填

    Remark: Optional[str] = None  # 备注，备份存储池描述信息，长度0-100字符，禁止http://或https://等非法字符

    SecretKey: Optional[str] = None  # 外部服务私钥，当StorageType为S3时必填

