# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ChangeMemberPasswordRequest:
    """"""

    Password: str  # 新密码，用于管理员重置账号密码，需满足 GlobalConfigKeyPasswordLength 与 GlobalConfigKeyPasswordComplexity 规则

    SpecMemberID: int  # 成员ID，指定要修改密码的目标账号

