# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CheckIPInuseRequest:
    """"""

    IP: str  # IP地址，指定要检查使用状态的IP地址

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    FlatNetworkID: Optional[str] = None  # 扁平网络ID，与SubnetID、SegmentID三选一且只能指定一个，用于指定要检查IP的扁平网络范围

    SegmentID: Optional[str] = None  # 网段ID，与SubnetID、FlatNetworkID三选一且只能指定一个，用于指定要检查IP的网段范围

    SubnetID: Optional[str] = None  # 子网ID，与SegmentID、FlatNetworkID三选一且只能指定一个，用于指定要检查IP的子网范围

