# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CloneKickstartTemplateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    ID: Optional[str] = None  # 模板ID
    Name: Optional[str] = None  # 模板名称
