# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class CloneVMInstanceRequest:
    """"""

    CPU: int  # 核心数，新虚拟机的vCPU核心数量

    ChargeType: str  # 计费类型，新虚拟机的计费模式，取值：Dynamic、Month、Year

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Memory: int  # 内存容量，新虚拟机的内存大小，单位：MiB

    Name: str  # 虚拟机名称，新虚拟机的显示名称，长度1-128个字符，仅支持中英文、数字、点、下划线和中划线

    Quantity: int  # 计费周期，购买的时长，按月/年计费时表示月数/年数

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 源虚拟机ID，被克隆的源虚拟机标识

    VMSPID: str  # 整机快照ID，基于该整机快照进行克隆

    ApplicationName: Optional[str] = None  # 审批名称，启用审批流程时的标题

    ApplicationReason: Optional[str] = None  # 审批理由，启用审批流程时的说明

    Bandwidth: Optional[int] = None  # 外网带宽，新虚拟机的带宽上限，单位：Mbps

    Email: Optional[str] = None  # 租户邮箱，归属租户的联系电子邮箱

    FlatNetworkID: Optional[str] = None  # 扁平网络ID，指定扁平网络，与OperatorName互斥

    IPVersion: Optional[str] = None  # IP版本，新虚拟机使用的IP协议版本，取值：IPv4、IPv6

    InternalExpandIP: Optional[str] = None  # 扩展IP，指定内网扩展IP地址

    InternalIP: Optional[str] = None  # 内网IP，指定新虚拟机的内网IP地址，留空则自动分配

    InternalIPVersion: Optional[str] = None  # 内网协议，指定内网IP协议版本，取值：IPv4、IPv6、ALL、空值

    InternetIP: Optional[str] = None  # 外网IP，指定新虚拟机的外网IP地址，留空则自动分配

    LANInAverageBandwidth: Optional[int] = None  # 入向带宽限制，第一张网卡的入向平均带宽限制，单位：Mbps，0表示不限制

    LANMAC: Optional[str] = None  # 内网MAC，指定新虚拟机的内网MAC地址，留空则自动生成

    LANOutAverageBandwidth: Optional[int] = None  # 出向带宽限制，第一张网卡的出向平均带宽限制，单位：Mbps，0表示不限制

    LANSGID: Optional[str] = None  # 内网安全组ID，新虚拟机绑定的内网安全组

    OperatorName: Optional[str] = None  # 外网线路ID，指定外网宽带运营商线路

    ProjectID: Optional[str] = None  # 项目ID，资源所属的项目分组标识

    Remark: Optional[str] = None  # 备注信息，对新虚拟机的补充说明，长度0-100个字符，禁止包含<script>标签或javascript链接

    SubnetID: Optional[str] = None  # 子网ID，新虚拟机所属的子网标识

    VPCID: Optional[str] = None  # VPCID，新虚拟机所属的VPC标识

    WANMAC: Optional[str] = None  # 外网MAC，指定新虚拟机的外网MAC地址，留空则自动生成

    WANNetworkConfig: Optional[WANNetworkConfig] = None  # WAN网络配置，克隆阶段用于声明WAN网卡及其IP配置；当前仅支持1张WAN网卡，单网卡可配置多个WAN IP

    WANSGID: Optional[str] = None  # 外网安全组ID，新虚拟机绑定的外网安全组

