# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CloneCustomImageToBaseImageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DestImageID: Optional[str] = None  # 目标镜像ID，复制成功后生成的新基础镜像标识
