# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CloseKVMSessionV2Request:
    """"""

    PMID: str  # 裸金属ID，指定要关闭会话的裸金属实例

    Region: str  # 地域ID，指定资源所属的物理区域

    SessionID: str  # 会话ID，指定要关闭的KVM会话

