# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateInstallProfileResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    ProfileID: Optional[str] = None  # 模板ID，创建成功后返回
