# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateRedisConfigFileResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    ConfigID: Optional[str] = None  # 配置文件ID，创建成功后返回的模板ID
