# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateWorkflowRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识流程所属的租户组织，管理员租户（CompanyID=200000231）创建的流程来源为Admin，普通租户创建的流程来源为Company，管理员只能为自己的管理员租户创建全局流程，普通租户只能为自己的租户创建流程，必填

    Name: str  # 自定义流程名称，用于标识和区分不同的审批流程，长度为1-128个字符，名称只能包含中英文、数字、点、下划线和中划线，必填

    NodeInfos: List[str]  # 审批节点信息列表，定义审批流程的各个节点，数组长度为1-10个节点，每项至少包含节点名称|审批人MemberID|自动审批(true/false)三段，后续可追加观察人MemberID，审批人和观察人必须来自同一租户，且审批人需按层级递增排序（子账号→子账号(租户)→管理员子账号→管理员），每个节点的观察人数量不超过10个，可以通过ListAdmin、DescribeUser和DescribeMember获取MemberID，必填

    ResourceTypes: List[str]  # 资源类型列表，指定该流程适用的资源类型，至少1项，每个租户的每种资源类型只能关联一个流程，重复关联会报错，可以通过ListProductResources获取支持的类型，必填

    Remark: Optional[str] = None  # 备注信息，用于说明流程的用途或特殊要求，长度为0-100个字符，不能包含<script>或javascript等非法内容

