# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVSPolicyResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    PolicyID: Optional[str] = None  # 转发规则ID，用于定位新建的转发规则
