# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDBSGatewayRequest:
    """"""

    Name: str  # 名称，DBS网关名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    Region: str  # 地域，备份源的地域

    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离

    EIPID: Optional[str] = None  # 外网IPID，外网的IPID

    ProjectID: Optional[str] = None  # 项目组ID，项目组的ID

    Remark: Optional[str] = None  # 备注，DBS网关的描述信息，长度0-100字符，禁止http://或https://等非法字符

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串，

