# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateResourceTemplateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    TemplateID: Optional[str] = None  # 模板ID，系统生成的唯一标识
