# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNodeHostDeviceRequest:
    """"""

    Bus: int  # 总线编号，设备在节点上的总线编号，来源于扫描结果

    Device: int  # 设备编号，设备在节点上的设备编号，来源于扫描结果

    HostDeviceName: str  # 外置设备名称，用于创建资源名称，长度1-128个字符，仅支持中英文、数字、点、下划线和中划线

    NodeID: str  # 物理机节点ID，设备所在物理机标识，必须为计算授权通过的节点

    Region: str  # 地域ID，用于标识外置设备资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识请求发起租户，未指定TargetCompanyID时作为资源归属租户

    HostDeviceType: Optional[str] = None  # 设备类型，用于标识外置设备类型，如USB、GPU

    ProductName: Optional[str] = None  # 产品名称，用于设备模板匹配或创建，两者（VendorName与ProductName）都为空则不创建模板

    ProjectID: Optional[str] = None  # 项目ID，资源所属的项目分组标识，为空则不关联项目

    Remark: Optional[str] = None  # 备注信息，用于补充说明，需符合uremark规则（0-100字符，禁止包含<script>/javascript）

    TargetCompanyID: Optional[int] = None  # 目标租户ID，指定资源归属的目标租户，填写后覆盖CompanyID

    VendorName: Optional[str] = None  # 厂商名称，用于设备模板匹配或创建，两者（VendorName与ProductName）都为空则不创建模板

