# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSubnetResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SubnetID: Optional[str] = None  # 子网ID，创建成功后返回的子网唯一标识符
