# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNICRequest:
    """"""

    ChargeType: str  # 计费类型，用于指定计费模式；仅WAN类型网卡计费生效；取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year；计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    NICType: str  # 网卡类型，指定IP分配来源；取值LAN（VPC内网）、WAN（外网网段）、Flat（扁平网络）

    Name: str  # 网卡名称，用于标识网卡，长度1-128个字符，仅支持中英文、数字、点、下划线和中划线

    Quantity: int  # 计费数量，按月/年计费时表示购买Quantity个月/年；仅WAN类型网卡计费生效

    Region: str  # 地域ID，用于标识资源所属的地理区域

    Bandwidth: Optional[int] = None  # 带宽，单位Mbps，仅WAN类型网卡必填

    ExpandIP: Optional[str] = None  # 扩展IP地址，用于网卡绑定额外的IP地址

    FlatNetworkID: Optional[str] = None  # 扁平网络ID，指定网卡所属的扁平网络；仅Flat类型网卡必填

    IP: Optional[str] = None  # IP地址，指定网卡使用的IP地址；为空时从所属网络自动分配

    IPVersion: Optional[str] = None  # IP协议版本，空值表示使用所选VPC或外网网络的默认协议；取值IPv4/IPv6/ALL

    InAverageBandwidth: Optional[int] = None  # 入向平均带宽，仅Flat类型网卡可指定，用于QoS流量整形；0表示不限制，单位Mbps，取值范围由网卡规格配置确定，

    MAC: Optional[str] = None  # MAC地址，格式为6组2位十六进制数，以冒号或连字符分隔；为空时系统自动分配

    OutAverageBandwidth: Optional[int] = None  # 出向平均带宽，仅Flat类型网卡可指定，用于QoS流量整形；0表示不限制，单位Mbps，取值范围由网卡规格配置确定，

    ProjectID: Optional[str] = None  # 项目ID，资源所属项目分组标识

    Remark: Optional[str] = None  # 备注，用于说明和注释，长度0-100个字符，禁止包含<script>标签或javascript链接

    SGID: Optional[str] = None  # 安全组ID，用于管控进出网卡的网络流量；可选，允许不绑定

    SegmentID: Optional[str] = None  # 外网线路ID，指定外网IP所属线路；仅WAN类型网卡必填

    SubnetID: Optional[str] = None  # 子网ID，网卡所属子网标识；仅LAN类型网卡必填

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

    VPCID: Optional[str] = None  # VPCID，网卡所属的专有网络ID，仅LAN类型网卡使用

