# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateLBResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    LBID: Optional[str] = None  # 负载均衡ID，负载均衡的唯一标识
