# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateRemoteVPNGWResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    RemoteVPNGWID: Optional[str] = None  # 对端网关ID，创建成功的对端网关唯一标识
