# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSMCResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SMCID: Optional[str] = None  # SMC任务唯一标识ID
