# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDiskRequest:
    """"""

    ChargeType: str  # 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR

    DiskSpace: int  # 磁盘大小，单位GiB，用于指定创建磁盘的存储容量，最终IOPS/带宽由SetType和容量联合计算

    Name: str  # 磁盘名称，支持中英文、数字、点、下划线和中划线，长度1-128个字符

    Quantity: int  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1

    Region: str  # 地域ID，指定资源所属的地域

    SetType: str  # 存储集群类型，指定磁盘所属的存储集群，仅支持当前租户具备权限的存储集群，否则创建会失败

    ApplicationName: Optional[str] = None  # 审批名称，用于审批流程的标题描述，当启用审批流程时使用

    ApplicationReason: Optional[str] = None  # 审批理由，用于说明申请创建磁盘的原因，当启用审批流程时使用

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    ProjectID: Optional[str] = None  # 项目组ID，资源所属项目组

    Remark: Optional[str] = None  # 磁盘备注，长度0-100个中英文字符，禁止包含http://或https://等非法字符

    Secret: Optional[str] = None  # 加密密钥，使用Base64编码传入以创建加密磁盘；未指定则创建非加密磁盘，创建后无法修改密钥

    ShareAble: Optional[bool] = None  # 是否为共享盘，true表示共享盘，false表示普通盘，共享盘支持被多台虚拟机挂载，但后续绑定数量受RegionConfigKeyDiskShareAbleLimit限制

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码

