# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreatePlatformStorageDiskRequest:
    """"""

    DiskSpace: int  # 磁盘大小，创建平台通用存储云盘的容量，单位GiB

    Region: str  # 地域ID，指定资源所属的物理区域

    SetType: str  # 集群类型，目标存储集群的类型标识

