# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateExternalStorageSetRequest:
    """"""

    CSIPluginAddress: str  # CSI插件地址，存储集群CSI插件的访问地址，格式为IP:Port，支持多个地址用逗号分隔

    Name: str  # 名称，存储集群名称，1-128个字符，仅支持中文、英文字母、数字、点（.）、下划线（_）和中划线（-）

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，外置存储集群所属租户

    DisableTargetIQNs: Optional[List[str]] = None  # IQN禁用列表，符合iqn.YYYY-MM.domain[:suffix]格式的IQN列表

    EnableTargetIQNs: Optional[List[str]] = None  # IQN启用列表，符合iqn.YYYY-MM.domain[:suffix]格式的IQN列表

    Password: Optional[str] = None  # 密码，登录存储集群的密码，最多50个字符

    UserName: Optional[str] = None  # 用户名，登录存储集群的用户名，最多50个字符

