# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateBucketRequest:
    """"""

    AccessType: str  # 访问类型，桶访问权限级别，取值范围：Private、PublicRead、PublicReadWrite

    Name: str  # 桶名称，创建后不可修改

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    BucketCryptEnabled: Optional[bool] = None  # 桶加密开关，是否开启服务端加密

    ObjectLockDays: Optional[int] = None  # 对象锁定时间，单位天，用于设置对象保留时长

    ObjectLockEnabled: Optional[bool] = None  # 对象锁定开关，是否启用对象锁定

    Quota: Optional[int] = None  # 桶配额，单位GB

    Versioning: Optional[bool] = None  # 多版本开关，是否开启多版本管理

