# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNATGWPolicyRequest:
    """"""

    DstPort: str  # 目标端口，目标虚拟机的端口号，支持单端口或端口范围（如8080或8080-8090），取值范围1-65535，协议+目标IP+目标端口组合不能与已有规则重复

    DstResourceID: str  # 目标虚拟机ID，端口转发的目标虚拟机唯一标识

    NATGWID: str  # NAT网关ID，用于定位需要添加DNAT规则的NAT网关实例，该NAT网关必须处于运行状态，同一NAT网关最多可创建200条DNAT规则

    Protocol: str  # DNAT协议，端口转发规则使用的协议类型，取值范围：TCP、UDP

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SrcIP: str  # 源IP，DNAT规则使用的外网IP地址，必须为该NAT网关已绑定的EIP地址

    SrcPort: str  # 源端口，DNAT规则的外网端口，支持单端口或端口范围（如80或80-90），取值范围1-65535，协议+外部IP+外部端口组合不能与已有规则重复

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

