# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateRoleRequest:
    """"""

    Name: str  # 角色名称，用于标识自定义角色并在控制台显示，长度为1-50个字符，只能包含中英文、数字、点、下划线和中划线

    Permission: str  # 权限定义，指定角色拥有的API操作权限集，格式：Action-1（允许）、Action-0（禁止）

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，

