# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOnSiteInspectionResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    InspectionID: Optional[str] = None  # 一键巡检报告ID，用于后续查询、删除等操作
