# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVSResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    VSID: Optional[str] = None  # 虚拟服务器ID，用于标识监听器实例
