# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateResourceEventNotifyRuleResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    RuleID: Optional[str] = None  # 规则ID，资源事件通知规则ID
