# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDTSTaskResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DTSID: Optional[str] = None  # DTS任务ID，新创建的数据传输任务唯一标识
