# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreatePortGroupRequest:
    """"""

    Name: str  # 端口组名称，用于标识端口组，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符

    Region: str  # 地域ID，用于标识端口组所属的地理区域

    Rules: str  # 端口组规则，定义端口组包含的协议与端口组合，格式为协议:端口或协议:端口范围，多条规则以逗号分隔

    CompanyID: Optional[int] = None  # 租户ID，标识端口组所属的租户组织，用于多租户资源隔离与权限控制

    ProjectID: Optional[str] = None  # 项目ID，端口组所属项目分组标识

    Remark: Optional[str] = None  # 备注，用于说明和注释，长度0-100字符，禁止http://或https://等非法字符

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

