# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateAdminRequest:
    """"""

    GrantLevel: str  # 授权等级，用于决定管理员的管理边界；取值：System（系统级）、Region（地域级）

    MemberEmail: str  # 账号邮箱，管理员登录身份标识，需符合邮箱格式

    MemberName: str  # 成员名称，管理员展示名称用于管理界面显示，长度为1-30个字符，只能包含中英文、数字、点、下划线和中划线

    Password: str  # 登录密码，用于管理员登录；若使用 X-Auth-Method: plain 则需 Base64 输入并在服务端转为 AES 加密；需满足 GlobalConfigKeyPasswordLength 与 GlobalConfigKeyPasswordComplexity 规则

    Regions: List[str]  # 地域ID列表，当GrantLevel=Region时必填且至少一个，用于在创建管理员时原子完成地域授权

    RoleIDs: List[str]  # 角色ID列表，为空时根据 ReadOnly 推导默认角色，用于指定管理员所属角色集合

    Phone: Optional[str] = None  # 手机号，用于安全通知或验证码接收，需为合法手机号

    ReadOnly: Optional[str] = None  # 只读权限（兼容字段），新调用建议使用 RoleIDs 明确授权；取值：1, Y, Yes, true 表示是，其他表示否

    ResetPassword: Optional[str] = None  # 重置密码，指定首次登录时是否强制修改密码；取值：1, Y, Yes, true 表示是，其他表示否

