# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVPCResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    VPCID: Optional[str] = None  # VPCID，新创建的虚拟私有网络唯一标识符
