# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateMySQLRequest:
    """"""

    ChargeType: str  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    ConfigFileID: str  # 配置文件模板ID，用于指定MySQL实例的配置模板，系统会复制该模板创建新的配置文件

    Memory: int  # 内存大小，单位MiB，最小2048 MiB（2GB），必须是1024的倍数（即以GB为单位）

    Name: str  # MySQL实例名称，1-128个字符，仅支持中英文、数字、点、下划线和中划线

    Password: str  # root用户密码，长度6-64个字符，支持字母、数字及部分特殊字符，必须包含至少2种字符类型

    Quantity: int  # 计费数量，指定计费周期的数量，按月/年计费时表示购买的月数/年数，按小时计费时强制为1

    Region: str  # 地域ID，指定资源所属的物理区域

    SubnetID: str  # 子网ID，创建虚拟机时必须选择VPC网络和所属子网，即选择虚拟要加入的网络及IP网段

    VMType: str  # 计算集群类型，MySQL实例所在计算集群类型，注意：AARCH64架构不支持MySQL 5.7版本

    VPCID: str  # VPCID，创建虚拟机时必须选择VPC网络和所属子网，即选择虚拟要加入的网络及IP网段

    Version: str  # MySQL版本，必须为枚举值之一，取值范围：MySQL 5.7、MySQL 8.0，注意：AARCH64架构不支持MySQL 5.7版本

    BackupID: Optional[str] = None  # 备份文件ID，用于从备份恢复创建MySQL实例，条件互斥：当提供BackupID时，HighAvailability不能为ActiveStandy；当提供BackupID时，DiskSetType和DiskSpace字段会被忽略

    DiskSetType: Optional[str] = None  # 存储集群ID，指定云硬盘所在的存储集群，条件必填：当BackupID为空时（全新创建）此字段为必填；从备份创建时此字段会被忽略

    DiskSpace: Optional[int] = None  # 存储容量，单位GiB，条件必填：当BackupID为空时（全新创建）此字段为必填且必须大于0；从备份创建时此字段会被忽略，使用备份中的容量信息

    EIPID: Optional[str] = None  # 外网IP资源ID，用于绑定公网IP，如果提供，系统会检查该IP是否已被绑定到其他资源，若已绑定则创建失败

    HighAvailability: Optional[str] = None  # MySQL数据库高可用类型，取值范围：Standalone（单机版，创建1个VM节点）、ActiveStandy（高可用版/双节点主备，创建2个VM节点），默认值：Standalone，业务限制：当BackupID不为空（从备份恢复）时，拒绝ActiveStandy，只能创建单机实例

    ProjectID: Optional[str] = None  # 项目ID，用于实现资源的逻辑分组管理

    Remark: Optional[str] = None  # 备注，用于说明和注释，长度为0-100个英文或中文字符，不能包含<script>、<a javascript:>等非法字符，用于XSS防护

    RestoreTime: Optional[int] = None  # 恢复时间，指定从备份恢复的时间点，Unix时间戳（秒级），用于时间点恢复功能

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串

    TerminationPolicy: Optional[int] = None  # 删除保护策略，取值范围：0（开启删除保护，删除操作会被拒绝）、1（关闭删除保护，允许删除），默认值：0

    WANSGID: Optional[str] = None  # 外网安全组ID，用于外网访问控制，如果需要使用外网安全组，需提前创建安全组后获取其ID

