# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateAlertNotifyWebhookResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    NotifyWebhookID: Optional[str] = None  # Webhook ID，Webhook唯一标识
