# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSubMemberRequest:
    """"""

    MemberEmail: str  # 账号邮箱，子账号登录身份标识，需符合邮箱格式

    MemberName: str  # 成员名称，子账号展示名称用于管理界面显示

    Password: str  # 登录密码，用于子账号登录；若使用 X-Auth-Method: plain 则需 Base64 输入并在服务端转为 AES 加密；需满足 GlobalConfigKeyPasswordLength 与 GlobalConfigKeyPasswordComplexity 规则

    CompanyID: Optional[int] = None  # 租户ID，标识子账号归属的租户实体，通常由登录上下文确定

    OAuth2UniqueID: Optional[str] = None  # OAuth2唯一标识ID，用于绑定外部身份认证系统的用户身份

    Phone: Optional[str] = None  # 手机号，用于安全通知或验证码接收，需为合法手机号

    ResetPassword: Optional[str] = None  # 重置密码，指定子账号首次登录时是否必须修改密码；取值：1, Y, Yes, true 表示是，其他表示否

