# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateOrchTaskRequest:
    """"""

    CompanyID: int  # 租户ID，任务所属租户

    Name: str  # 任务名称，编排任务名称，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符

    Region: str  # 地域，编排任务所属地域

    ResourceType: str  # 资源类型，编排任务作用的资源类型，必须与TaskType匹配，取值：VM

    Steps: List[str]  # 步骤列表，定义编排任务的执行步骤，每个步骤为JSON字符串，格式：{"order":1,"delay":0,"resourceIDs":"vm-xx,vm-yy"}；delay取值范围0-3600；order在所有步骤中必须唯一；resourceIDs为逗号分隔的资源ID列表，同一资源ID在所有步骤中只能出现一次；所有资源必须存在且为AVAILABLE，且资源类型必须与ResourceType一致

    TaskType: str  # 任务类型，必须与ResourceType匹配，取值：StartInOrder/StopInOrder

    Condition: Optional[str] = None  # 资源筛选条件，用于动态选择资源，当前未使用

    ProjectID: Optional[str] = None  # 项目组ID，任务所属项目组，当前未使用

    Remark: Optional[str] = None  # 任务备注，编排任务描述信息，长度0-100字符，禁止http://或https://等非法字符

