# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDataCheckTaskResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DTSID: Optional[str] = None  # 校验任务ID，新创建的数据校验任务唯一标识
