# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateResourceUsageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    ResourceUsageID: Optional[str] = None  # 资源用量ID，用于后续查询、删除等操作
