# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVPNTunnelResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    VPNTunnelID: Optional[str] = None  # VPN隧道ID，创建成功的VPN隧道唯一标识
