# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSuperNodeRequest:
    """"""

    ClusterID: str  # 集群Id

    ComputeclassType: str  # 计算集群类型

    NodeName: str  # 节点名称

    Region: str  # 地域

    CompanyID: Optional[int] = None  # 租户ID

    MaxCPU: Optional[int] = None  # 节点最大CPU数量

    MaxMemory: Optional[int] = None  # 节点最大内存容量

    MaxPods: Optional[int] = None  # 节点最大pod数量

    StorageclassType: Optional[str] = None  # 存储集群类型

