# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateProductSpecificationRequest:
    """"""

    Region: str  # 地域ID，指定规格所属地域

    ResourceType: str  # 资源类型，指定规格的资源类型

    SetType: str  # 集群类型，指定规格所属的集群类型

    SpecificationName: str  # 规格名称，需与规格模板中定义的名称一致

    Value: str  # 规格值，需符合规格模板定义的格式要求

