# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateRedisRequest:
    """"""

    ChargeType: str  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    ConfigID: str  # 配置文件ID，用于指定Redis实例的配置模板

    Count: str  # 购买数量，创建实例的数量

    HighAvailability: str  # Redis数据库高可用类型，取值范围：Standalone（单机版，创建1个VM节点）、ActiveStandy（高可用版/主备版，创建2个VM节点），当BackupID不为空（从备份恢复）时仅支持Standalone

    Memory: int  # 内存大小，单位：GiB，系统会根据比率自动调整实际分配的内存

    Name: str  # Redis实例名称，长度为1-128个字符，名称只能包含中英文、数字、点、下划线和中划线

    Region: str  # 地域ID，指定资源所属的物理区域

    SubnetID: str  # 子网ID，创建虚拟机时必须选择VPC网络和所属子网

    VMType: str  # 计算集群类型，虚拟机所在宿主机的集群类型，需要有访问权限

    VPCID: str  # VPCID，创建虚拟机时必须选择VPC网络和所属子网

    BackupID: Optional[str] = None  # 备份文件ID，用于从备份恢复创建Redis实例，条件互斥：当提供BackupID时，HighAvailability不能为ActiveStandy

    DiskSetType: Optional[str] = None  # 存储集群ID，指定云硬盘所在的存储集群，若不指定，系统会自动获取最空闲的存储集群

    EIPID: Optional[str] = None  # 外网IP资源ID，用于绑定公网IP，如果提供，系统会检查该IP是否已被绑定到其他资源，若已绑定则创建失败

    Password: Optional[str] = None  # Redis登录密码，要求：1.长度6-64个字符2.支持字母、数字及部分特殊字符（~!@#^&*_+{}|:<>?-=[],./等）3.不支持反引号、单引号、反斜杠、$、%、;、小括号4.必须包含至少2种字符类型（大写字母、小写字母、数字、特殊字符）

    ProjectID: Optional[str] = None  # 项目ID，用于实现资源的逻辑分组管理

    Quantity: Optional[int] = None  # 计费数量，指定计费周期的数量，按月/年计费时表示购买的月数/年数，按小时计费时强制为1

    Remark: Optional[str] = None  # 备注，用于说明和注释，长度为0-100个英文或中文字符，不能包含<script>、<a javascript:>等非法字符，用于XSS防护

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串，

    TerminationPolicy: Optional[int] = None  # 删除保护策略，取值范围：0（开启删除保护，删除操作会被拒绝）、1（关闭删除保护，允许删除），默认值：0

    Threads: Optional[int] = None  # 线程数量，仅Redis7.0版本有效，默认值：Redis4.0默认为1，Redis7.0默认为2

    Version: Optional[str] = None  # Redis版本，必须为枚举值之一，取值范围：4.0、7.0，默认值：4.0

    WANSGID: Optional[str] = None  # 外网安全组ID，用于外网访问控制，如果需要使用外网安全组，需提前创建安全组后获取其ID

