# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateAdminResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    MemberID: Optional[int] = None  # 成员ID，创建成功后返回的管理员账号标识
