# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSecurityGroupRequest:
    """"""

    CompanyID: int  # 租户ID，标识安全组所属的租户组织，用于多租户资源隔离与权限控制

    Name: str  # 安全组名称，用于标识安全组，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符

    Region: str  # 地域ID，用于标识安全组所属的地理区域

    ProjectID: Optional[str] = None  # 项目ID，安全组所属项目分组标识，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注，用于说明和注释，长度0-100字符，禁止http://或https://等非法字符

    Rule: Optional[List[str]] = None  # 安全组规则列表，定义流量控制策略；创建安全组时可为空；每条规则格式：协议|端口|地址|动作|优先级|方向|备注；协议支持TCP/UDP/ICMP/ICMPv4/ICMPv6/ALL，端口支持1-65535或端口范围，地址支持IP/CIDR或group:IPGroupID，动作支持ACCEPT/DROP，优先级支持HIGH/MEDIUM/LOW，方向1为入站0为出站；端口组引用格式：group:PortGroupID|-|地址|动作|优先级|方向|备注；备注长度不超过100字符

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

