# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDirectConnectResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DirectConnectID: Optional[str] = None  # 专线接入ID
