# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVMInstanceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    DiskID: Optional[str] = None  # 数据盘ID，盘的唯一标识
    DiskIDs: Optional[List[str]] = None  # 数据盘ID列表，挂载的数据盘唯一标识列表
    EIPID: Optional[str] = None  # 外网资源ID，绑定的弹性IP标识
    EIPIDs: Optional[List[str]] = None  # 外网资源ID列表，创建阶段生成的WAN IP标识列表；首个元素与EIPID一致，后续元素为附加WAN IP的标识
    VMID: Optional[str] = None  # 虚拟机ID，创建成功的云主机实例标识
