# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSlaveRedisRequest:
    """"""

    ChargeType: str  # 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR

    CompanyID: int  # 租户ID，从库实例所属租户

    Memory: int  # 内存容量，单位MiB，且不得小于主库内存

    Name: str  # 名称，从库实例名称，长度为1-128个字符，名称只能包含中英文、数字、点、下划线和中划线

    RedisID: str  # 主库ID，从库所属主库实例ID；必须为主库实例且状态为Running，单主库最多5个从库

    Region: str  # 地域ID，从库实例所属地域

    VMType: str  # 计算集群类型，从库实例所属计算集群类型

    DiskSetType: Optional[str] = None  # 存储集群类型，从库实例数据盘所属存储集群类型

    EIPID: Optional[str] = None  # 外网IP资源ID，用于绑定公网IP

    Password: Optional[str] = None  # 密码，从库登录密码

    Quantity: Optional[int] = None  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1

    Remark: Optional[str] = None  # 描述，从库实例备注，长度为0-100个英文或中文字符，不能包含<script>、<a javascript:>等非法字符，用于XSS防护

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，资源标签键值对列表，格式为Base64编码的key:value

    Threads: Optional[int] = None  # 线程数量，Redis7.0有效

    Version: Optional[str] = None  # Redis版本，取值4.0或7.0，默认4.0；主库为7.0时从库版本必须为7.0

    WANSGID: Optional[str] = None  # 安全组ID，用于外网访问控制

