# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateAlertTemplateRuleResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    RuleID: Optional[str] = None  # 告警规则ID，告警规则唯一标识，格式为rule-前缀加14位随机字符
