# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreatePartitionTemplateRequest:
    """"""

    Config: str  # 分区配置，JSON格式字符串，包含分区列表、LVM卷组、RAID配置等信息，前端可提交展开后的点式路径字段（如Config.Scheme）或JSON字符串

    Name: str  # 模板名称，分区模板的唯一标识名称

    OSDistribution: str  # 操作系统发行版，指定该分区模板适用的操作系统类型

    Region: str  # 地域ID，指定资源所属的物理区域

    SchemeType: str  # 分区方案类型，指定分区管理方式，standard：标准分区；lvm：LVM逻辑卷；raid：RAID阵列；btrfs：Btrfs文件系统

    Description: Optional[str] = None  # 模板描述，说明分区模板的用途和特点

