# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateTimerResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    TimerID: Optional[str] = None  # 定时器ID，创建成功后返回的定时器唯一标识符，用于后续查询、更新和删除操作
