# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNativeNodeResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    NodeName: Optional[str] = None  # 节点名称
