# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateNATGWResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    NATGWID: Optional[str] = None  # NAT网关ID，创建成功的NAT网关唯一标识
