# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class CreateDTSTaskRequest:
    """"""

    CPU: int  # CPU核数，用于指定DTS实例的CPU配置

    ChargeType: str  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    ComputeClass: str  # 计算集群类型，用于指定DTS实例运行的计算集群，需具备集群权限

    DestinationEndpointInstanceType: str  # 目标实例类型，指定目标数据库的部署位置，取值范围：Internal（平台内部数据库）、External（外部数据库）

    DestinationEngine: str  # 目标实例数据库类型，指定目标数据库引擎类型，取值范围：MYSQL、REDIS，必须与SourceEngine一致

    MaxRPS: int  # 最大每秒同步记录数，用于限制数据同步速率，取值最小范围为100，最大范围根据DTS实例CPU核数确定，1核上限为20000，2核上限为40000

    Memory: int  # 内存大小，单位GB，用于指定DTS实例的内存配置

    Name: str  # DTS任务名称，支持中文、英文字母、数字、点、下划线和中划线，长度1-128字符

    Quantity: int  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SourceEndpointInstanceType: str  # 源实例类型，指定源数据库的部署位置，取值范围：Internal（平台内部数据库）、External（外部数据库）

    SourceEngine: str  # 源实例数据库类型，指定源数据库引擎类型，取值范围：MYSQL、REDIS，必须与DestinationEngine一致

    StorageClass: str  # 存储集群类型，用于指定DTS实例系统盘所在存储集群，需具备集群权限

    TaskMode: str  # 任务类型，指定数据传输的同步模式，取值范围：full（全量迁移）、incremental（增量同步）、full+incremental（全量加增量）

    BatchSize: Optional[int] = None  # 单批写入大小，用于控制 sinker 每次批量写入的记录数；为0时使用系统默认值1000

    DataMarkTable: Optional[str] = None  # 数据标记表，用于双向同步场景记录已同步数据，格式为database.table_name，若不指定则同步服务自动创建，需确保数据库账户有创建表权限

    Databases: Optional[str] = None  # 同步数据库列表，指定需要同步的数据库名称，多个数据库用逗号分隔；不指定则默认同步所有数据库

    DestinationEndpointBinlogGTID: Optional[str] = None  # 目标库GTID集合，用于双向同步场景，指定目标库GTID起始位置，可通过show master status获取，用于反向增量同步

    DestinationEndpointIP: Optional[str] = None  # 目标实例地址，当DestinationEndpointInstanceType为External时必填，指定外部数据库访问地址，源与目标地址端口不可完全相同

    DestinationEndpointInstanceID: Optional[str] = None  # 目标实例ID，当DestinationEndpointInstanceType为Internal时必填，指定平台内部数据库实例，需可用且归属当前租户，且类型与DestinationEngine一致，不能与源实例ID相同

    DestinationEndpointPassword: Optional[str] = None  # 目标实例密码，当DestinationEngine为MYSQL时必填，用于连接目标数据库的账号密码

    DestinationEndpointPort: Optional[int] = None  # 目标实例端口，当DestinationEndpointInstanceType为External时必填，MYSQL默认3306，REDIS默认6379，源与目标地址端口不可完全相同

    DestinationEndpointUserName: Optional[str] = None  # 目标实例用户名，当DestinationEngine为MYSQL时必填，用于连接目标数据库的账号用户名，需具备写入权限

    EIPID: Optional[str] = None  # 弹性公网IPID，当源端或目的端为External时必填，用于DTS与外部数据库建立网络连接，EIP需未绑定其他资源

    HeartbeatInterval: Optional[int] = None  # 心跳间隔秒数，指定推进binlog位点的时间间隔（秒），用于防止长时间无数据变更导致位点不更新

    HeartbeatTable: Optional[str] = None  # 心跳表名称，用于增量或双向同步场景定时推进binlog位点，格式为database.table_name，若不指定则同步服务自动创建，需确保数据库账户有创建表权限

    IgnoreDatabases: Optional[str] = None  # 忽略数据库列表，指定需要排除的数据库名称，多个数据库用逗号分隔，与Databases互斥使用

    IgnoreTables: Optional[str] = None  # 忽略数据表列表，指定需要排除的数据表，支持通配符，格式为database.table，多个表用逗号分隔，与Tables互斥使用

    IncrementalRestart: Optional[DTSServiceRestartPolicy] = None  # 增量同步阶段的 DTS 自恢复策略；不传表示沿用 DTS 默认自恢复策略，显式 Enabled=false 表示关闭 DTS 自恢复

    ProjectID: Optional[str] = None  # 项目ID，用于标识资源所属项目分组，未传时尝试分配默认项目

    Remark: Optional[str] = None  # 备注，长度0-100字符，禁止http://或https://等非法字符

    SourceEndpointBinlogGTID: Optional[str] = None  # binlog GTID集合，用于MYSQL增量或全量加增量同步时基于GTID模式同步，可通过show master status获取，

    SourceEndpointBinlogName: Optional[str] = None  # binlog文件名，用于MYSQL增量或全量加增量同步时指定起始binlog位置，可通过show master status获取，

    SourceEndpointBinlogPos: Optional[int] = None  # binlog位点，用于MYSQL增量或全量加增量同步时指定起始binlog偏移量，可通过show master status获取，

    SourceEndpointIP: Optional[str] = None  # 源实例地址，当SourceEndpointInstanceType为External时必填，指定外部数据库访问地址，源与目标地址端口不可完全相同

    SourceEndpointInstanceID: Optional[str] = None  # 源实例ID，当SourceEndpointInstanceType为Internal时必填，指定平台内部数据库实例，需可用且归属当前租户，且类型与SourceEngine一致

    SourceEndpointPassword: Optional[str] = None  # 源实例密码，当SourceEngine为MYSQL时必填，用于连接源数据库的账号密码

    SourceEndpointPort: Optional[int] = None  # 源实例端口，当SourceEndpointInstanceType为External时必填，MYSQL默认3306，REDIS默认6379，源与目标地址端口不可完全相同

    SourceEndpointServerID: Optional[str] = None  # 服务器ID，当SourceEngine为MYSQL时必填，用于标识DTS服务作为从库的唯一ID，需确保不与现有slave的server_id重复

    SourceEndpointUserName: Optional[str] = None  # 源实例用户名，当SourceEngine为MYSQL时必填，用于连接源数据库的账号用户名，需具备读取权限

    Tables: Optional[str] = None  # 同步数据表列表，指定需要同步的数据表，支持通配符，格式为database.table，多个表用逗号分隔；不指定则同步所有数据表

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，格式为Base64编码的key:value字符串，用于资源标记和分类管理

