# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateSegmentRouteRequest:
    """"""

    Destination: str  # 目的地址，路由的目标网段，必须为CIDR格式，系统会自动使用net.ParseCIDR格式化为标准CIDR表示（如10.0.0.0/16），不能与外网线路中已存在的路由目的地址冲突

    NextHop: str  # 下一跳IP地址，必须为合法的IP地址格式，且必须在外网线路网段范围内

    Region: str  # 地域ID，指定外网线路路由所属的物理区域

    SegmentID: str  # 外网线路ID，指定要添加路由规则的外网线路，单个外网线路最多支持50条自定义路由

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符

