# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateDiskFromSnapshotRequest:
    """"""

    ChargeType: str  # 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR

    Name: str  # 磁盘名称，支持中英文、数字、点、下划线和中划线，长度1-128个字符

    Quantity: int  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1

    Region: str  # 地域ID，指定资源所属的地域

    SrcSnapshotID: str  # 源快照ID，新磁盘会自动继承快照所属磁盘的存储集群、容量和加密密钥；当源磁盘已被删除或不在可用状态时会返回StatusDiskInRecycleBin

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    ProjectID: Optional[str] = None  # 项目组ID，资源所属项目组

    Remark: Optional[str] = None  # 磁盘备注，长度0-100个中英文字符，禁止包含http://或https://等非法字符

    TagKeyValuePairs: Optional[List[str]] = None  # 标签键值对，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码

