# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteMemberTagRequest:
    """"""

    MemberID: int  # 成员ID，用于指定需移除授权的账号

    RoleID: str  # 角色ID，用于指定要移除的角色

    ProjectID: Optional[str] = None  # 项目组ID，租户级别用户必填；系统级/区域级授权可为空

