# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteIPGroupRequest:
    """"""

    IPGroupID: str  # IP组ID，指定要删除的IP组唯一标识符；删除前会检查是否被安全组规则引用

    Region: str  # 地域ID，用于标识IP组所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识IP组所属的租户组织，用于多租户资源隔离与权限控制

