# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteAlertNotifyGroupRequest:
    """"""

    NotifyGroupID: str  # 通知组ID，待删除的通知组ID；当通知组仍被告警规则引用时会返回错误

