# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteMulticastGroupRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    MulticastGroupID: str  # 组播组ID，指定要删除的组播组唯一标识符

    Region: str  # 地域ID，指定资源所属的物理区域

