# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteDiskRequest:
    """"""

    DiskID: str  # 磁盘ID，要删除的磁盘标识，删除前会校验地域级删除权限(CheckAllowDeleteResource)并通过底层CheckAllowDeleteDisk确认磁盘未被使用，校验未通过会返回相应限制错误

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

