# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteVPNTunnelRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VPNTunnelID: str  # VPN隧道ID，待删除的VPN隧道唯一标识

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

