# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteOPLogNotifyRuleRequest:
    """"""

    RuleID: str  # 规则ID，操作日志通知规则ID

