# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteProductSpecificationResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    SpecificationID: Optional[str] = None  # 规格ID，已删除的规格唯一标识符
