# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteNICRequest:
    """"""

    CompanyID: int  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    NICID: str  # 弹性网卡ID，指定要删除的网卡资源

    Region: str  # 地域ID，用于标识资源所属的地理区域

