# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteFlatNetworkResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

