# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteMySQLParamTplRequest:
    """"""

    Region: str  # 地域ID，模板所属地域

    TplID: str  # 模板ID，参数模板ID

    CompanyID: Optional[int] = None  # 租户ID，模板所属租户

