# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteRedisConfigFileRequest:
    """"""

    ConfigID: str  # 配置ID，参数模板ID

