# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteInstallProfileRequest:
    """"""

    ProfileID: str  # 模板ID，指定要删除的模板

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，预留字段，当前不生效

