# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteAlertNotifyReceiverRequest:
    """"""

    NotifyReceiverID: str  # 接收人ID，待删除的接收人ID，可通过创建或查询接收人接口获取

