# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteDBSBackupPlanRequest:
    """"""

    PlanID: str  # 计划ID，待删除的备份计划ID

    CompanyID: Optional[int] = None  # 租户ID，备份计划所属租户

