# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteSubnetRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SubnetID: str  # 子网ID，删除前会校验是否允许删除

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

