# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteKickstartTemplateRequest:
    """"""

    ID: str  # 模板ID

    Region: str  # 地域

