# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteNATGWRuleRequest:
    """"""

    NATGWID: str  # NAT网关ID，用于定位SNAT规则所属的NAT网关实例，该NAT网关必须处于运行状态

    Region: str  # 地域ID，用于标识资源所属的地理区域

    RuleID: str  # SNAT规则ID，用于定位需要删除的SNAT规则，规则状态不能为创建中或更新中

    CompanyID: Optional[str] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

