# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteAlertTemplateRequest:
    """"""

    TemplateID: str  # 告警模板ID，待删除的告警模板ID；若模板类型为REGION或仍绑定资源则会返回错误

