# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DeleteFlatNetworkRouteRequest:
    """"""

    Destination: str  # 目的地址CIDR，指定要删除的路由目标网段，仅支持删除NextHopType为local的本地路由

    FlatNetworkID: str  # 扁平网络ID，指定路由所属的扁平网络唯一标识

    Region: str  # 地域ID，用于标识资源所属的地理区域

