# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeStorageTypeRequest:
    """"""

    Region: str  # 地域ID，指定存储集群类型所属的物理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，用于按权限过滤可见的存储类型，普通租户需填写自身CompanyID；管理员租户（CompanyID=200000231）或留空时系统将返回该地域全部可用类型

