# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeFlatNetworkRouteResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[FlatNetworkRoute]] = None  # 路由列表，返回的路由详细信息
    TotalCount: Optional[int] = None  # 总记录数，用于分页计算
