# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeImageRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    ImageFormat: Optional[str] = None  # 镜像格式，用于筛选镜像格式，取值qcow2、iso、vmdk、raw

    ImageIDs: Optional[List[str]] = None  # 镜像ID列表，用于精确筛选指定镜像集合

    ImageType: Optional[str] = None  # 镜像类型，用于筛选镜像类型，取值Base、Custom

    Keyword: Optional[str] = None  # 关键词，用于对镜像名称或备注进行模糊检索

    Limit: Optional[int] = None  # 分页记录数，用于限制单次返回条数

    Offset: Optional[int] = None  # 起始偏移量，用于指定返回结果集的起始位置

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于筛选自定义镜像所属项目，基础镜像不生效

    Status: Optional[List[str]] = None  # 状态列表，用于筛选指定状态的镜像资源

