# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeNetworkTopologyRequest:
    """"""

    Region: str  # 地域ID，指定要查询网络拓扑的地域

    CompanyID: Optional[int] = None  # 租户ID，指定要查询网络拓扑的租户，若不指定则查询所有租户

    DirectConnectIDs: Optional[List[str]] = None  # 专线ID列表，已弃用，参数无效

    FlatNetworkIDs: Optional[List[str]] = None  # 扁平网络ID列表，指定要查询的扁平网络范围

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，若不指定则默认为10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，指定要查询网络拓扑的项目组范围，ProjectID 采用 project- 前缀加14位随机字符格式

    ResourceIDs: Optional[List[str]] = None  # 资源ID列表，指定要查询网络拓扑的资源范围，每个ResourceID格式为类型前缀-14位随机字符

    ResourceTypes: Optional[List[str]] = None  # 资源类型列表，指定要查询网络拓扑的资源类型

    SegmentIDs: Optional[List[str]] = None  # 外网线路ID列表，指定要查询的外网线路范围

    SubnetIDs: Optional[List[str]] = None  # 子网ID列表，指定要查询的子网范围

    SubnetIPVersion: Optional[str] = None  # 子网查询情况下的IP协议版本，支持IPv4或IPv6，若不指定则查询所有协议

