# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeExternalStorageSetRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，筛选指定租户的外置存储集群资源

    Limit: Optional[int] = None  # 分页大小，默认10

    Offset: Optional[int] = None  # 分页偏移量，默认0

    Provisioner: Optional[str] = None  # 存储集群提供者，支持iscsi和fcsan，非fcsan按iscsi处理

