# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeVMHostResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[HostInfo]] = None  # 物理机信息列表，返回物理宿主机详细信息
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的物理机总数
