# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeVSRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Keyword: Optional[str] = None  # 搜索关键词，用于搜索虚拟服务器

    LBID: Optional[str] = None  # 负载均衡ID，用于定位需要查询的负载均衡实例

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量，取值范围：1-100，默认值：10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询，取值范围：≥0， 默认值：0

    Origin: Optional[str] = None  # 虚拟服务器来源，用于筛选监听器来源，取值范围：Default、Service、Ingress，空表示不筛选来源

    VSIDs: Optional[List[str]] = None  # 虚拟服务器ID列表，用于筛选指定虚拟服务器

