# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeBucketsRequest:
    """"""

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    BucketNames: Optional[List[str]] = None  # 桶名称列表，用于查询指定桶信息

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊匹配桶名称

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

