# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeVSPolicyRequest:
    """"""

    LBID: str  # 负载均衡ID，用于定位需要查询转发规则的负载均衡实例

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VSID: str  # 虚拟服务器ID，用于定位需要查询转发规则的监听器

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    PolicyIDs: Optional[List[str]] = None  # 转发规则ID列表，用于筛选指定转发规则

