# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeDBSStorageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[DBSStorageInfo]] = None  # 备份存储池列表，存储池信息列表
    TotalCount: Optional[int] = None  # 总数，查询得到的记录总数
