# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeVPCRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Keyword: Optional[str] = None  # 搜索关键词，用于按名称或备注模糊查询

    Limit: Optional[int] = None  # 分页大小，用于限制单次返回条数

    Offset: Optional[int] = None  # 分页偏移量，用于指定返回结果起始位置

    PeerID: Optional[str] = None  # 对端ID，用于筛选包含指定对等连接的VPC

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于按项目维度筛选资源

    VPCIDs: Optional[List[str]] = None  # VPCID列表，用于查询指定的虚拟私有网络

