# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeQuotaUsageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[QuotaUsage]] = None  # 配额使用情况列表
    TotalCount: Optional[int] = None  # 配额使用情况总数
