# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeDOSTokenResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[DOSToken]] = None  # 令牌列表，查询到的令牌信息
    TotalCount: Optional[int] = None  # 总数，查询到的令牌数量
