# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeVMWareVMsRequest:
    """"""

    ConfigName: str  # 配置名称，VMware配置标识

    Datacenter: str  # 数据中心，VMware数据中心标识

    Cluster: Optional[str] = None  # 集群名称，VMware集群标识

