# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeRecycledResourceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[RecycleResourceInfo]] = None  # 回收资源信息，回收站资源列表
    TotalCount: Optional[int] = None  # 总回收资源数量，满足条件的回收资源总数
