# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeSecurityGroupResourceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[SGResourceInfo]] = None  # 绑定资源详情列表，包含资源类型、ID、名称、网卡类型等信息
    TotalCount: Optional[int] = None  # 总记录数，用于分页计算
