# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeResourceUsersResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[int]] = None  # 租户ID列表，返回所有正在使用指定资源的租户唯一标识，按租户ID升序排列
    TotalCount: Optional[int] = None  # 租户总数，返回正在使用该资源的租户数量
