# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeOrderRequest:
    """"""

    BeginTime: int  # 查询起始时间，订单创建时间的起始时间戳，单位为秒，必须小于结束时间

    EndTime: int  # 查询结束时间，订单创建时间的结束时间戳，单位为秒，必须大于起始时间

    ProjectIDs: List[str]  # 项目组ID列表，保留字段，当前接口不会根据项目进行过滤

    Limit: Optional[int] = None  # 分页大小，指定每页返回的订单记录数量

    Offset: Optional[int] = None  # 分页偏移量，指定从第几条记录开始返回

    Region: Optional[str] = None  # 地域ID，指定订单资源所属的物理区域，传入all或空值表示查询所有地域的订单

    UserAccountID: Optional[int] = None  # 租户唯一标识ID，用于标识资源所属的租户，实现多租户环境下的资源隔离和权限控制，根据此租户ID查询所有订单

