# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeFSResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[FSInfo]] = None  # 文件存储信息列表，查询到的文件存储信息
    TotalCount: Optional[int] = None  # 总记录数，符合条件的文件存储数量
