# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeAlertRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，按告警中的company_id标签过滤，仅当告警携带company_id标签时才会命中

    Limit: Optional[int] = None  # 分页大小，逻辑上会在合并所有地域的告警并按活跃时间倒序排列后再进行分页，Limit为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，与Limit配合在合并后的告警列表中定位返回窗口

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，按project_id注解过滤自定义告警，告警未携带项目注解时不会返回

    Region: Optional[str] = None  # 地域，按告警的region标签进行过滤；为空时会遍历所有地域的Prometheus并合并自定义告警后再统一筛选

    Severities: Optional[List[str]] = None  # 告警级别列表，按severity标签过滤，取值：warning/critical/error；告警缺少severity标签时在设置该条件时会被过滤掉

    States: Optional[List[str]] = None  # 告警状态列表，按Prometheus Alert的状态过滤，取值：inactive/pending/firing

    TemplateTypes: Optional[List[str]] = None  # 告警模板类型列表，按resource_type标签过滤，可通过DescribeMetric获取常见取值；若告警缺少resource_type标签则不会命中

