# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeQuotaRequest:
    """"""

    Region: str  # 地域ID，指定要查询配额的地域，必须填写且需要具备该地域的访问权限

    CompanyID: Optional[int] = None  # 租户ID，指定要查询配额的租户，用于筛选指定租户的配额信息

    FactorTypes: Optional[List[str]] = None  # 配额因子列表，用于过滤特定计量维度的配额

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊搜索配额信息

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，取值范围1-100

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，从0开始计数

    ProductTypes: Optional[List[str]] = None  # 产品类型列表，用于过滤特定产品的配额

