# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeDTSTaskRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    DTSIDs: Optional[List[str]] = None  # DTS任务ID列表，用于精确查询指定的DTS任务

    Keyword: Optional[str] = None  # 搜索关键词，支持按任务名称模糊搜索DTS任务

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于筛选指定项目下的DTS任务

