# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeNodeNUMAInfoRequest:
    """"""

    Region: str  # 地域ID，用于查询NUMA信息的资源所属地域

    SetID: str  # 计算集群ID，用于指定查询NUMA信息的计算集群

