# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeNICRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    BindResourceID: Optional[str] = None  # 绑定的资源ID，用于查询绑定到指定资源的网卡

    CompanyID: Optional[int] = None  # 租户ID，指定查询范围内的租户组织，可选，用于跨租户查询

    Keyword: Optional[str] = None  # 关键词，用于模糊匹配网卡名称或ID

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    NICIDs: Optional[List[str]] = None  # 网卡ID列表，用于查询指定的网卡资源

    NICType: Optional[str] = None  # 网卡类型过滤，LAN表示从VPC内网分配，WAN表示从外网网段分配，Flat表示从扁平网络分配

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于查询指定项目下的网卡资源

    SegmentID: Optional[str] = None  # 外网线路ID过滤，用于查询指定线路的外网网卡

    Status: Optional[str] = None  # 状态过滤，查询指定状态的网卡

    SubnetID: Optional[str] = None  # 子网ID过滤，用于查询指定子网下的网卡

