# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeTrafficMirrorRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    Keyword: Optional[str] = None  # 关键字，用于搜索流量镜像名称或ID

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    Status: Optional[str] = None  # 资源状态，用于过滤特定状态的流量镜像

    TrafficMirrorIDs: Optional[List[str]] = None  # 流量镜像ID列表，指定要查询的流量镜像，若指定单个ID则返回详细信息（包含规则和源设备详情）

