# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeBindableTagResourceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[BindableTagResourceInfo]] = None  # 标签资源信息
    TotalCount: Optional[int] = None  # 总记录数
