# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeOrchTaskTypeResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[TaskTypeInfo]] = None  # 详情，任务类型列表
    TotalCount: Optional[int] = None  # 总数，任务类型总数
