# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeMemberRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，用于限定查询的租户范围

    Email: Optional[str] = None  # 账号邮箱，用于按邮箱筛选账号

    Keyword: Optional[str] = None  # 关键词，用于按名称或邮箱模糊检索

    Limit: Optional[int] = None  # 分页大小，控制单次返回数量

    MemberIDs: Optional[List[int]] = None  # 成员ID列表，筛选指定账号的查询条件，为空则不过滤

    MemberPubKey: Optional[str] = None  # 账号公钥，用于按公钥筛选账号

    Offset: Optional[int] = None  # 分页偏移量，用于分页起点

