# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeDirectConnectRequest:
    """"""

    Region: str  # 地域ID，指定查询专线接入所属的物理区域

    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离，若不指定则查询用户有权限访问的所有专线接入

    DirectConnectIDs: Optional[List[str]] = None  # 专线接入ID列表，用于精确查询指定的专线接入资源，支持批量查询

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊搜索专线接入的名称、描述等信息，长度不超过100个字符

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，取值范围：1-100，默认值：10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询，默认值：0

