# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeContainerImageRepositoryRequest:
    """"""

    Region: str  # 地域，镜像仓库所属地域

    CompanyID: Optional[int] = None  # 租户ID，用于筛选指定租户的私有仓库且必须与仓库所属租户一致；当 Public 设为 true 查询公有仓库时可不填

    Keyword: Optional[str] = None  # 关键词，按镜像仓库名称模糊搜索

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，用于过滤指定项目组的镜像仓库

    Public: Optional[bool] = None  # 是否只查询公有仓库，true 时忽略租户过滤并仅返回带有公有标记、所有租户都可拉取的仓库

