# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeRedisSlowlogRequest:
    """"""

    EndTime: int  # 结束时间，Unix时间戳（秒）

    RedisID: str  # Redis实例ID，指定要查询慢日志的实例；注意：资源必须为AVAILABLE且状态为Running，且至少存在Ready状态的VM

    Region: str  # 地域ID，实例所属地域

    StartTime: int  # 开始时间，Unix时间戳（秒）

    Keyword: Optional[str] = None  # 关键词，用于搜索慢日志记录

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，默认0

