# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeBucketLifecycleRulesRequest:
    """"""

    BucketName: str  # 桶名称，存储桶名称

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

