# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeResourceEventRequest:
    """"""

    BeginTime: Optional[int] = None  # 开始时间，Unix时间戳(秒)，查询该时间点之后发生的事件

    CompanyID: Optional[int] = None  # 租户ID，指定要查询资源事件的租户，若不指定则查询所有租户

    EndTime: Optional[int] = None  # 结束时间，Unix时间戳(秒)，查询该时间点之前发生的事件，必须大于开始时间

    EventTypes: Optional[List[str]] = None  # 事件类型列表，指定要查询的事件类型

    Levels: Optional[List[str]] = None  # 事件等级列表，指定要查询的事件严重程度，取值范围：Info、Warning、Error

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，若不指定则使用默认值

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，指定要查询事件的项目组范围，ProjectID 采用 project- 前缀加14位随机字符格式

    Region: Optional[str] = None  # 地域ID，指定要查询资源事件的地域

    ResourceIDs: Optional[List[str]] = None  # 资源ID列表，指定要查询事件的资源范围，每个ResourceID格式为类型前缀-14位随机字符

    ResourceTypes: Optional[List[str]] = None  # 资源类型列表，指定要查询事件的资源类型范围

