# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeTrafficMirrorSourcesRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    Keyword: Optional[str] = None  # 关键字，用于搜索虚拟机名称或ID

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

