# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeAlertNotifyWebhookResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[AlertNotifyWebhookInfo]] = None  # 详情，Webhook列表
    TotalCount: Optional[int] = None  # 总数，查询到的Webhook总数
