# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeLoginWhitelistResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[IAMLoginWhitelist]] = None  # 登录白名单详情列表，查询结果返回当前租户的登录IP白名单配置
