# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeTimerTaskResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[TaskInfo]] = None  # 任务执行记录列表
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的任务执行记录总数，用于分页计算
