# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeBucketLifecycleRulesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    BucketName: Optional[str] = None  # 桶名称，存储桶名称
    Infos: Optional[List[BucketLifecycleRule]] = None  # 生命周期规则列表，查询到的生命周期规则
    TotalCount: Optional[int] = None  # 总记录数，符合条件的生命周期规则数量
