# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeTenantResourcesRequest:
    """"""

    CompanyID: int  # 租户ID，请求传入并指定要查询资源的租户；租户资源查询场景使用

    Region: str  # 地域ID，请求传入并指定资源所属物理区域；租户资源查询场景使用

    Limit: Optional[int] = None  # 分页大小，请求传入用于控制返回记录数；列表分页场景使用；Limit为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，请求传入用于分页起始位置；列表分页场景使用；Offset为0表示从头开始

