# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeBaseImageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[BaseImageInfo]] = None  # 基础镜像详情列表，包含符合查询条件的镜像授权与属性信息
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的基础镜像资源总量
