# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeDiskRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的地域

    AttachResourceID: Optional[str] = None  # 挂载的资源ID，用于筛选已挂载到指定资源（目前仅支持虚拟机）的磁盘；指定后会先查询该资源绑定的磁盘并以其DiskIDs为筛选条件

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    DiskIDs: Optional[List[str]] = None  # 硬盘ID列表，用于查询指定磁盘信息

    DiskType: Optional[str] = None  # 硬盘类型（已废弃参数），保留向后兼容，传值时会自动转换为DiskTypes

    DiskTypes: Optional[List[str]] = None  # 硬盘类型列表，多值过滤字段，取值范围：Boot、Data、cdrom、SaveMem、BootImage

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊匹配磁盘名称或备注

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，用于筛选指定项目组下的磁盘资源

    SetIDs: Optional[List[str]] = None  # 存储集群ID列表，用于筛选指定存储集群下的磁盘资源

    ShareAbleFilter: Optional[str] = None  # 筛选共享盘，取值true（仅返回共享盘）或false（仅返回普通盘），空值表示返回所有类型

    Status: Optional[List[str]] = None  # 状态列表，用于筛选指定状态的磁盘资源

