# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeSetAllocateUsageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    MemoryUsageInfos: Optional[List[MemoryUsageInfo]] = None  # 内存使用情况列表
    StorageUsageInfos: Optional[List[StorageUsageInfo]] = None  # 存储使用情况列表
    VCPUUsageInfos: Optional[List[VCPUUsageInfo]] = None  # vCPU使用情况列表
