# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeVSResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[LbVSInfo]] = None  # 虚拟服务器详情列表
    TotalCount: Optional[int] = None  # 总记录数，用于分页计算
