# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeResourceEventResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[ResourceEventInfo]] = None  # 资源事件信息列表，包含符合条件的所有资源事件的详细信息
    TotalCount: Optional[int] = None  # 总数，符合条件的资源事件总数量
