# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeIsolationGroupsRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    IGIDs: Optional[List[str]] = None  # 隔离组ID列表，用于按ID筛选隔离组

    Keyword: Optional[str] = None  # 关键词，用于匹配隔离组名称或备注

    Limit: Optional[int] = None  # 分页大小，用于限制单次返回条数

    Offset: Optional[int] = None  # 分页偏移量，用于指定返回结果起始位置

    PolicyObj: Optional[str] = None  # 策略对象，用于筛选隔离组，PolicyToVG时为隔离组ID，PolicyToNode时为节点标识

    PolicyObjType: Optional[str] = None  # 策略对象类型，用于筛选隔离组，取值PolicyToNode/PolicyToVG

    PolicyType: Optional[str] = None  # 策略类型，用于筛选隔离组，取值VMAffinity/VMAntiAffinity

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于按项目筛选隔离组

    SetID: Optional[str] = None  # 计算集群ID，用于按计算集群筛选隔离组

    SetType: Optional[str] = None  # 计算集群类型，用于按类型筛选隔离组

