# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeCertificateRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CertificateIDs: Optional[List[str]] = None  # 证书ID列表，用于筛选指定证书，当Origin为Ingress时必填

    CertificateType: Optional[str] = None  # 证书类型，证书的类型，取值范围：ServerCrt、CACrt，空表示不筛选类型

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Keyword: Optional[str] = None  # 搜索关键词，用于搜索证书

    LBID: Optional[str] = None  # 负载均衡ID，用于筛选已绑定证书的负载均衡，当Origin为Ingress时必填

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    Origin: Optional[str] = None  # 证书来源，证书的来源，取值范围：Default、Ingress，空表示不筛选来源

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于筛选指定项目的证书

    VSID: Optional[str] = None  # 虚拟服务器ID，用于筛选已绑定证书的虚拟服务器，当Origin为Ingress时必填

