# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeSRIOVStateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    State: Optional[str] = None  # SR-IOV状态，取值Enabling、Disabling、Enabled或Disabled
