# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeComputeClassDRSRecordsRequest:
    """"""

    Region: str  # 地域ID

    SetID: str  # 计算集群ID，指定要查询的DRS记录所属ComputeClass

    BeginTime: Optional[int] = None  # 开始时间，秒级Unix时间戳，与EndTime一起限定任务创建时间区间，缺省表示不限制

    CompanyID: Optional[int] = None  # 租户ID

    EndTime: Optional[int] = None  # 结束时间，秒级Unix时间戳，需大于等于BeginTime，缺省表示不限制

    Keyword: Optional[str] = None  # 虚拟机ID关键字，非空时仅返回包含该关键字的虚拟机记录

    Limit: Optional[int] = None  # 分页大小，默认10

    Offset: Optional[int] = None  # 分页偏移量，默认0

