# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeEIPRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    BindResourceID: Optional[str] = None  # 绑定的资源ID，用于过滤已绑定到指定资源的EIP，支持查询VM绑定的普通EIP、弹性网卡EIP和VIP

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    EIPIDs: Optional[List[str]] = None  # EIP资源ID列表，用于过滤指定的EIP，若不指定则返回所有EIP

    IPStatus: Optional[str] = None  # EIP绑定状态，用于过滤指定状态的EIP，取值Bound/Bounding/Unbounding/Free等资源状态

    IPVersion: Optional[str] = None  # IP版本，用于过滤指定IP协议版本的EIP，取值IPv4/IPv6

    Keyword: Optional[str] = None  # 关键词，用于模糊搜索EIP名称、备注等字段

    Limit: Optional[int] = None  # 分页大小，用于限制单次返回条数

    Offset: Optional[int] = None  # 分页偏移量，用于指定返回结果起始位置

    OperatorName: Optional[str] = None  # 运营商网段名称，用于过滤指定网段的EIP

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于过滤指定项目下的EIP资源

