# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribePaaSInstanceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[PaaSInstance]] = None  # PaaS实例列表，默认返回绑定的所有虚拟机及其迁移状态；平台管理员可看到更多诊断字段
