# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeOSSRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    Filter: Optional[str] = None  # 过滤标志，如Filter=DBS时排除已被DBS备份绑定的对象存储

    Keyword: Optional[str] = None  # 搜索关键词，用于模糊匹配对象存储名称或备注

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，为0时默认10

    OSSIDs: Optional[List[str]] = None  # 对象存储ID列表，用于查询指定对象存储信息

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

    ProjectIDs: Optional[List[str]] = None  # 项目组ID列表，用于筛选指定项目组下的对象存储资源

    Region: Optional[str] = None  # 地域ID，指定资源所属的地域

    Status: Optional[List[str]] = None  # 对象存储状态列表，用于筛选指定状态的对象存储资源，取值与DescribeOSSResponse.Infos.Status一致（如Running、Stopped、Starting、Stopping、Upgrading、Changingpwd、Downgrading、Deleting、Failed、VersionUpgrading等）

    VpcIDs: Optional[List[str]] = None  # VPC ID列表，用于筛选指定VPC下的对象存储资源

