# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeVMHostRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    FilterRunnableHostsByVMID: Optional[str] = None  # 虚拟机ID，用于筛选可运行该虚拟机的宿主机

    HostIDs: Optional[List[str]] = None  # 物理机ID列表，用于精确筛选指定物理机

    Keyword: Optional[str] = None  # 关键词，用于模糊匹配主机名或IP地址

    Limit: Optional[int] = None  # 分页大小，用于限制单次返回条数

    Offset: Optional[int] = None  # 分页偏移量，用于指定返回结果起始位置

    SetID: Optional[str] = None  # 计算集群ID，用于筛选指定集群的物理机

