# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeAlertTemplateRuleRequest:
    """"""

    TemplateID: str  # 告警模板ID，查询指定模板下的规则，非管理员租户仅能查看自身模板

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，Limit为0时默认10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数

