# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeApplicationResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[WorkflowApplication]] = None  # 审批工单列表，包含审批的详细信息，当指定ApplicationID时，返回单个审批的完整信息（包含所有审批节点）
    TotalCount: Optional[int] = None  # 审批工单总数，用于分页显示
