# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeResourceChartRequest:
    """"""

    ResourceType: str  # 资源类型，指定要查询的资源图表类型，支持COMPUTE_SET(计算集群)、STORAGE_SET(存储集群)、REGION(地域)

    Region: Optional[str] = None  # 地域ID，指定要查询资源图表的地域，若不指定则查询所有有权限的地域

    ShowUserVMOnly: Optional[bool] = None  # 类型为 REGION 时, 是否只展示用户虚拟机；为 true 时仅统计用户 VM（过滤管理虚拟机），为 false 时包含所有虚拟机（过滤 sandbox）

