# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeRedisResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[RedisInfo]] = None  # Redis信息，实例信息列表
    TotalCount: Optional[int] = None  # 总数，查询得到的记录总数
