# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeTimerRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Keyword: Optional[str] = None  # 关键词，用于按定时器名称模糊搜索

    Limit: Optional[int] = None  # 分页大小，用于限制单次返回条数

    Offset: Optional[int] = None  # 分页偏移量，用于指定返回结果起始位置

    ProjectIDs: Optional[List[str]] = None  # 项目ID列表，用于筛选指定项目下的定时器

    Region: Optional[str] = None  # 地域ID，用于筛选定时器所属地域，为空时查询授权地域

    SetID: Optional[str] = None  # 集群ID，用于筛选PolicySetID匹配的定时器

    Task: Optional[str] = None  # 任务类型，用于筛选特定业务任务

    TimerIDs: Optional[List[str]] = None  # 定时器ID列表，用于精确查询指定定时器

    TimerStatus: Optional[List[str]] = None  # 定时器状态列表，取值Normal、Paused；为空时默认Normal

    Types: Optional[List[str]] = None  # 调度类型列表，用于筛选特定调度规则

