# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeVMCResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[VMCInfo]] = None  # VMC任务列表，包含满足条件的克隆任务详情
    TotalCount: Optional[int] = None  # 总记录数，返回满足查询条件的记录总数
