# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeMetricRequest:
    """"""

    Labels: Optional[List[str]] = None  # 过滤标签列表，仅返回同时包含所有指定标签的指标，弹性伸缩监控会通过horizontal_vm/horizontal_vs/vertical_vm/vertical_eip等标签区分不同模式

    Region: Optional[str] = None  # 地域，指定要访问的Prometheus及后台服务；当TargetTypes包含STORAGE_SET且传入TargetID时必须填写

    TargetID: Optional[str] = None  # 监控目标资源ID，需要与TargetTypes中的类型匹配，Handler会把该ID写入指标PromQL的resource_id（或特定标签）过滤条件，例如VM/COMPUTE_SET/REDIS等直接填资源ID，STORAGE_SET/FS/CLUSTER填SetID，OSD或对象存储需填SetID:子资源，VPNGW_TUNNEL填隧道ID，AS_GROUP填伸缩组ID等；为空时仅返回模板定义，不拼装资源级PromQL

    TargetInstanceID: Optional[str] = None  # 实例ID，PaaS多实例资源可通过该参数指定具体实例，仅在同时指定TargetID时生效

    TargetTypes: Optional[List[str]] = None  # 监控资源类型列表，限定需要返回的监控对象，支持类型（HOST/VM/COMPUTE_SET/STORAGE_SET/REGION/LB/LB_VSERVER/NATGW/VPNGW/VPNGW_TUNNEL/EIP/AS_GROUP/OSS/FS/REDIS/PM/MYSQL/DBS等）；为空时返回指标文件中启用了告警且当前租户已授权的所有资源类型

