# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeBillResourceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[BillResourceInfo]] = None  # 详情，资源账单信息列表
    TotalCount: Optional[int] = None  # 总数量，符合条件的记录总数
