# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeRegionRequest:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，用于查询指定租户授权的地域列表；条件互斥：CompanyID不为0时使用当前登录用户Company和Member作为目标；CompanyID为0且MemberID为0时返回当前用户可访问的全部地域

    MemberID: Optional[int] = None  # 管理员ID，用于查询指定管理员授权的地域列表；条件互斥：MemberID不为0时仅返回该管理员授权地域；CompanyID不为0时该字段被忽略

