# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeStorageSetSortPolicyRequest:
    """"""

    Region: str  # 地域ID，指定存储集群所属的物理区域

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，普通租户需填写自身CompanyID；管理员租户（CompanyID=200000231）或留空时按管理员权限查询

