# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeMySQLSlowLogRecordsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[SlowLogInfo]] = None  # 慢日志信息，慢查询日志记录列表
    TotalCount: Optional[int] = None  # 总数，查询得到的记录总数
