# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DescribeRSRequest:
    """"""

    LBID: str  # 负载均衡ID，用于定位需要查询服务节点的负载均衡实例

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VSID: str  # 虚拟服务器ID，用于定位需要查询服务节点的监听器实例

    BindResourceID: Optional[str] = None  # 绑定资源ID，真实服务器绑定的资源ID，仅支持虚拟机资源

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    Limit: Optional[int] = None  # 分页大小，指定每页返回的记录数，用于控制返回数据量，取值范围：1-100，默认值：10

    Offset: Optional[int] = None  # 分页偏移量，指定跳过的记录数，用于实现分页查询，取值范围：≥0， 默认值：0

    RSIDs: Optional[List[str]] = None  # 真实服务器ID列表，用于筛选指定服务节点

