# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeRedisConfigFileResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[RedisConfigFile]] = None  # 配置模板信息，模板信息列表
    TotalCount: Optional[int] = None  # 总数，查询得到的记录总数
