# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class DescribeAlertTemplateResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[AlertTemplateInfo]] = None  # 告警模板详细信息列表，告警模板列表，包含模板的完整配置信息
    TotalCount: Optional[int] = None  # 告警模板总数，满足查询条件的告警模板总数
