# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DetachExternalDiskRequest:
    """"""

    DiskID: str  # 磁盘ID，待解绑的外置存储盘资源ID

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceID: str  # 资源ID，解绑目标资源的ID

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户的权限上下文

    ResourceType: Optional[str] = None  # 资源类型，解绑目标资源的类型标识

