# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DetachUSBRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    USBDeviceID: str  # USB设备ID，指定要从虚拟机卸载的USB设备

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织

