# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DOSLoginRequest:
    """"""

    Bucket: str  # 桶名称，存储桶名称

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，用于校验对象存储资源的租户归属；公司级账号必须填写自身CompanyID，其它角色可不填或传0

