# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DowngradeOSSRequest:
    """"""

    OSSID: str  # 对象存储ID，要降配的对象存储标识，对象存储状态必须为Stopped

    Region: str  # 地域ID，指定资源所属的地域

    CPU: Optional[int] = None  # CPU核数，降配后的CPU核数需小于当前值，取值范围：2、4、6、8、10、12、14、16

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

