# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FlushBucketResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Count: Optional[int] = None  # 被清理的对象数量，清理掉的对象总数
