# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FreezeUserRequest:
    """"""

    CompanyID: int  # 租户ID，请求传入并定位要冻结的租户，用于冻结租户账号与资源操作场景

