# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FSLoginRequest:
    """"""

    FSID: str  # 文件存储实例ID，要登录的文件存储标识，资源状态必须为可用

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

