# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetDTSPriceRequest:
    """"""

    CPU: int  # CPU核数，用于指定DTS实例的CPU配置

    ChargeType: str  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR

    ComputeClass: str  # 计算集群类型，用于指定DTS实例运行的计算集群

    Count: int  # 购买数量，用于批量购买时指定购买的DTS实例数量

    Memory: int  # 内存大小，单位GB，用于指定DTS实例的内存配置

    Quantity: int  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，

    Region: str  # 地域ID，用于标识资源所属的地理区域

    StorageClass: str  # 存储集群类型，用于指定DTS实例系统盘所在存储集群

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    DTSID: Optional[str] = None  # DTS任务ID，用于计算升级配置时的费用差价；不指定则计算新购价格

