# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetPMHardwareV2Response:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    HardwareInfo: Optional[str] = None  # 硬件信息，包含CPU、内存、磁盘、网卡等硬件配置的JSON格式数据
    LastUpdateTime: Optional[int] = None  # 最后更新时间，硬件信息上次更新的Unix时间戳（秒）
