# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetNativeNodePriceRequest:
    """"""

    BootDiskSetType: str  # 系统盘集群ID

    BootDiskSpace: int  # 系统盘大小

    CPU: int  # CPU核数

    ComputeclassType: str  # 计算集群类型

    Count: int  # 数量

    Memory: int  # 内存大小

    Region: str  # 地域

    ClusterID: Optional[str] = None  # ClusterID

    CompanyID: Optional[int] = None  # 租户ID

    DataDiskSetType: Optional[str] = None  # 数据盘集群ID

    DataDiskSpace: Optional[int] = None  # 数据盘大小

