# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetLatestInstallConfigRequest:
    """"""

    MachineSN: str  # 机器序列号

    Region: str  # 地域

