# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetSubnetAvailableIPQuotaResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    AvailableCount: Optional[int] = None  # 主网段可用IP数量
    UsedCount: Optional[int] = None  # 主网段已用IP数量
