# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetPaymentOfPremiumRequest:
    """"""

    CPU: int  # 核心数，变更后的vCPU核心数量

    Memory: int  # 内存容量，变更后的内存大小，单位：MiB

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待变更配置的虚拟机标识

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    GPU: Optional[int] = None  # GPU数量，变更后的物理GPU数量，仅在GPUType为GPU时有效且必填

    GPUMdevName: Optional[str] = None  # GPU规格，变更后的物理GPU型号，仅在GPUType为GPU时有效且必填

    GPUType: Optional[str] = None  # GPU类型，变更后的GPU资源类型，取值：GPU、VGPU，暂未支持VGPU

    MdevName: Optional[str] = None  # vGPU规格，变更后的虚拟GPU规格，仅在GPUType为VGPU时有效且必填，预留字段，暂未支持

