# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetUpdateNICPriceRequest:
    """"""

    Bandwidth: int  # 带宽，单位Mbps，指定网卡的新带宽值

    NICID: str  # 网卡ID，指定要修改带宽的网卡资源，仅支持非Flat类型网卡

    Region: str  # 地域ID，用于标识资源所属的地理区域

    CompanyID: Optional[int] = None  # 租户ID，GetUpdateNICPrice接口中可选，用于权限校验

