# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class GetResourceUsageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[InspectionResourceUsageInfo]] = None  # 资源用量信息列表，包含详细的资源用量数据
    QueryCriteria: Optional[InspectionResourceUsageQueryCriteria] = None  # 查询条件，创建该资源用量报告时指定的查询参数
    ResourceUsageID: Optional[str] = None  # 资源用量ID
    TotalCount: Optional[int] = None  # 总数，资源用量信息的总数量
