# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetBMCTypeRequest:
    """"""

    Name: str  # BMC类型名称

    Region: str  # 地域

