# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetFilterKeywordsRequest:
    """"""

    Region: str  # 地域ID，指定要查询筛选关键字的地域

