# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class GetFilterKeywordsResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    BillPriceGroupInfo: Optional[BillPriceGroupInfo] = None  # 价格筛选关键字，包含可用的产品ID和集群类型
    QuotaInfo: Optional[QuotaInfo] = None  # 配额筛选关键字，包含可用的产品类型和配额因子
    SpecificationInfo: Optional[SpecificationInfo] = None  # 规格筛选关键字，包含可用的产品类型和集群类型
