# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetOSMediaV2Request:
    """"""

    MediaID: str  # 系统镜像ID

    Region: str  # 地域

