# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetPriceRequest:
    """"""

    ChargeType: str  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR

    Count: int  # 购买数量，需要购买的VPN网关数量，用于批量询价

    Quantity: int  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMType: str  # 计算集群类型，用于指定VPN网关虚拟机运行的计算集群，影响价格计算

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    HighAvailability: Optional[str] = None  # 高可用模式，VPN网关高可用配置方式，影响价格计算，ActiveStandy为主备高可用（2个实例），Standalone为单机（1个实例），若不指定则默认为ActiveStandy

    VPNGWID: Optional[str] = None  # VPN网关ID，若指定则按该网关规格查询续费或升级价格，若不指定则查询新购价格

