# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class GetMySQLPriceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[MysqlPriceInfo]] = None  # 价格信息，计费价格列表
