# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetEIPDiffPriceRequest:
    """"""

    Bandwidth: int  # 带宽，单位为Mbps，用于计算升级或降级带宽后的价格差异，取值范围由线路规格配置确定，默认为1-20000

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    EIPID: str  # EIP资源ID，要查询价格差异的弹性IP唯一标识符

    Region: str  # 地域ID，用于标识资源所属的地理区域

