# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetMigratePaaSStoragePriceRequest:
    """"""

    CompanyID: int  # 租户ID，保留字段

    InstanceID: str  # 实例ID，指定要评估存储迁移费用的虚拟机，必须属于该PaaS资源

    MigrateStorageSetID: str  # 目标存储集群ID，后台会验证集群存在且合法

    Region: str  # 地域ID，指定资源所属地域

    ResourceID: str  # PaaS资源ID，需处于AVAILABLE状态，且仅支持发起存储迁移的资源类型（MYSQL、REDIS、FS、OSS、DTS等）

