# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetLBPriceRequest:
    """"""

    ChargeType: str  # 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMType: str  # 计算集群类型，用于指定负载均衡运行的计算集群

    CPU: Optional[int] = None  # CPU核数，用于指定负载均衡计费规格的CPU配置

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

    HighAvailability: Optional[str] = None  # 高可用模式，用于指定负载均衡计费规格的高可用配置方式

    LBID: Optional[str] = None  # 负载均衡ID，用于标识需要计价的负载均衡实例

    Quantity: Optional[int] = None  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1，

    Specification: Optional[str] = None  # 规格，用于指定负载均衡计费规格

