# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetDiskPriceRequest:
    """"""

    ChargeType: str  # 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR

    Count: int  # 磁盘数量，用于价格计算

    DiskSpace: int  # 磁盘大小，单位GiB，用于价格计算

    Quantity: int  # 计费数量，用于指定购买时长的数量，按月/年计费时表示购买的月/年数，按小时计费时默认为1

    Region: str  # 地域ID，指定资源所属的地域

    SetType: str  # 存储集群类型，指定磁盘所属的存储集群

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

