# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class GetRoleRequest:
    """"""

    RoleID: str  # 角色ID，用于查询角色详情

