# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ImportImageResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Bucket: Optional[str] = None  # 目标存储桶，镜像数据存放的S3存储桶名称，当前固定为mirror
    ImageID: Optional[str] = None  # 镜像ID，导入完成后生成的镜像标识
    UploadID: Optional[str] = None  # 上传ID，本地分片上传任务的识别编号，仅Local模式有效
