# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListAllocatedIPsInSubnetRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    SubnetID: str  # 子网ID，用于查询该子网已分配IP

    OnlyCount: Optional[bool] = None  # 是否仅返回IP数量，true时仅返回AllocatedIPCount

