# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListInstallProfilesRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    IDs: Optional[List[str]] = None  # 模板ID列表过滤

    Keyword: Optional[str] = None  # 关键词搜索，按模板名称进行模糊匹配

    Limit: Optional[int] = None  # 每页数量，指定每页返回记录数，默认20，最大100

    Offset: Optional[int] = None  # 偏移量，指定跳过记录数，最小值为0

