# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListProductTypeCompanysRequest:
    """"""

    Enabled: str  # 启用状态，填N表示关闭，其他值表示启用

    ProductType: str  # 产品类型，标识云产品的服务类型

    Region: str  # 地域ID，指定产品服务所属的物理区域

    Limit: Optional[int] = None  # 分页大小，控制单次返回数量

    Offset: Optional[int] = None  # 分页偏移量，用于分页起点

