# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class ListBMCTypesResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Infos: Optional[List[BMCType]] = None  # BMC类型列表
    TotalCount: Optional[int] = None  # 总数
