# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListAdminRequest:
    """"""

    Keyword: Optional[str] = None  # 关键词，用于按名称或邮箱检索管理员账号

    Limit: Optional[int] = None  # 分页大小，控制单次返回数量

    Offset: Optional[int] = None  # 分页偏移量，用于分页起点，默认为0

