# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListRegionConfigsRequest:
    """"""

    ConfigType: str  # 配置类型，用于筛选地域配置的分类

    Region: str  # 地域ID，指定要查询配置的地域

