# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ListKickstartTemplatesRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    Keyword: Optional[str] = None  # 关键词搜索，支持按模板名称、OSDistribution 进行关键词搜索

    Limit: Optional[int] = None  # 每页数量，指定每页返回的记录数，默认值为10，最大值为100

    OSDistribution: Optional[str] = None  # 操作系统发行版，支持模糊匹配，如：CentOS、Rocky、Ubuntu、OpenEuler等

    Offset: Optional[int] = None  # 偏移量，指定跳过的记录数，最小值为0

