# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MigrateStorageBandWidthRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待调整带宽的虚拟机标识

    Bandwidth: Optional[int] = None  # 迁移带宽，限制迁移速率，单位：MiB/s

    DstSetID: Optional[str] = None  # 目标存储集群ID，无Infos参数时必填

    Infos: Optional[List[str]] = None  # 磁盘迁移详情，格式：原盘ID|目标集群ID|目标盘ID|带宽，会覆盖Bandwidth和DstSetID

