# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MigrateVMStorageRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    Infos: List[str]  # 磁盘迁移信息，格式：原盘ID|目标集群ID|目标盘ID，目标盘ID可为空（自动创建）

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待迁移存储的虚拟机标识

    ChargeType: Optional[str] = None  # 计费类型，新磁盘的计费模式，取值：Dynamic、Month、Year

    Quantity: Optional[int] = None  # 计费周期，购买的时长，按月/年计费时表示月数/年数

    ReserveOriginDisk: Optional[bool] = None  # 保留原盘，标识迁移后是否保留源磁盘

