# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ModifyNameAndRemarkRequest:
    """"""

    Name: str  # 资源名称，请求传入并更新资源显示名称，用于展示资源信息，长度为1-30个字符，只能包含中英文、数字、点、下划线和中划线

    Region: str  # 地域ID，请求传入并定位资源所属地域

    ResourceID: str  # 资源ID，请求传入并定位要修改名称或备注的资源

    Remark: Optional[str] = None  # 备注，请求传入并更新资源说明信息，可用于备注用途或状态，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，

