# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MoveProjectResourceRequest:
    """"""

    CompanyID: int  # 租户ID，用于标识资源所属租户并进行权限校验

    ProjectID: str  # 项目组ID，用于指定资源迁移后的目标项目

    ResourceIDs: List[str]  # 资源ID列表，用于指定需要迁移的资源集合

