# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PreviewKickstartTemplateRequest:
    """"""

    Name: str  # 模板名称

    Region: str  # 地域

    Config: Optional[str] = None  # 结构化安装参数(JSON String)

    MediaID: Optional[str] = None  # 系统镜像ID，用于生成正确的安装源URL，当Config去除空白后非空时必填

    Variables: Optional[str] = None  # 模板变量(JSON String)

