# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PrometheusQueryRangeRequest:
    """"""

    End: str  # 查询结束时间，定义时间范围的结束点，支持Unix时间戳（秒）或RFC3339格式，解析失败会直接返回错误

    Query: str  # PromQL查询表达式，用于查询时间范围内的监控指标数据，必须是合法的PromQL语法

    Region: str  # 地域ID，指定查询哪个地域的Prometheus监控数据；若地域不存在将返回StatusRegionNotExist错误

    Start: str  # 查询开始时间，定义时间范围的起始点，支持Unix时间戳（秒）或RFC3339格式，解析失败会直接返回错误

    Step: str  # 查询步长，定义返回数据点之间的时间间隔，支持数字（秒）或Go duration格式（如60、60s），无法解析时会直接返回错误

    Limit: Optional[int] = None  # 返回结果数量限制，用于限制返回的时间序列数据点数量，避免结果集过大，预留字段，当前实现未对Prometheus返回结果做截断

    Timeout: Optional[str] = None  # 查询超时时间，用于控制单次查询的最大执行时间，支持Go duration格式（如30s、1m），若解析失败、<=0或超过2m将返回参数错误

