# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RecoverPaaSConfigRequest:
    """"""

    Region: str  # 地域ID，指定资源所属地域，用于调用对应的资源服务

    ResourceID: str  # 资源ID，指定要恢复配置的PaaS资源，仅支持MYSQL/REDIS/OSS/FS四类资源。默认要求资源处于AVAILABLE且hhpaas状态为Config_Mismatch；对于带 legacy 标记且尚未 normalized 的 Running 状态 MySQL，也允许执行恢复配置

