# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ReleaseVIPRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VIPID: str  # VIPID，VIP的唯一标识符

