# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RemoveASMemberRequest:
    """"""

    GroupID: str  # 伸缩组ID，要移除成员的伸缩组唯一标识符，仅支持VM类型的伸缩组

    Region: str  # 地域ID，指定伸缩组所属的物理区域

    ResourceID: str  # 虚拟机ID，要从伸缩组移除的虚拟机实例ID，虚拟机必须是伸缩组的有效成员

    CompanyID: Optional[int] = None  # 租户唯一标识ID，伸缩组所属租户，普通调用无需显式填写，系统会根据伸缩组记录自动补充

