# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RenameRoleRequest:
    """"""

    Name: str  # 角色名称，用于更新角色显示名称，长度为1-50个字符，只能包含中英文、数字、点、下划线和中划线

    RoleID: str  # 角色ID，用于指定要重命名的角色

    Remark: Optional[str] = None  # 备注，用于补充说明角色用途和权限范围，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，

