# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RenewResourceResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    TransactonNo: Optional[str] = None  # 交易号，续费成功后生成的交易唯一标识，可用于后续查询交易记录
