# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RollbackResourceRequest:
    """"""

    Region: str  # 地域ID，资源所属的物理区域

    ResourceID: str  # 资源ID，待从回收站恢复的资源ID

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户的权限上下文

    ProjectID: Optional[str] = None  # 项目ID，资源所属项目，当前不影响恢复逻辑

