# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SetResourceTagsRequest:
    """"""

    CompanyID: int  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离，普通租户需填写自身CompanyID；当CompanyID=200000231（系统管理员租户）时仅能操作SEGMENT/DIRECTCONNECT/FLATNETWORK/TRAFFICMIRROR等运维资源

    KeyValuePairs: List[str]  # 标签键值对列表，格式为key:value（均为Base64编码），此操作会先清空资源的所有标签，然后按列表重新绑定；留空表示清空全部标签，键和值会在解码后校验非空且键名不可重复（tagutils.ParseKeyValuePairs），批量上限50个

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceID: str  # 资源ID，指定要设置标签的目标资源，资源必须满足：1）属于指定租户（StatusResourceNotBelongsToTenant）；2）状态为可用（StatusResourceStatusInvalid）；3）资源存在（StatusResourceNotExist）；4）资源类型匹配（StatusParamInvalid），设置操作会替换资源的所有标签，绑定时会自动检查标签是否存在（StatusTagNotFound）

    ResourceType: str  # 资源类型，标识要设置标签的资源种类，支持包括DISK、VM等多种资源类型，无效类型返回StatusResourceTypeInvalid，类型与资源ID不匹配返回StatusParamInvalid

