# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SetComputeClassDRSRequest:
    """"""

    Region: str  # 地域ID，指定请求操作的物理区域，用于路由到对应的Huanghe集群

    SetID: str  # 计算集群ID，指定要配置DRS策略的ComputeClass

    AutoMigrate: Optional[bool] = None  # 是否自动迁移，为true时DRS会在满足条件后直接迁移，为false仅生成建议供人工确认

    CompanyID: Optional[int] = None  # 租户ID，用于按租户隔离DRS配置与权限，非空时按租户过滤返回数据

    Cron: Optional[str] = None  # DRS执行Cron表达式，采用标准5字段格式（分 时 日 月 周），如0 2 * * * 表示每日02:00触发

    FinishTime: Optional[int] = None  # DRS周期结束时间，秒级Unix时间戳，需大于StartTime，不填表示长期生效

    MaxJobKeep: Optional[int] = None  # 历史保留批次，控制最多保留的DRS任务记录数量，0表示沿用默认10个

    MaxMigratableVMCPU: Optional[int] = None  # 最大可迁出虚拟机CPU核数，限制单个任务迁移的最大vCPU数量，0表示沿用默认16核

    MaxMigratableVMMemory: Optional[int] = None  # 最大可迁出虚拟机内存容量，限制单个任务迁移的最大内存，单位GiB，0表示沿用默认32GiB

    NodeHealthScore: Optional[int] = None  # 节点健康阈值，取值0-100，0表示沿用默认80，DRS会对低于阈值的节点触发均衡

    StartTime: Optional[int] = None  # DRS周期开启时间，秒级Unix时间戳，不填表示立即生效

    Suspend: Optional[bool] = None  # DRS是否暂停，为true时仅保留配置不再触发巡检

    VMMigrationPolicy: Optional[str] = None  # 虚拟机迁出排序策略，按资源占用排序迁移，支持FromLarge（大优先）、FromMedium（中位数优先）、FromSmall（小优先），空值默认为FromMedium

