# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class SMCHeartbeatResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Bandwidth: Optional[int] = None  # 带宽限速，单位Mbps，0表示不限速
    Checksum: Optional[bool] = None  # 是否启用校验和验证，确保数据完整性
    CompressLevel: Optional[bool] = None  # 是否启用压缩传输，节省网络带宽
    DiskMappings: Optional[List[DiskMapping]] = None  # 磁盘映射关系列表，仅包含已配置MappingDiskID的磁盘信息
    Host: Optional[str] = None  # 传输IP地址，目标VM的内网IP，用于SSH数据传输
    Password: Optional[str] = None  # 目标虚拟机SSH密码，已使用AES-ECB加密存储，使用VMID作为密钥
    Port: Optional[int] = None  # 传输端口，固定为22（SSH协议）
    SMCID: Optional[str] = None  # SMC任务唯一标识ID
    State: Optional[str] = None  # 当前任务状态，由任务引擎根据迁移进度返回
    User: Optional[str] = None  # 目标虚拟机SSH用户名，用于数据传输认证
    VMID: Optional[str] = None  # 目标传输虚拟机ID，接收迁移数据的目标VM
    WholeFile: Optional[bool] = None  # 是否传输全量文件，否则仅传输增量部分
