# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StartDTSTaskRequest:
    """"""

    DTSID: str  # DTS任务ID，待启动的DTS任务唯一标识

    Region: str  # 地域ID，用于标识资源所属的地理区域

