# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StartPaaSInstanceRequest:
    """"""

    ProductType: str  # 产品类型，取值范围与StopPaaSInstance一致；当类型为LB时，开机完成后会自动恢复绑定的弹性伸缩组配置

    Region: str  # 地域ID，指定资源所属地域，用于获取相应的黄河服务

    ResourceID: str  # 资源ID，指定要开启的PaaS资源，仅支持MYSQL/REDIS/OSS/FS/LB/NATGW/VPNGW

