# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StopPaaSInstanceRequest:
    """"""

    ProductType: str  # 产品类型，限定可关机的资源范围，取值：MYSQL/REDIS/OSS/FS/LB/NATGW/VPNGW；若资源与类型不匹配或类型未在列表中将返回错误

    Region: str  # 地域ID，指定资源所属地域，用于定位对应的黄河区域

    ResourceID: str  # 资源ID，指定要关机的PaaS资源，仅支持MYSQL/REDIS/OSS/FS/LB/NATGW/VPNGW几类资源，且资源状态必须为AVAILABLE

