# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TestBMCTypeRequest:
    """"""

    IPMIIP: str  # IPMI IP地址

    IPMIPassword: str  # IPMI密码

    IPMIUsername: str  # IPMI用户名

    Name: str  # BMC类型名称

    Region: str  # 地域

    StepByStep: Optional[str] = None  # 是否分步骤测试, true, false

    StepIndex: Optional[int] = None  # 步骤索引, 从 0 开始 (StepByStep为true时必填)

