# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnBindTagRequest:
    """"""

    CompanyID: int  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离

    Keys: List[str]  # 标签键名列表，指定要解绑的标签键，支持批量解绑多个标签键，解绑操作会删除资源与标签的绑定关系，但不会删除标签定义本身

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceIDs: List[str]  # 待解绑资源ID列表，支持批量从多个资源解绑标签

