# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnBindEIPRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    EIPID: str  # EIP资源ID，弹性IP的唯一标识符

    Region: str  # 地域ID，用于标识资源所属的地理区域

    ResourceID: str  # 资源ID，要解绑EIP的资源唯一标识符

    ResourceType: str  # 资源类型，指定EIP绑定的资源类型，取值VM/NATGW/VPNGW/LB/K8S/DTS/OSS/FS/MYSQL/REDIS

