# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UnFreezeSubMemberRequest:
    """"""

    MemberID: int  # 成员ID，解冻目标账号的唯一标识

