# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateDBSBackupPlanRequest:
    """"""

    BackupType: str  # 备份类型，取值Logical/Physical/Snapshot/Incremental

    Name: str  # 名称，备份计划名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    PlanID: str  # 计划ID，待更新的备份计划ID

    RetentionTime: int  # 保留时间，备份保留时长

    ScheduleType: str  # 调度类型，取值Manual或Timer

    SrcResourceID: str  # 源资源ID，备份源资源ID

    SrcResourceRegion: str  # 源数据地域，备份源资源所属地域

    SrcResourceType: str  # 源数据类型，备份源资源类型

    BackupTables: Optional[str] = None  # 备份库表，备份库表范围，格式为db.table用逗号分隔，MySQL逻辑备份需为*.*

    CompanyID: Optional[int] = None  # 租户ID，备份计划所属租户

    IncrementalInterval: Optional[int] = None  # 增量备份间隔，单位分钟，增量备份更新时必填，且必须≥5分钟

    Remark: Optional[str] = None  # 备注，备份计划描述信息，长度0-100字符，禁止http://或https://等非法字符

    StorageID: Optional[str] = None  # 存储系统ID，备份存储池ID；备份类型为Snapshot时可为空

    TimerDays: Optional[List[int]] = None  # 执行日期，TimerType为TIMER_TYPE_MONTHLY时必填

    TimerHours: Optional[List[int]] = None  # 执行小时，TimerType为TIMER_TYPE_DAILY/TIMER_TYPE_WEEKLY/TIMER_TYPE_MONTHLY时必填

    TimerType: Optional[str] = None  # 定时器类型，ScheduleType为Timer时必填

    TimerWeeks: Optional[List[int]] = None  # 执行星期，TimerType为TIMER_TYPE_WEEKLY时必填

