# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateTerminationPolicyRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围，用于验证资源归属

    Region: str  # 地域ID，指定资源所属的物理区域，用于验证资源归属

    ResourceID: str  # 资源ID，指定要修改删除保护策略的PaaS产品资源，如MySQL主库实例

    SlaveIDs: List[str]  # 从库ID列表，可同时下发给最多5个从库（后台直接遍历Patch资源注解，不做额外校验），为空表示仅修改主库

    TerminationPolicy: Optional[int] = None  # 删除保护策略，0表示开启删除保护，1表示关闭删除保护

