# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateAlertTemplateRuleRequest:
    """"""

    ConditionType: str  # 条件类型，告警触发比较方式，取值：GE/LE/ET/NE/LT/GT

    ForSeconds: int  # 持续时间，超过阈值需持续的秒数才触发告警

    Metric: str  # 监控指标名称，必须是合法的Prometheus指标名，且不能包含大括号

    NotifyGroupID: str  # 通知组ID，告警触发通知目标组ID；若规则所属模板为REGION类型，则此字段对管理员不可修改

    Query: str  # PromQL查询表达式，必须是合法的Prometheus查询语法

    RuleID: str  # 告警规则ID，待更新的规则ID，非管理员租户需验证规则所属模板的归属权限

    Severity: str  # 告警级别，定义告警严重程度，取值：warning/critical/error

    Summary: str  # 告警摘要，描述告警的触发条件和意义，将在告警通知中展示

    Thresholds: float  # 告警阈值，触发告警的指标值

