# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateSGFromLBRequest:
    """"""

    NICType: str  # 网络类型，指定安全组绑定的网卡类型，仅支持WAN，且需与负载均衡类型一致

    Region: str  # 地域ID，用于标识资源所属的地理区域

    ResourceID: str  # 负载均衡ID，用于定位需要更新安全组的负载均衡实例

    SGID: str  # 安全组ID，用于更新负载均衡绑定的安全组

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

