# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateResourceEventNotifyRuleRequest:
    """"""

    MonitorLevel: List[str]  # 监控级别列表，取值：info/warning/error

    MonitorModule: List[str]  # 监控模块列表，指定监控哪些资源模块的事件

    MonitorRegion: str  # 监控地域，指定监控地域的资源事件

    NotifyGroupID: str  # 通知组ID，资源事件通知规则所属通知组ID

    RuleID: str  # 规则ID，资源事件通知规则ID

