# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMOSRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    OSDistribution: Optional[str] = None  # 操作系统发行版，标识操作系统的具体家族

    OSType: Optional[str] = None  # 操作系统类型，标识操作系统的核心分类

    OSVersion: Optional[str] = None  # 操作系统版本，标识发行版内部的具体版本信息

