# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateNodeCPUGovernorRequest:
    """"""

    Governor: str  # 电源模式，取值performance（性能）、powersave（节能）、ondemand（自动，部分机器不支持）

    HostID: str  # 节点ID，用于标识节点唯一标识

    Region: str  # 地域ID，用于标识资源所属的地理区域

