# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateNativeNodeWANRequest:
    """"""

    ClusterID: str  # 集群Id

    NodeName: str  # 节点名称

    Region: str  # 地域

    CompanyID: Optional[int] = None  # 租户ID

    EIPID: Optional[str] = None  # EIP

    SGID: Optional[str] = None  # 安全组

