# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateResourceTemplateRequest:
    """"""

    CompanyID: int  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，必须与模板所属租户一致

    Content: str  # 模板内容，JSON字符串格式，等同于相应资源的创建接口入参，若模板已绑定弹性伸缩组则不允许修改VPCID；Content中的ProjectID必须为有效项目ID

    Region: str  # 地域ID，用于标识资源所属的地理区域

    TemplateID: str  # 模板ID，要更新的模板唯一标识

