# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMDefaultGWRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待修改网关的虚拟机资源标识

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

    EIPID: Optional[str] = None  # 弹性IPID，指定新的默认网关出口EIP，建议优先使用IPID

    IPID: Optional[str] = None  # IPID，指定新的默认网关出口IP

