# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdatePartitionTemplateRequest:
    """"""

    ID: str  # 模板ID

    Region: str  # 地域

    Config: Optional[str] = None  # 分区配置

    Description: Optional[str] = None  # 模板描述

    IsDefault: Optional[str] = None  # 是否默认

    Name: Optional[str] = None  # 模板名称

