# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateDiskQoSRequest:
    """"""

    DiskID: str  # 磁盘ID，要更新QoS配置的磁盘标识

    Region: str  # 地域ID，指定资源所属的地域

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户标识

    DiskBandwidth: Optional[int] = None  # 硬盘带宽限制，单位MBps，取值范围0-1000，0表示不限制

    DiskIOPS: Optional[int] = None  # 硬盘IOPS限制，取值范围0-50000，0表示不限制

