# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdatePortGroupRequest:
    """"""

    PortGroupID: str  # 端口组ID，指定要更新的端口组唯一标识符

    Region: str  # 地域ID，用于标识端口组所属的地理区域

    Rules: str  # 端口组规则，新的协议端口组合列表，将替换现有规则，格式为协议:端口或协议:端口范围，多条规则以逗号分隔

    CompanyID: Optional[int] = None  # 租户ID，标识端口组所属的租户组织，用于多租户资源隔离与权限控制

