# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateProductSpecificationRequest:
    """"""

    Region: str  # 地域ID，指定规格所属地域

    SpecificationID: str  # 规格ID，要更新的产品规格唯一标识符

    Value: str  # 规格值，要设置的新规格值，需符合规格模板定义的格式要求

