# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateAlertNotifyWebhookRequest:
    """"""

    Method: str  # HTTP请求方法类型，取值：GET/POST

    Name: str  # 名称，Webhook名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    NotifyWebhookID: str  # Webhook通知规则的ID，待更新的Webhook ID

    Url: str  # URL链接，Webhook目标URL

