# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdatePMV2Request:
    """"""

    PMID: str  # 裸金属ID，指定要更新的裸金属实例

    Region: str  # 地域ID，指定资源所属的物理区域

    BMCTypeName: Optional[str] = None  # BMC类型名称，标识硬件厂商的BMC类型，可选

    CustomMetricsPath: Optional[str] = None  # 自定义监控地址，用于Prometheus等监控系统采集指标，可选

    IPMIIP: Optional[str] = None  # IPMI管理IP地址，用于带外管理访问，可选

    IPMIPassword: Optional[str] = None  # IPMI密码，用于IPMI身份验证，可选

    IPMIUsername: Optional[str] = None  # IPMI用户名，用于IPMI身份验证，可选

    Manufacturer: Optional[str] = None  # 生产厂商，从BMC/IPMI FRU信息采集，可选

    Name: Optional[str] = None  # 资源名称，长度为1-128个字符，名称只能包含中英文、数字、点（.）、下划线（_）和中划线（-），可选，若不指定则不更新

    ProductName: Optional[str] = None  # 产品名称，从BMC/IPMI FRU信息采集，可选

    RackLocation: Optional[str] = None  # 机架位置，标识裸金属在数据中心的物理位置，可选

    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，可选，若不指定则不更新

