# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateLBAccessLogForLiveResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    WebSocketURL: Optional[str] = None  # WebSocket会话ID，仅当Switch为On时返回，调用方需将该ID拼接为ws://{host}/logconsole?session={ID}以建立实时日志连接
