# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateDBSBackupPlanSimpleRequest:
    """"""

    Name: str  # 名称，备份计划名称，长度1-128字符，支持中英文、数字、点、下划线和中划线

    PlanID: str  # 计划ID，待更新的备份计划ID

    Remark: Optional[str] = None  # 备注，备份计划描述信息，长度0-100字符，禁止http://或https://等非法字符

