# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateClusterRequest:
    """"""

    ClusterID: str  # 集群Id

    PodSubnetIDs: List[str]  # Pod子网Id 列表

    Region: str  # Region

    CompanyID: Optional[int] = None  # 租户ID

