# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMBootBootLoaderTypeRequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID，待修改配置的虚拟机标识

    BootloaderType: Optional[str] = None  # 引导方式，虚拟机的系统引导协议，取值：bios、uefi

