# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateVMNICLinkStateRequest:
    """"""

    LinkState: str  # 启用状态，可选值：up，down

    NICID: str  # 网卡ID

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VMID: str  # 虚拟机ID

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围

