# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateRolePermissionRequest:
    """"""

    Permission: str  # 角色权限，指定需要变更的Action名称

    RoleID: str  # 角色ID，用于唯一标识角色

    IsPermission: Optional[int] = None  # 是否开启权限，0表示关闭，'1','Y','Yes','YES','True','true'表示开启

