# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateBucketObjectLockRequest:
    """"""

    Days: int  # 锁定天数，设置对象锁定天数

    Name: str  # 桶名称，存储桶名称

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

