# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateResourcePermissionRequest:
    """"""

    Region: str  # 地域ID，指定资源所属的物理区域

    ResourceID: str  # 资源ID，指定要修改权限的资源唯一标识

    ResourceType: str  # 资源类型，指定资源的类型，支持COMPUTE_SET、STORAGE_SET、BASE_IMAGE、SEGMENT、DC（DirectConnect专线）、FLATNETWORK（扁平网络），用于确定资源的类别

    Permission: Optional[str] = None  # 权限配置，当PermissionMode为whitelist或blacklist时，传入以逗号分隔的租户ID列表（如1001,1002,1003）

    PermissionMode: Optional[str] = None  # 权限模式，控制租户访问权限的模式，可选值：all（所有租户可用，默认值）、whitelist（白名单，仅指定租户可用）、blacklist（黑名单，仅指定租户不可用）

