# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateBucketVersioningRequest:
    """"""

    Name: str  # 桶名称，存储桶名称

    OSSID: str  # 对象存储ID，对象存储实例标识

    Region: str  # 地域ID，指定资源所属的地域

    Enabled: Optional[bool] = None  # 是否启用，多版本开关状态

