# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateRegionConfigRequest:
    """"""

    ConfigKey: str  # 配置键，要更新的地域配置项唯一标识符，

    Region: str  # 地域ID，指定要更新配置的地域

    ConfigValue: Optional[str] = None  # 配置值，要设置的新配置值，ConfigKey为VPCNetwork时，需为有效的VPC网段（CIDR格式）

