# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpdateSRIOVStateRequest:
    """"""

    NodeID: str  # 节点ID，用于指定需要启用或禁用SR-IOV的节点

    PCIAddress: str  # 网卡PCI地址，用于指定需要操作的物理网卡

    Region: str  # 地域ID，用于标识资源所属的地理区域

    State: str  # 目标状态，取值Enable或Disable

