# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpgradeMySQLRequest:
    """"""

    CompanyID: int  # 租户ID，资源所属租户

    DiskSpace: int  # 目标存储容量，单位：GiB，最小值为10GB，升级限制：不能小于当前磁盘容量；若存在从库，从库磁盘必须先升级到大于等于此规格；若无变更则该项不生效

    Memory: int  # 目标内存大小，单位：MiB，必须是1024的倍数，升级限制：不能小于当前内存；AARCH64架构不支持热升级，实例必须先停止；若无变更则该项不生效

    MySQLID: str  # MySQL实例ID，指定要升级的MySQL实例；注意：资源必须为AVAILABLE，存在从库时需先将从库规格升级到不小于目标规格

    Region: str  # 地域ID，指定资源所属的物理区域

