# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UpgradeVPNGWToHARequest:
    """"""

    Region: str  # 地域ID，用于标识资源所属的地理区域

    VPNGWID: str  # VPN网关ID，待升级为高可用模式的VPN网关唯一标识，网关需处于Running且资源可用，当前为Standalone时才执行升级

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制

