# Code generated by sdk-generator. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Dict
from ucloudstack.services.models import *


@dataclass
class ValidatePartitionConfigResponse:
    """"""
    RetCode: int = 0
    Message: str = ""
    Action: str = ""

    Result: Optional[ValidatePartitionConfigResult] = None  # 验证结果
