# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AlertInfo:
    """"""

    ActiveAt: Optional[int] = None  # 活跃时间，告警活跃时间戳，表示告警首次触发或最后一次活跃的时间
    CompanyID: Optional[int] = None  # 租户ID，告警所属租户ID
    Email: Optional[str] = None  # 租户邮箱，告警所属租户邮箱
    LabelSet: Optional[List[AlertLabelSet]] = None  # 告警标签，告警标签信息
    Metric: Optional[str] = None  # 告警指标，触发告警的监控指标名称
    Region: Optional[str] = None  # 地域，告警所属地域
    RegionName: Optional[str] = None  # 地域名称，告警所属地域名称
    Severity: Optional[str] = None  # 告警级别，取值：warning/critical/error
    State: Optional[str] = None  # 告警状态，取值：inactive/pending/firing
    Summary: Optional[str] = None  # 描述，告警摘要描述
    TargetID: Optional[str] = None  # 资源ID，触发告警的目标资源ID
    TargetName: Optional[str] = None  # 资源名称，触发告警的目标资源名称
    TemplateType: Optional[str] = None  # 模板类型，告警规则使用的模板类型
    Thresholds: Optional[float] = None  # 阈值，告警规则设置的触发阈值
    Value: Optional[float] = None  # 当前值，监控指标实时值
