# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AlertNotifyGroupInfo:
    """"""

    CompanyID: Optional[int] = None  # 所属租户ID，通知组所属租户
    CreateTime: Optional[int] = None  # 创建时间，通知组创建时间戳
    Email: Optional[str] = None  # 租户邮箱，通知组所属租户邮箱
    Name: Optional[str] = None  # 通知组名称，通知组名称
    NotifyGroupID: Optional[str] = None  # 通知组ID，通知组唯一标识
    Region: Optional[str] = None  # 所属地域，通知组所属地域
    UpdateTime: Optional[int] = None  # 更新时间，通知组更新时间戳
