# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ASInstanceIPInfo:
    """"""

    IP: Optional[str] = None  # IP地址，伸缩成员的网络地址
    Type: Optional[str] = None  # IP类型，Private表示内网IP，Public表示公网IP
