# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AuditLogInfos:
    """"""

    AccountName: Optional[str] = None  # 账户名，执行SQL语句的数据库账户名称
    ClientIP: Optional[str] = None  # 客户端IP，执行SQL语句的客户端IP地址
    ExecutionDB: Optional[str] = None  # 操作数据库，SQL语句操作的数据库名称
    ExecutionResult: Optional[int] = None  # 执行结果，MySQL审计日志中的ReturnCode，0表示成功，非0表示失败
    ExecutionTime: Optional[int] = None  # 执行时间，日志时间戳（Unix时间），由Agent返回的LogMessage.Timestamp转换
    LogType: Optional[str] = None  # 日志类型，审计日志的事件类型，如QUERY、QUERY_DDL等
    SQLCommand: Optional[str] = None  # 执行命令，实际执行的SQL语句内容
