# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class BillOverView:
    """"""

    CycleAmount: Optional[float] = None  # 统计周期金额，该周期内的总金额，单位为元
    CycleAmountFree: Optional[float] = None  # 统计周期内部账号金额，该周期内的内部账号金额，单位为元
    CycleAmountReal: Optional[float] = None  # 统计周期外部账号金额，该周期内的外部账号金额，单位为元
    CycleCount: Optional[int] = None  # 统计周期数量，该周期内的记录数量
    CycleDetails: Optional[List[BillOverViewDetail]] = None  # 详情，该周期内各维度的详细统计信息
    CycleUnit: Optional[str] = None  # 统计周期单位，时间周期的单位，如hour、day、month等
    Time: Optional[int] = None  # 时间，统计周期的时间戳
