# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ChartInfo:
    """"""

    ID: Optional[str] = None  # 图表唯一标识，用于区分不同图表类型，如CPU、内存、存储等
    Items: Optional[List[ChartItem]] = None  # 图表元素列表，包含图表的具体数据项
    Labels: Optional[List[ChartLabel]] = None  # 额外的标签列表，用于标识图表的附加属性，如集群的resource_id或监控大屏的tab栏位置
    Title: Optional[str] = None  # 图表标题，图表的显示名称
