# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ChartSubItem:
    """"""

    DisplayValue: Optional[float] = None  # 显示值，细分数据项经过单位换算后的显示数值
    Name: Optional[str] = None  # 子图表项名称，细分数据项的显示名称
    Unit: Optional[str] = None  # 单位，细分数据项的计量单位
    Value: Optional[float] = None  # 子图表值，细分数据项的原始数值
