# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CIInfo:
    """"""

    BindResourceID: Optional[str] = None  # 绑定资源ID，虚拟机关联资源标识
    BindResourceName: Optional[str] = None  # 绑定资源名称，虚拟机关联资源名称
    BindResourceType: Optional[str] = None  # 绑定资源类型，虚拟机关联的资源类型
    CPU: Optional[int] = None  # CPU核数，虚拟机分配的vCPU数量
    CanMigrateAbort: Optional[bool] = None  # 是否可取消迁移，当前迁移是否允许取消
    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    Email: Optional[str] = None  # 所属租户邮箱，资源归属租户的联系邮箱
    GPU: Optional[int] = None  # GPU数量，虚拟机分配的GPU数量
    GPUMdevName: Optional[str] = None  # GPU规格，物理GPU规格名称
    HostID: Optional[str] = None  # 物理机ID，虚拟机所在宿主机标识
    HostIP: Optional[str] = None  # 物理机IP地址，宿主机管理IP地址
    HostIPv6: Optional[str] = None  # 物理机IPv6地址，宿主机管理IPv6地址
    ImageID: Optional[str] = None  # 镜像ID，虚拟机启动镜像标识
    ImageName: Optional[str] = None  # 镜像名称，虚拟机启动镜像名称
    InternalIP: Optional[str] = None  # 内网IP地址，虚拟机内网地址，优先返回IPv4地址
    MdevName: Optional[str] = None  # vGPU规格，虚拟GPU配置规格名称
    Memory: Optional[int] = None  # 内存大小，虚拟机分配内存容量，单位MiB
    Name: Optional[str] = None  # 虚拟机名称，宿主机上运行的虚拟机名称
    Region: Optional[str] = None  # 地域ID，虚拟机所属地域
    RegionAlias: Optional[str] = None  # 地域别名，地域的人性化显示名称
    Remark: Optional[str] = None  # 虚拟机描述，资源用途说明
    SetAlias: Optional[str] = None  # 集群别名，虚拟机所在计算集群的自定义名称
    SetArch: Optional[str] = None  # 计算集群架构，虚拟机所在集群CPU架构
    SetID: Optional[str] = None  # 计算集群ID，虚拟机所在计算集群标识
    SetType: Optional[str] = None  # 集群类型，虚拟机所在计算集群的类型标识
    Status: Optional[str] = None  # 运行状态，虚拟机当前状态
    Usage: Optional[str] = None  # 虚拟机用途，业务用途说明
    VCPUBindingNode: Optional[str] = None  # vCPU绑定节点，虚拟机绑定的物理节点
    VGPUID: Optional[str] = None  # vGPUID，虚拟GPU实例标识
    VMID: Optional[str] = None  # 虚拟机ID，虚拟机唯一标识
