# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CIStatusInfo:
    """"""

    CIID: Optional[str] = None  # CIID，容器实例标识（如果适用）
    CIStatus: Optional[str] = None  # CI状态，容器实例的运行状态
    ResourceID: Optional[str] = None  # 资源ID，对应的虚拟机等资源标识
