# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Compute:
    """"""

    CPUAllocable: Optional[int] = None  # CPU可分配，剩余可分配CPU核心数
    CPUCount: Optional[int] = None  # CPU数量，CPU核心总数
    CPULocked: Optional[int] = None  # CPU锁定量，已锁定CPU数量
    CPUType: Optional[str] = None  # CPU类型，用于标识类型
    CPUUsed: Optional[int] = None  # CPU已用，已分配CPU核心数
    GPUAllocable: Optional[int] = None  # GPU可分配，剩余可分配GPU数量
    GPUCount: Optional[int] = None  # GPU数量，GPU总数
    GPUInfos: Optional[List[HostGPUUsedInfo]] = None  # GPU详情，物理GPU使用详情
    GPULocked: Optional[int] = None  # GPU锁定量，已锁定GPU数量
    GPUType: Optional[str] = None  # GPU类型，用于标识类型
    GPUUsed: Optional[int] = None  # GPU已用，已分配GPU数量
    MemoryAllocable: Optional[float] = None  # 内存可分配，剩余可分配内存容量
    MemoryCap: Optional[float] = None  # 内存总量，内存总容量
    MemoryLocked: Optional[float] = None  # 内存锁定量，已锁定内存容量
    MemoryPhysicUsed: Optional[float] = None  # 物理内存已用，系统占用内存容量
    MemoryReserved: Optional[float] = None  # 内存预留量，系统预留内存容量
    MemoryUsed: Optional[float] = None  # 内存已用，已分配内存容量
    ResourceCount: Optional[int] = None  # 资源总数，节点资源总数
    SetID: Optional[str] = None  # 集群ID，用于标识集群
    SetType: Optional[str] = None  # 集群类型，用于标识类型
    VGPUDriverNotReady: Optional[bool] = None  # vGPU驱动是否就绪，标识vGPU驱动是否就绪
    VGPUInfos: Optional[List[HostVGPUUsedInfo]] = None  # vGPU详情，虚拟GPU使用详情
    Weight: Optional[int] = None  # 权重，调度权重值
