# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CompanyInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，租户唯一标识
    CompanyName: Optional[str] = None  # 租户名称，租户显示名称
    Email: Optional[str] = None  # 邮箱，租户主账号邮箱
