# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ConnectionInfos:
    """"""

    ConnectionStatus: Optional[str] = None  # 连接状态，来自ss/netstat输出的状态，如ESTABLISHED/TIME_WAIT
    RequestAdd: Optional[str] = None  # 请求地址，客户端IP及端口
    RequestResourceCompanyID: Optional[int] = None  # 请求端租户ID，仅当客户端IP可映射到具体租户资源时返回
    RequestResourceID: Optional[str] = None  # 请求端资源ID，系统尝试根据客户端IP反查租户资源，若无法匹配则为空
    RequestResourceName: Optional[str] = None  # 请求端资源名称，只有当IP成功匹配到租户资源时才会返回，未匹配时为空
    ResponseAdd: Optional[str] = None  # 响应地址，PaaS服务端虚拟机的内网IP及端口
    SearchTime: Optional[int] = None  # 查询时间，接口返回该连接时记录的时间戳（Unix时间）
