# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ControllerPlaneStatus:
    """"""

    CCM: Optional[ComponentStatus] = None  # 集群svc插件状态
    CSI: Optional[ComponentStatus] = None  # 集群存储插件状态
    ETCD: Optional[ComponentStatus] = None  # 集群ETCD状态
    KubeApiserver: Optional[ComponentStatus] = None  # 集群KubeApiserver状态
    KubeControllerManager: Optional[ComponentStatus] = None  # 集群KubeControllerManager状态
    KubeScheduler: Optional[ComponentStatus] = None  # 集群KubeScheduler状态
    KubeTerminal: Optional[ComponentStatus] = None  # 集群Kubeutil状态
    VK: Optional[ComponentStatus] = None  # 集群默认超级节点状态
