# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CreateVMInstanceRequestNIC:
    """"""

    FlatNetworkID: Optional[str] = None  # 扁平网络ID
    IP: Optional[str] = None  # ip地址，可选参数，为空则由平台分配
    InAverageBandwidth: Optional[int] = None  # 入向平均带宽，用于QoS流量整形；0表示不限制，单位Mbps
    LinkState: Optional[str] = None  # 启用状态，可选值：up（默认），down，可选参数
    MAC: Optional[str] = None  # mac地址，可选参数，为空则由平台分配
    Model: Optional[str] = None  # 网卡型号，支持e1000，virtio（默认），可选参数
    OutAverageBandwidth: Optional[int] = None  # 出向平均带宽，用于QoS流量整形；0表示不限制，单位Mbps
    Queues: Optional[int] = None  # 网卡队列数，可选参数，为0则根据cpu计算
    SGID: Optional[str] = None  # 安全组ID，可选参数
