# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Dimension:
    """"""

    DimensionName: Optional[str] = None  # 维度名称，对应集群类型的名称
    DimensionValue: Optional[str] = None  # 维度值，对应集群类型的值
