# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DiskInfo:
    """"""

    AttachResourceID: Optional[str] = None  # 已挂载资源ID，挂载目标资源标识
    AttachResourceName: Optional[str] = None  # 已挂载资源名称，挂载目标资源名称
    AttachResourceSnapCount: Optional[int] = None  # 已挂载资源整机快照数量，挂载目标资源的整机快照数量
    AttachResourceStatus: Optional[str] = None  # 已挂载资源状态，挂载目标资源状态
    AttachResourceType: Optional[str] = None  # 已挂载资源类型，挂载目标资源类型
    AttachShareBlockInfos: Optional[List[AttachShareBlock]] = None  # 共享盘挂载信息，当磁盘为共享盘且已挂载时返回挂载详情
    Bandwidth: Optional[int] = None  # 带宽，单位MB/s
    ChargeType: Optional[str] = None  # 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR
    CompanyID: Optional[int] = None  # 租户ID，资源所属的租户标识
    CompanyName: Optional[str] = None  # 租户名称，资源所属租户名称
    CreateTime: Optional[int] = None  # 创建时间，Unix 时间戳（秒级）
    CreatedAsBoot: Optional[bool] = None  # 创建时是否为系统盘，true表示创建时为系统盘
    DisableQoS: Optional[bool] = None  # 是否禁用QoS，true表示不限制磁盘QoS
    DiskID: Optional[str] = None  # 磁盘ID，磁盘唯一标识
    DiskStatus: Optional[str] = None  # 磁盘状态，取值范围：Creating、Detached、Attaching、Attached、Detaching、Deleting、Deleted、Rollbacking、Cloning、Shareabling、Shareabled、Blockcopying、Blockcopyed；空值表示未知
    DiskType: Optional[str] = None  # 磁盘类型，取值范围：Boot（系统盘）、Data（数据盘）、cdrom（光驱盘）、SaveMem（暂存盘）、BootImage（系统镜像盘）
    Drive: Optional[str] = None  # 设备名，磁盘在虚拟机内的设备名
    Email: Optional[str] = None  # 租户邮箱，资源所属租户的联系邮箱
    Encrypted: Optional[bool] = None  # 是否加密，true表示加密磁盘
    ExpireTime: Optional[int] = None  # 过期时间，Unix 时间戳（秒级）
    IOPS: Optional[int] = None  # IOPS，磁盘每秒输入输出操作次数
    MigrateBandWidth: Optional[int] = None  # 存储热迁移带宽，磁盘热迁移带宽限制
    MigrateFrom: Optional[str] = None  # 存储迁移原盘，迁移来源磁盘标识
    Name: Optional[str] = None  # 磁盘名称，支持中文、英文字母、数字、点（.）、下划线（_）和中划线（-），长度1-128个字符
    Percent: Optional[float] = None  # 迁移进度百分比，范围0-100
    ProjectID: Optional[str] = None  # 项目组ID，资源所属项目组
    ProjectName: Optional[str] = None  # 项目组名称，资源所属项目组名称
    Reason: Optional[str] = None  # 创建失败原因，失败时的错误信息
    Region: Optional[str] = None  # 地域，磁盘所属的地域
    RegionAlias: Optional[str] = None  # 地域别名，用于展示
    Remark: Optional[str] = None  # 备注，用于说明，长度0-100个中英文字符，禁止包含http://或https://等非法字符
    SetAlias: Optional[str] = None  # 存储集群别名，存储集群展示名称
    SetArch: Optional[str] = None  # 存储集群架构，取值范围：HDD、SSD、RSSD
    SetID: Optional[str] = None  # 存储集群ID，磁盘所属存储集群标识
    SetProvider: Optional[str] = None  # 存储集群制备器，底层存储驱动
    SetType: Optional[str] = None  # 存储集群类型，磁盘所属存储集群类型
    ShareAble: Optional[bool] = None  # 是否共享盘，true表示共享盘
    Size: Optional[int] = None  # 磁盘大小，单位GiB
    SnapshotCount: Optional[int] = None  # 快照数量，磁盘快照数量
    Tags: Optional[List[UnifiedTag]] = None  # 标签，资源标签列表
