# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DOSToken:
    """"""

    AccessKey: Optional[str] = None  # 公钥，用于S3访问认证
    AllowBuckets: Optional[List[str]] = None  # 授权的桶，允许访问的桶列表
    AllowObjectPrefix: Optional[str] = None  # 授权的对象前缀，仅允许 "*" 或不含 "*" 的前缀
    AllowOps: Optional[List[str]] = None  # 允许的操作，允许的S3操作列表
    BlackIPs: Optional[List[str]] = None  # IP黑名单，格式需包含 "/" 前缀长度
    ExpireTime: Optional[int] = None  # 过期时间，Unix 时间戳（毫秒）
    Name: Optional[str] = None  # 令牌名称，令牌展示名称
    SecretKey: Optional[str] = None  # 私钥，用于S3访问认证
    WhiteIPs: Optional[List[str]] = None  # IP白名单，格式需包含 "/" 前缀长度
