# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class EIPInfo:
    """"""

    Bandwidth: Optional[int] = None  # EIP带宽，单位为Mbps
    BindResourceID: Optional[str] = None  # 绑定的资源ID，EIP绑定的资源唯一标识符
    BindResourceName: Optional[str] = None  # 绑定的资源名称，EIP绑定资源的名称
    BindResourceProjectID: Optional[str] = None  # 绑定资源所属的项目ID
    BindResourceType: Optional[str] = None  # 绑定的资源类型，取值VM/NATGW/VPNGW/LB/K8S/DTS/OSS/FS/MYSQL/REDIS
    BindTime: Optional[int] = None  # 绑定时间，秒级Unix时间戳
    CanDefaultGW: Optional[int] = None  # 是否可以作为默认网关，0表示否，1表示是
    ChargeType: Optional[str] = None  # 计费类型，EIP的计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year，计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
    CompanyID: Optional[int] = None  # 租户唯一标识ID，资源所属租户标识
    CompanyName: Optional[str] = None  # 租户名称，资源所属租户名称
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    EIPID: Optional[str] = None  # EIP资源ID，弹性IP的唯一标识符
    Email: Optional[str] = None  # 租户邮箱，资源所属租户联系邮箱
    ExpireTime: Optional[int] = None  # 过期时间，秒级Unix时间戳
    IP: Optional[str] = None  # IP地址，弹性IP对应的公网地址
    IPVersion: Optional[str] = None  # IP版本，取值IPv4/IPv6
    ISDefaultGW: Optional[int] = None  # 是否是默认网关，0表示否，1表示是
    ISVIP: Optional[int] = None  # 是否为VIP，0表示否，1表示是，用于标识该IP是否为虚拟IP
    IsElastic: Optional[str] = None  # 是否弹性，N表示普通EIP，Y表示弹性网卡EIP或VIP
    Mode: Optional[str] = None  # EIP模式，取值NAT/Direct
    NICID: Optional[str] = None  # 网卡ID，当IsElastic为Y时表示关联的弹性网卡ID或VIP所在网卡ID
    Name: Optional[str] = None  # EIP名称，用于标识弹性IP资源
    OperatorAlias: Optional[str] = None  # 运营商网段别名
    OperatorName: Optional[str] = None  # 运营商网段名称
    ProjectID: Optional[str] = None  # 项目ID，资源所属项目分组标识
    ProjectName: Optional[str] = None  # 项目名称，资源所属项目名称
    Reason: Optional[str] = None  # 失败原因，当EIP创建失败时记录具体错误信息
    Region: Optional[str] = None  # 地域ID，用于标识资源所属的地理区域
    RegionAlias: Optional[str] = None  # 地域别名，地域的人性化显示名称
    Remark: Optional[str] = None  # EIP备注，用于补充说明
    Status: Optional[str] = None  # EIP状态，取值范围：Bound（已绑定）、Bounding（绑定中）、Unbounding（解绑中）、Free（未绑定）、SCHEDULING（调度中）、AVAILABLE（可用）、FAILED（创建失败）、DELETING（删除中）等资源状态
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表，资源关联的标签信息
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
