# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ExpiredResourceInfo:
    """"""

    Items: Optional[List[BaseExpiredResourceInfo]] = None  # 过期资源列表，包含该资源类型下的所有过期资源
    ResourceType: Optional[str] = None  # 资源类型，资源的分类标识
