# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ExternalStorageSetInfo:
    """"""

    CSIPluginAddress: Optional[str] = None  # 
    CreateTime: Optional[int] = None  # 
    DisableTargetIQNs: Optional[List[str]] = None  # 
    EnableTargetIQNs: Optional[List[str]] = None  # 
    LUNCount: Optional[int] = None  # 
    Reason: Optional[str] = None  # 
    Region: Optional[str] = None  # 
    SetAlias: Optional[str] = None  # 
    SetArch: Optional[str] = None  # 
    SetID: Optional[str] = None  # 
    SetType: Optional[str] = None  # 
    Status: Optional[str] = None  # 
    StorageCap: Optional[int] = None  # 
    UserName: Optional[str] = None  # 
