# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class HttpInfo:
    """"""

    RequestBody: Optional[str] = None  # 请求体，HTTP请求正文内容
    RequestHeader: Optional[str] = None  # 请求头，HTTP请求头的JSON字符串
    RequestMethods: Optional[str] = None  # 请求方法，HTTP请求的方法类型
    RequestParams: Optional[str] = None  # 请求参数，HTTP请求的查询参数
    RequestProtocolType: Optional[str] = None  # 请求协议，HTTP或HTTPS协议类型
    RequestURI: Optional[str] = None  # 请求URI，HTTP请求的目标路径
    ResponseBody: Optional[str] = None  # 响应体，HTTP响应正文内容
    ResponseHeader: Optional[str] = None  # 响应头，HTTP响应头的JSON字符串
    ResponseStatusCode: Optional[int] = None  # HTTP状态码，响应的HTTP状态码
