# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InspectionResourceUsageCompanyInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID
    Email: Optional[str] = None  # 邮箱，租户的邮箱地址
    Name: Optional[str] = None  # 租户名称，租户的显示名称
