# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InspectionResourceUsageDetail:
    """"""

    Infos: Optional[List[InspectionResourceUsageForm]] = None  # 资源用量表单列表，包含该资源的各项用量指标
    ResourceID: Optional[str] = None  # 资源ID，资源的唯一标识，包含资源类型前缀和14位随机字符
    ResourceName: Optional[str] = None  # 资源名称，资源的显示名称
    TotalCount: Optional[int] = None  # 总数，该资源的用量数据条目数
