# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InspectionResourceUsageForm:
    """"""

    Key: Optional[str] = None  # 资源用量键，用量指标的名称
    Unit: Optional[str] = None  # 单位，用量指标的计量单位
    Value: Optional[str] = None  # 资源用量值，用量指标的数值
