# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InspectionReport:
    """"""

    AbnormalCount: Optional[int] = None  # 异常项数，检查结果为异常的项数
    EndTime: Optional[int] = None  # 结束时间，巡检任务完成的Unix时间戳(秒)
    InspectionID: Optional[str] = None  # 一键巡检报告ID
    Name: Optional[str] = None  # 报告名称，巡检报告的显示名称
    NormalCount: Optional[int] = None  # 正常项数，检查结果为正常的项数
    RegionReports: Optional[List[MenuOne]] = None  # 地域报告列表，按地域组织的巡检结果树形结构
    Score: Optional[int] = None  # 总分，巡检报告的综合评分
    Spend: Optional[int] = None  # 耗时(秒)，巡检任务执行所花费的时间
    StartTime: Optional[int] = None  # 开始时间，巡检任务开始执行的Unix时间戳(秒)
    Status: Optional[str] = None  # 报告状态，巡检任务的当前执行状态
    TotalCount: Optional[int] = None  # 总检查项数，本次巡检包含的检查项总数
