# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class IPInfo:
    """"""

    IP: Optional[str] = None  # IP地址，具体的网络地址值
    IPID: Optional[str] = None  # IPID，IP资源唯一标识
    IPVersion: Optional[str] = None  # IP版本，网络地址协议版本，取值：IPv4、IPv6
    ISDefaultGW: Optional[int] = None  # 默认网关，标识是否为系统默认路由出口
    InterfaceID: Optional[str] = None  # 网卡ID，虚拟网卡接口标识
    InterfaceName: Optional[str] = None  # 接口名称，操作系统内的网卡设备名
    IsElastic: Optional[str] = None  # 弹性IP，标识是否为弹性公网IP
    IsVIP: Optional[str] = None  # VIP标识，标识是否为虚拟IP
    MAC: Optional[str] = None  # MAC地址，虚拟网卡的物理地址
    Mode: Optional[str] = None  # 绑定模式，IP与网卡的关联模式，取值：Direct、NAT
    NicPFCode: Optional[str] = None  # 网卡型号编码，物理网卡的标准型号编号
    NicPFProduct: Optional[str] = None  # 网卡产品型号，物理网卡的具体产品型号
    NicPFVendor: Optional[str] = None  # 网卡厂商，物理网卡的制造厂商
    NicType: Optional[str] = None  # 网卡类型，取值：LAN（内网）、WAN（外网）、Flat（扁平网络）
    SGID: Optional[str] = None  # 安全组ID，绑定的安全组资源标识
    SGName: Optional[str] = None  # 安全组名称，绑定的安全组可视化名称
    Type: Optional[str] = None  # 网络类型，标识IP的网络属性，取值：public（公网）、private（私网）
