# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class IpPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，EIP的计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year，计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
    OrderType: Optional[str] = None  # 订单类型，表示订单操作类型，如UPGRADE表示升级、DOWNGRADE表示降级
    Price: Optional[float] = None  # 价格，单位为元，表示EIP的价格或价格差异
