# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class LbVSInfo:
    """"""

    BackendProtocol: Optional[str] = None  # 后端协议，后端使用的协议，取值范围：空（默认HTTP）、HTTP、HTTPS
    CACertificateID: Optional[str] = None  # CA证书ID，用于验证客户端证书的签名，仅当协议为HTTPS且SSLMode为双向认证时有效
    CreateTime: Optional[int] = None  # 创建时间，资源创建的时间戳（秒）
    Domain: Optional[str] = None  # HTTP健康检查域名，HTTP检查时校验的HOST字段域名
    HealthcheckType: Optional[str] = None  # 健康检查类型，健康检查的类型，取值范围：Port、Path
    HttpClientMaxBodySizeMB: Optional[int] = None  # 请求体大小限制，单位MB，最大512；未配置时返回历史兼容默认展示值64
    HttpClientMaxHeaderSizeKB: Optional[int] = None  # 请求头大小限制，单位KB，最大512；未配置时返回历史兼容默认展示值32
    KeepaliveTimeout: Optional[int] = None  # 连接空闲超时时间，负载均衡的连接空闲超时时间，单位为秒
    LBID: Optional[str] = None  # 负载均衡ID，用于标识所属负载均衡实例
    Origin: Optional[str] = None  # 虚拟服务器来源，标识监听器来源，取值范围：Default、Service、Ingress
    Path: Optional[str] = None  # HTTP健康检查路径，HTTP检查时的请求路径
    PersistenceKey: Optional[str] = None  # 会话保持KEY，会话保持的键
    PersistenceType: Optional[str] = None  # 会话保持类型，会话保持的类型，取值范围：None、Auto、Manual
    Port: Optional[int] = None  # 虚拟服务器端口，VServer的监听端口，端口范围为1~65535
    Protocol: Optional[str] = None  # 虚拟服务器协议，VServer的监听协议，取值范围：TCP、UDP、HTTP、HTTPS
    ProxyProtocolEnable: Optional[str] = None  # TCP Proxy Protocol开关，是否开启TCP Proxy Protocol，取值范围：On、Off
    RSHealthStatus: Optional[str] = None  # 真实服务器健康状态，健康检查的状态，取值范围：Empty（全部异常）、Parts（部分异常）、All（全部正常）
    RSInfos: Optional[List[LbRSInfo]] = None  # 真实服务器列表，VServer关联的真实服务器列表
    RedirectVsID: Optional[str] = None  # HTTP重定向目标VSID，重定向到的虚拟服务器ID
    SSLMode: Optional[str] = None  # SSL认证模式，SSL的认证模式，取值范围：simplex（单向认证）、duplex（双向认证）
    Scheduler: Optional[str] = None  # 调度算法，负载均衡的调度算法，取值范围：wrr、least_conn、hash、ip_hash
    ServerCertificateID: Optional[str] = None  # 服务器证书ID，用于证明服务器的身份，仅当协议为HTTPS时有效
    UpdateTime: Optional[int] = None  # 更新时间，资源最后更新的时间戳（秒）
    VSID: Optional[str] = None  # 虚拟服务器ID，用于标识所属监听器
    VSPolicyInfos: Optional[List[LbVSPolicyInfo]] = None  # 转发规则列表，VServer关联的转发规则列表
    VSStatus: Optional[str] = None  # 虚拟服务器状态，VServer的资源状态，取值范围：Available（可用）、Updating（更新中）、Deleted（已删除）
