# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Location:
    """"""

    ControllerID: Optional[str] = None  # RAID卡ControllerID，用于标识RAID控制器ID
    Drive: Optional[str] = None  # 物理设备名，用于展示物理设备名称
    Enclosure: Optional[str] = None  # 磁盘柜编号，磁盘所在磁盘柜编号
    Model: Optional[str] = None  # 磁盘型号，磁盘设备型号
    RAIDLevel: Optional[str] = None  # RAID级别，用于标识RAID级别
    SerialNumber: Optional[str] = None  # 磁盘序列号，用于标识唯一标识
    Size: Optional[int] = None  # 磁盘大小，单位GiB
    Slot: Optional[str] = None  # 磁盘插槽号，磁盘所在插槽号
    Status: Optional[str] = None  # 磁盘状态，用于标识当前状态
    Type: Optional[str] = None  # 磁盘类型，取值范围：1-HDD、2-SSD
