# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class LogicalVolume:
    """"""

    LVDMPath: Optional[str] = None  # 逻辑卷路径，逻辑卷设备路径
    LVMSize: Optional[int] = None  # 逻辑卷大小，逻辑卷容量
    LVName: Optional[str] = None  # 逻辑卷名，逻辑卷名称
    LVTAGs: Optional[str] = None  # 逻辑卷标签，逻辑卷标签信息
    VGName: Optional[str] = None  # 卷组名，卷组名称
