# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MemberInfo:
    """"""

    Amount: Optional[float] = None  # 账号总余额，账户可支配资金总额，单位为元
    AmountCredit: Optional[float] = None  # 外部余额，通过充值获得的余额，单位为元
    AmountFree: Optional[float] = None  # 内部余额，系统发放的免额额度，单位为元
    Audit: Optional[int] = None  # 审批状态，用于资源审批流程识别，仅对某些特定业务流程有效，取值：0（待审批）、1（已通过）
    CompanyID: Optional[int] = None  # 租户ID，账号所属租户标识
    CreateTime: Optional[int] = None  # 创建时间，账号首次建立的Unix时间戳
    Email: Optional[str] = None  # 账号邮箱，账号登录与通知接收地址
    MemberID: Optional[int] = None  # 成员ID，账号唯一标识，用于账号关联与管理
    MemberName: Optional[str] = None  # 成员名称，账号展示名称用于管理界面显示
    OAuth2UniqueID: Optional[str] = None  # OAuth2唯一标识ID，用于绑定外部身份提供商的用户身份
    Phone: Optional[str] = None  # 手机号，用于安全通知或验证码接收
    PrivateKey: Optional[str] = None  # API私钥，用于请求签名，需妥善保管
    Privileges: Optional[str] = None  # 权限级别，标识账号在租户内的管理范围，取值：MEMBER_PRIVILEGES_ADMIN（管理员）、MEMBER_PRIVILEGES_DEFAULT（普通成员）
    PublicKey: Optional[str] = None  # API公钥，用于请求签名校验与鉴权
    Status: Optional[str] = None  # 账号状态，标识账号当前可用性，取值：AVAILABLE（正常）、FREEZE（冻结）、LOCKED（锁定）
    UpdateTime: Optional[int] = None  # 更新时间，账号信息最后一次修改的Unix时间戳
