# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MemoryUsage:
    """"""

    Size: Optional[int] = None  # 内存大小，单位MiB
    Used: Optional[int] = None  # 已使用内存大小，单位MiB
