# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MenuTwo:
    """"""

    Children: Optional[List[ItemReport]] = None  # 检查项列表，该分类下的具体检查项
    Key: Optional[str] = None  # 二级菜单ID，检查分类ID
    Title: Optional[str] = None  # 二级菜单名称，检查分类名称
