# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MySQLInfo:
    """"""

    Arch: Optional[str] = None  # 集群架构，实例计算架构
    AuditStatus: Optional[str] = None  # SQL审计状态，0:关闭;1:开启
    Bandwidth: Optional[int] = None  # 带宽，单位：Mbps
    ChargeType: Optional[str] = None  # 计费类型，用于指定计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）
    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
    CompanyName: Optional[str] = None  # 租户名称，租户的名称
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳（秒级）
    DiskID: Optional[str] = None  # 磁盘ID，实例数据盘ID
    DiskSpace: Optional[int] = None  # 存储容量，单位：GiB
    Email: Optional[str] = None  # 租户邮箱，租户注册时提供的用于接收通知和联系的邮箱
    Endpoints: Optional[List[MysqlEndpoint]] = None  # MySQL网络信息，实例网络信息列表
    ExpireTime: Optional[int] = None  # 过期时间，Unix时间戳（秒级）
    HighAvailability: Optional[str] = None  # MySQL数据库高可用类型，实例高可用类型
    IOPS: Optional[int] = None  # IOPS，单位：IOPS
    LegacyConfigNormalized: Optional[str] = None  # legacy 配置是否已完成归一化，true 表示已归一化并退出兼容 bypass
    LegacyUpgradeFrom: Optional[str] = None  # legacy 升级来源标记，仅用于标识老版本升级进入 2.13.x 的兼容实例
    Memory: Optional[int] = None  # 内存大小，单位：MiB
    MySQLID: Optional[str] = None  # MySQL实例ID，实例唯一标识
    Name: Optional[str] = None  # MySQL名称，实例名称
    ProjectID: Optional[str] = None  # 项目组ID，用于资源分组管理
    ProjectName: Optional[str] = None  # 项目组名称，项目组的名称
    Reason: Optional[str] = None  # 创建失败原因，实例创建失败原因
    Region: Optional[str] = None  # 地域ID，地域，一批可共享的物理资源使用集合
    RegionAlias: Optional[str] = None  # 地域别名，地域的别名
    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用的http://或https://等非法字符，可为空
    Role: Optional[str] = None  # MySQL角色，取值范围：1、Master（主节点）2、Slave（从节点）
    SlaveInfos: Optional[List[MySQLSlaveInfo]] = None  # 从库信息，从库实例信息列表
    Status: Optional[str] = None  # MySQL资源状态，实例状态
    StorageSetArch: Optional[str] = None  # 存储集群架构，实例存储集群架构
    StorageSetType: Optional[str] = None  # 存储集群ID，实例存储集群ID
    StorageSetTypeAlias: Optional[str] = None  # 存储集群名称，实例存储集群名称
    SubnetID: Optional[str] = None  # 子网ID，实例所属子网ID
    SubnetName: Optional[str] = None  # 子网名称，实例所属子网名称
    Tags: Optional[List[UnifiedTag]] = None  # 标签，资源标签列表
    TerminationPolicy: Optional[int] = None  # 是否开启删除保护，0:开启;1:关闭
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳（秒级）
    VMType: Optional[str] = None  # 计算集群类型，实例所属计算集群类型
    VMTypeAlias: Optional[str] = None  # 计算集群名称，实例所属计算集群名称
    VPCID: Optional[str] = None  # VPCID，实例所属VPCID
    VPCName: Optional[str] = None  # VPC名称，实例所属VPC名称
    Version: Optional[str] = None  # MySQL版本，必须为'MySQL 5.7'或者'MySQL 8.0'
