# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MysqlEndpoint:
    """"""

    Endpoint: Optional[str] = None  # 端点，IP:Port形式的访问地址
    IP: Optional[str] = None  # IP地址，实例网卡IP地址
    IPVersion: Optional[str] = None  # IP版本，IPv4或IPv6
    NicType: Optional[str] = None  # 网卡类型，取值范围：LAN（内网）、WAN（外网）
    SGID: Optional[str] = None  # 安全组ID，网卡绑定的安全组ID
    SGName: Optional[str] = None  # 安全组名称，网卡绑定的安全组名称
