# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class NICInfo:
    """"""

    Bandwidth: Optional[int] = None  # 带宽，单位Mbps
    BindResourceID: Optional[str] = None  # 绑定资源ID，网卡当前绑定的资源ID
    BindResourceName: Optional[str] = None  # 绑定资源名称
    BindResourceType: Optional[str] = None  # 绑定资源类型
    ChargeType: Optional[str] = None  # 计费类型，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year；计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
    CompanyID: Optional[int] = None  # 租户ID
    CompanyName: Optional[str] = None  # 租户名称
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱
    ExpireTime: Optional[int] = None  # 过期时间，秒级Unix时间戳，仅计费资源有效
    FlatNetwork: Optional[str] = None  # 扁平网络网段，扁平网络型网卡所属的网段范围
    FlatNetworkID: Optional[str] = None  # 扁平网络ID，扁平网络型网卡所属的网络资源标识
    FlatNetworkName: Optional[str] = None  # 扁平网络名称
    IP: Optional[str] = None  # IP地址，网卡当前使用的IP地址
    IPID: Optional[str] = None  # IPID，网卡绑定的IP资源标识。网卡级IP/VPC/Subnet/Segment/FlatNetwork信息取自网卡的IPInfos第一个IP，这些是为了兼容，应该优先使用IPInfos
    IPInfos: Optional[List[NICIPInfo]] = None  # IP信息列表，网卡绑定的IP地址详细信息
    InTrafficShaping: Optional[TrafficShaping] = None  # 入向流量整形策略，包含是否启用和平均带宽限制
    IsElastic: Optional[bool] = None  # 是否弹性网卡，标识网卡是否为可独立创建和管理的弹性网卡
    MAC: Optional[str] = None  # MAC地址，格式为6组2位十六进制数，以冒号或连字符分隔
    NICID: Optional[str] = None  # 网卡ID，网卡资源的唯一标识
    NICStatus: Optional[str] = None  # 网卡状态，表示网卡当前状态；当资源状态非Available时返回资源状态
    NICType: Optional[str] = None  # 网卡类型，LAN表示从VPC内网分配，WAN表示从外网网段分配，Flat表示从扁平网络分配
    Name: Optional[str] = None  # 网卡名称
    OutTrafficShaping: Optional[TrafficShaping] = None  # 出向流量整形策略，包含是否启用和平均带宽限制
    PFCode: Optional[str] = None  # 物理网卡型号标准编号，SR-IOV场景下使用的物理网卡型号代码
    PFProduct: Optional[str] = None  # 物理网卡型号，SR-IOV场景下使用的物理网卡具体型号
    PFVendor: Optional[str] = None  # 物理网卡厂商，SR-IOV场景下使用的物理网卡厂商名称
    ProjectID: Optional[str] = None  # 项目ID
    ProjectName: Optional[str] = None  # 项目名称
    Reason: Optional[str] = None  # 失败原因，网卡状态为失败时的原因描述
    Region: Optional[str] = None  # 地域ID，用于标识网卡所属的地理区域
    RegionAlias: Optional[str] = None  # 地域名称
    Remark: Optional[str] = None  # 备注，用于说明和注释
    SGID: Optional[str] = None  # 安全组ID，网卡绑定的安全组资源标识
    SGName: Optional[str] = None  # 安全组名称
    SegmentID: Optional[str] = None  # 外网线路ID，外网型网卡使用的线路资源标识
    SegmentName: Optional[str] = None  # 外网线路名称
    SegmentNetwork: Optional[str] = None  # 外网线路网段，外网型网卡所属的网段范围
    SubnetID: Optional[str] = None  # 子网ID，内网型网卡所属的子网资源标识
    SubnetName: Optional[str] = None  # 子网名称
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表
    VPCID: Optional[str] = None  # VPCID，内网型网卡所属的专有网络ID
    VPCName: Optional[str] = None  # VPC名称
