# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class NicPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，表示该价格对应的计费模式；取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费），兼容hour/month/year；计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
    OrderType: Optional[str] = None  # 订单类型，仅在改配场景返回，UPGRADE表示升级，DOWNGRADE表示降级，ORDER_TYPE_NONE表示平级改配，创建场景为空
    Price: Optional[float] = None  # 价格，单位元
