# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class NodeInfo:
    """"""

    Arch: Optional[str] = None  # 架构，节点CPU架构
    CPU: Optional[CPU] = None  # CPU详情，节点CPU资源信息
    Compute: Optional[Compute] = None  # 资源用量情况（计算节点独有），计算节点资源使用统计
    HealthStatus: Optional[str] = None  # 节点健康状态，节点健康度状态
    Memory: Optional[Memory] = None  # 内存详情，节点内存资源信息
    NTP: Optional[NTPInfo] = None  # NTP详情，节点时间同步信息
    Network: Optional[Network] = None  # 主机网络详情，节点网络信息
    NodeID: Optional[str] = None  # 节点ID，节点唯一标识
    NodeIP: Optional[str] = None  # 节点IP地址，节点管理IP地址
    NodeIPv6: Optional[str] = None  # 节点IPv6地址，节点管理IPv6地址
    NodeStatus: Optional[str] = None  # 节点状态，当前运行状态
    NumaNodes: Optional[int] = None  # NUMA节点数，节点NUMA拓扑数量
    OSDInfos: Optional[List[OSDStat]] = None  # 存储节点OSD详情，存储服务状态信息
    PhysicalDisks: Optional[List[PhysicalDisk]] = None  # 物理磁盘详情，节点磁盘列表信息
    Region: Optional[str] = None  # 地域ID，节点所属地域
    SerialNumber: Optional[str] = None  # 序列号，硬件设备序列号
    Types: Optional[List[str]] = None  # 节点类型，节点角色列表
    UUID: Optional[str] = None  # UUID，节点硬件唯一标识
    VCPUBindingEnabled: Optional[bool] = None  # 是否支持vCPU绑定，节点是否支持绑定能力
