# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ObserverInfo:
    """"""

    ObserverEmail: Optional[str] = None  # 观察人邮箱地址，观察人的邮箱，用于接收审批进度通知
    ObserverMemberID: Optional[int] = None  # 观察人账号ID，可以查看审批进度但不参与审批决策的用户标识
