# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class OPLogResource:
    """"""

    IPs: Optional[List[OPLogIPInfo]] = None  # 关联IP列表，记录操作发生时关联的IP信息
    ResourceID: Optional[str] = None  # 资源ID，关联资源的唯一标识
    ResourceName: Optional[str] = None  # 资源名称，操作发生时记录的资源名称
    ResourceType: Optional[str] = None  # 资源类型，关联资源的类型标识
