# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class OPLogInfo:
    """"""

    APIName: Optional[str] = None  # API名称，触发该操作日志的接口名称
    ClientIp: Optional[str] = None  # 客户端IP，发起请求的客户端IP地址
    CompanyID: Optional[int] = None  # 租户ID，日志所属租户的唯一标识
    Context: Optional[Dict[str, str]] = None  # 错误上下文，用于前端参数化翻译，包含错误相关的键值对
    CreateTime: Optional[int] = None  # 创建时间，日志生成的Unix时间戳
    HttpInfo: Optional[HttpInfo] = None  # HTTP请求响应详情，记录请求与响应的原始信息
    Message: Optional[str] = None  # 返回信息，API响应的描述信息
    OPLogID: Optional[int] = None  # 操作日志ID，系统生成的唯一标识
    ProductType: Optional[str] = None  # 产品类型，操作涉及的产品分类
    Region: Optional[str] = None  # 地域ID；地域类操作返回具体地域标识，全局类或账号级日志可为空
    RegionAlias: Optional[str] = None  # 地域别称；当 Region 非空时保证非空，优先返回地域显示名称，缺失时可回退为 Region 原值；当 Region 为空时该字段也为空
    ResourceID: Optional[str] = None  # 资源ID，操作涉及的资源唯一标识
    ResourcesAfter: Optional[List[OPLogResource]] = None  # 操作后关联资源快照，记录资源名称、类型和IP信息
    ResourcesBefore: Optional[List[OPLogResource]] = None  # 操作前关联资源快照，记录资源名称、类型和IP信息
    RetCode: Optional[int] = None  # 返回码，API响应的状态码；0表示成功，非0表示失败
    UpdateTime: Optional[int] = None  # 更新时间，日志信息最后更新的Unix时间戳
    UserEmail: Optional[str] = None  # 账号邮箱，执行操作的用户邮箱
