# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class OrderDetail:
    """"""

    Factor: Optional[int] = None  # 计费因子，计费规则的因子值，用于价格计算，与产品计费方式相关
    ProductName: Optional[str] = None  # 产品名称，订单关联的产品显示名称，例如磁盘、云主机等
    Property: Optional[str] = None  # 集群类型，资源所属的集群类型标识，用于区分不同的存储或计算集群
    Quantity: Optional[int] = None  # 资源数量，本次操作涉及的资源数量，例如创建磁盘的数量或购买的容量大小，单位与产品类型相关
    ResourceID: Optional[str] = None  # 资源ID，订单关联的资源唯一标识，例如磁盘订单对应磁盘ID
    Unit: Optional[str] = None  # 计量单位，资源的计量单位，例如GB、个、核等
