# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class OssPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，价格对应的计费模式
    OrderType: Optional[str] = None  # 订单类型，用于区分购买或扩容等计费场景
    Price: Optional[float] = None  # 价格，单位元
