# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PaaSInstance:
    """"""

    CPU: Optional[int] = None  # CPU数量，虚拟机的CPU核心数
    CanMigrateAbort: Optional[bool] = None  # 是否允许取消迁移，true表示当前可以取消正在进行的迁移，false表示不允许取消
    Disk: Optional[int] = None  # 磁盘大小，虚拟机的磁盘容量（单位：GB）
    DstSetID: Optional[str] = None  # 目标计算集群或存储集群ID
    HostIP: Optional[str] = None  # 宿主机IP，虚拟机所在物理宿主机的IP地址
    InstanceID: Optional[str] = None  # 实例ID，具体实例（虚拟机）的ID标识
    InstanceIP: Optional[str] = None  # 实例IP，虚拟机的内网IP地址
    InstanceStatus: Optional[str] = None  # 实例状态，虚拟机的运行状态，如Running、Stopped等
    IsPrimary: Optional[bool] = None  # 是否是主实例，true表示主实例，false表示从实例或备份实例
    Memory: Optional[int] = None  # 内存大小，虚拟机的内存容量（单位：MB）
    MigrateBandWidth: Optional[int] = None  # 存储热迁移带宽，当前存储热迁移的带宽限制（单位：MB/s）
    Progress: Optional[int] = None  # 迁移进度，当前计算迁移或存储迁移的进度，0-100
    Reason: Optional[str] = None  # 异常信息，实例异常时的错误描述信息
    ResourceID: Optional[str] = None  # PaaS资源ID，PaaS产品的资源标识
    ResourceType: Optional[str] = None  # PaaS资源类型，PaaS产品的类型，如MYSQL、REDIS、LB、NATGW、VPNGW等
    SetAlias: Optional[str] = None  # 计算集群别名，计算集群的友好名称
    SetArch: Optional[str] = None  # 计算集群架构，计算集群的CPU架构类型，如x86_64、arm64等
    SetID: Optional[str] = None  # 计算集群ID，虚拟机所在计算集群的ID
    StorageSetAlias: Optional[str] = None  # 存储集群别名，存储集群的友好名称
    StorageSetArch: Optional[str] = None  # 存储集群架构，存储集群的CPU架构类型，如x86_64、arm64等
    StorageSetID: Optional[str] = None  # 存储集群ID，虚拟机磁盘所在存储集群的ID
    StorageSetType: Optional[str] = None  # 存储集群类型，存储集群的类型，如SSD、HDD等
    VMType: Optional[str] = None  # 计算集群类型，虚拟机所在计算集群的类型标识
