# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PartitionTemplateConfig:
    """"""

    BtrfsSubvols: Optional[List[PartitionTemplateBtrfsSubvol]] = None  # Btrfs子卷配置
    LVMVolumeGroup: Optional[str] = None  # LVM卷组名称
    Partitions: Optional[List[PartitionTemplatePartition]] = None  # 分区列表
    RAIDConfigs: Optional[List[PartitionTemplateRAIDConfig]] = None  # RAID配置
    Scheme: Optional[str] = None  # 分区方案: standard, lvm, raid, btrfs
