# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PCPUBindingInfo:
    """"""

    NUMANodes: Optional[List[NUMANode]] = None  # CPU详情，节点NUMA拓扑CPU信息
    NodeID: Optional[str] = None  # 节点ID，用于标识节点唯一标识
