# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Permission:
    """"""

    ActionType: Optional[str] = None  # 操作类型，标识该权限所属分类
    IsPermission: Optional[int] = None  # 是否授权，标识是否拥有该动作权限；0表示否，1表示是
    Name: Optional[str] = None  # 权限名称，对应API的Action标识
    Permission: Optional[int] = None  # 权限值，内部使用的权限位标识
    Remark: Optional[str] = None  # 备注，对该权限功能的业务描述
