# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PhyProductInfo:
    """"""

    Code: Optional[str] = None  # 网卡型号标准编号，网卡型号标识
    PFInfos: Optional[List[PFInfo]] = None  # 节点下的同型号网卡列表
    Product: Optional[str] = None  # 网卡型号，网卡型号名称
    ReservedVFs: Optional[List[VFInfo]] = None  # 预占VF列表，已占用VF名额但未确定归属PF，例如绑定中的VF卡或未绑定IP的Eth0
    Vendor: Optional[str] = None  # 网卡厂商，网卡厂商名称
