# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PMInfoV2:
    """"""

    BMCInfo: Optional[str] = None  # BMC信息，包含BMC版本、厂商等详细信息
    BMCTypeName: Optional[str] = None  # BMC类型名称，标识硬件厂商的BMC类型（如Dell iDRAC、HP iLO等）
    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
    CompanyName: Optional[str] = None  # 租户名称，租户的显示名称
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳（秒）
    CustomMetricsPath: Optional[str] = None  # 自定义监控地址，用于Prometheus等监控系统采集指标，必须是有效的http/https URL且包含Host
    Email: Optional[str] = None  # 联系人邮箱地址
    ExpireTime: Optional[int] = None  # 资源过期时间，Unix时间戳（秒），到期后资源可能被回收
    HardwareInfo: Optional[str] = None  # 硬件信息，包含CPU、内存、磁盘等硬件配置的JSON格式数据
    Hostname: Optional[str] = None  # 主机名，裸金属当前登记的主机名
    IPMIIP: Optional[str] = None  # IPMI管理IP地址，用于带外管理访问
    IPMIPassword: Optional[str] = None  # IPMI密码，用于IPMI身份验证
    IPMIUsername: Optional[str] = None  # IPMI用户名，用于IPMI身份验证
    IPs: Optional[List[str]] = None  # IP地址列表，裸金属绑定的所有IP地址
    InstallMode: Optional[str] = None  # 安装模式，系统安装方式，clone：克隆模式；kickstart：Kickstart自动化安装
    Manufacturer: Optional[str] = None  # 生产厂商，从BMC/IPMI FRU信息采集
    Name: Optional[str] = None  # 资源名称，长度为1-128个字符，名称只能包含中英文、数字、点（.）、下划线（_）和中划线（-）
    PMID: Optional[str] = None  # 裸金属ID，由Taishan生成，作为Kunlun的资源标识
    ProductName: Optional[str] = None  # 产品名称，从BMC/IPMI FRU信息采集
    ProjectID: Optional[str] = None  # 项目ID，用于实现资源的逻辑分组管理
    ProjectName: Optional[str] = None  # 项目名称，项目的显示名称
    RackLocation: Optional[str] = None  # 机架位置，标识裸金属在数据中心的物理位置
    Reason: Optional[str] = None  # 资源申请原因，说明申请该资源的用途和目的
    Region: Optional[str] = None  # 地域ID，标识资源所属的物理区域
    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用http://或https://等非法字符，可为空
    SN: Optional[str] = None  # 序列号，从硬件获取的物理机唯一序列号
    Status: Optional[str] = None  # 裸金属状态，表示当前运行状态，Available：可用；Manageable：可管理；Uppering：上架中；UpperFailed：上架失败；Enrolled：已登记；InUse：使用中
    Tags: Optional[List[UnifiedTag]] = None  # 统一标签，用于资源标记和分类管理
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳（秒）
    ValidityCheckResults: Optional[List[str]] = None  # 有效性检查结果，系统对裸金属进行健康检查的结果信息
