# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PMInstallConfig:
    """"""

    DiskSelector: Optional[DiskSelectorV2] = None  # 磁盘选择器
    Hostname: Optional[str] = None  # 主机名
    ISOURL: Optional[str] = None  # ISO镜像URL
    ImageID: Optional[str] = None  # 镜像ID
    ImageURL: Optional[str] = None  # 镜像URL
    MachineID: Optional[str] = None  # 机器ID
    MachineSN: Optional[str] = None  # 机器序列号
    Mode: Optional[str] = None  # 模式
    Networks: Optional[List[InstallNetworkConfig]] = None  # 网络配置列表
    OSDistribution: Optional[str] = None  # 操作系统发行版
    OSMediaID: Optional[str] = None  # 系统镜像ID
    OSName: Optional[str] = None  # 操作系统名称
    PartitionTemplateID: Optional[str] = None  # 分区模板ID
    PartitionTemplateName: Optional[str] = None  # 分区模板名称
    Password: Optional[str] = None  # 密码
    SSHPublicKeys: Optional[List[str]] = None  # SSH公钥列表
    TemplateID: Optional[str] = None  # Kickstart 模板 ID
    TemplateName: Optional[str] = None  # Kickstart 模板名称
    Username: Optional[str] = None  # 用户名
