# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PodInfo:
    """"""

    CPULimit: Optional[int] = None  # CPU资源上限，单位核
    CPURequest: Optional[int] = None  # CPU资源下限，单位核
    Containers: Optional[List[ContainerInfo]] = None  # 容器详情列表，展示Pod内容器资源信息
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    HostID: Optional[str] = None  # 物理机ID，宿主机标识
    HostIP: Optional[str] = None  # 物理机IP地址，宿主机IP地址
    MemoryLimit: Optional[int] = None  # 内存资源上限，单位GiB
    MemoryRequest: Optional[int] = None  # 内存资源下限，单位GiB
    Name: Optional[str] = None  # Pod名称，用于展示Pod名称
    NameSpace: Optional[str] = None  # 命名空间，Pod所属命名空间
    Phase: Optional[str] = None  # Pod状态，标识当前状态
    PodIP: Optional[str] = None  # PodIP，Pod内网IP地址
