# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ProductResource:
    """"""

    ProductType: Optional[str] = None  # 产品类型，标识资源所属产品
    ResourceType: Optional[str] = None  # 资源类型，产品对应的资源类型名称
