# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RecycleResourceInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，资源所属租户
    CompanyName: Optional[str] = None  # 租户名称，资源所属租户的显示名称
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳
    DeleteTime: Optional[int] = None  # 删除时间，资源进入回收站的时间，Unix时间戳
    Description: Optional[str] = None  # 资源描述，资源备注或说明信息
    Email: Optional[str] = None  # 租户邮箱，资源所属租户的联系邮箱
    ExpireTime: Optional[int] = None  # 过期时间，资源到期时间，0表示永不过期
    IsAutoTerminated: Optional[bool] = None  # 是否自动销毁，true表示回收站资源将自动销毁
    IsFailed: Optional[bool] = None  # 是否失败，true表示资源处于失败状态
    Name: Optional[str] = None  # 资源名称，资源的自定义显示名称
    ProjectID: Optional[str] = None  # 项目ID，资源所属项目ID
    ProjectName: Optional[str] = None  # 项目名称，资源所属项目的显示名称
    Reason: Optional[str] = None  # 资源操作原因，记录资源状态变更或操作原因
    Region: Optional[str] = None  # 地域ID，资源所属的物理区域
    RegionAlias: Optional[str] = None  # 地域别名，地域的展示名称
    Remark: Optional[str] = None  # 资源备注，用于记录资源用途或说明
    ResourceID: Optional[str] = None  # 资源ID，回收站资源的唯一标识
    ResourceType: Optional[str] = None  # 资源类型，资源类型字符串，如VM、DISK、EIP等
    State: Optional[str] = None  # 状态字符串，资源业务状态的字符串表示
    Status: Optional[int] = None  # 状态码，资源状态的数值表示
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳
    WillTerminateTime: Optional[int] = None  # 预计销毁时间，回收站资源自动销毁时间
