# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RedisInfo:
    """"""

    Arch: Optional[str] = None  # 计算集群架构，实例计算架构
    ChargeType: Optional[str] = None  # 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR
    CompanyID: Optional[int] = None  # 租户ID，用于标识资源所属的租户，实现多租户环境下的资源隔离
    CompanyName: Optional[str] = None  # 租户名称，租户显示名称
    ConfigID: Optional[str] = None  # 配置文件ID，实例使用的配置模板ID
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳（秒级）
    Email: Optional[str] = None  # 租户邮箱，租户注册时提供的用于接收通知和联系的邮箱
    Endpoints: Optional[List[RedisEndpoint]] = None  # 网络信息，实例访问地址列表
    ExpireTime: Optional[int] = None  # 过期时间，Unix时间戳（秒）
    HighAvailability: Optional[str] = None  # 高可用类型，Standalone或ActiveStandy
    Memory: Optional[int] = None  # 内存大小，单位GiB
    MemoryUsage: Optional[MemoryUsage] = None  # 内存使用情况，实例内存使用信息
    Name: Optional[str] = None  # Redis名称，实例名称
    ProjectID: Optional[str] = None  # 项目组ID，用于资源分组管理
    ProjectName: Optional[str] = None  # 项目组名称，项目组显示名称
    Reason: Optional[str] = None  # 创建失败原因，实例创建失败原因
    RedisID: Optional[str] = None  # Redis实例ID，实例唯一标识
    Region: Optional[str] = None  # 地域ID，地域，一批可共享的物理资源使用集合
    RegionAlias: Optional[str] = None  # 地域别名，地域展示名称
    Remark: Optional[str] = None  # 备注，用于进行说明和注释，长度为0-100个英文或中文字符，不能使用的http://或https://等非法字符，可为空
    Role: Optional[str] = None  # 角色，实例角色类型
    SetType: Optional[str] = None  # 计算集群类型，实例所属计算集群类型
    SlaveCount: Optional[int] = None  # 从节点数量，从库数量
    SlaveInfos: Optional[List[SlaveRedisInfo]] = None  # 从库信息，从库实例列表
    Status: Optional[str] = None  # 资源状态，实例状态字符串
    StorageSetType: Optional[str] = None  # 存储集群类型，实例数据盘所属存储集群类型
    SubnetID: Optional[str] = None  # 子网ID，实例所属子网ID
    SubnetName: Optional[str] = None  # 子网名称，实例所属子网名称
    Tags: Optional[List[UnifiedTag]] = None  # 标签，用于资源标记和分类管理，格式为key:value的字符串，传入Base64编码的字符串，
    TerminationPolicy: Optional[int] = None  # 删除保护策略，0开启，1关闭
    Threads: Optional[int] = None  # 线程数量，Redis7.0有效
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳（秒级）
    VPCID: Optional[str] = None  # VPCID，实例所属VPCID
    VPCName: Optional[str] = None  # VPC名称，实例所属VPC名称
    Version: Optional[str] = None  # Redis版本，实例版本
