# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RegionConfigSyncStatusInfo:
    """"""

    CompletedCount: Optional[int] = None  # 已完成同步任务数
    ConfigKey: Optional[str] = None  # 配置键，地域配置项的唯一标识符
    SyncStatus: Optional[str] = None  # 同步状态，Synced 表示已同步，Syncing 表示同步中
    TotalCount: Optional[int] = None  # 同步任务总数
