# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RegionNetworkLatency:
    """"""

    Latency: Optional[float] = None  # 延迟时间，网络探测的耗时，单位毫秒
    ProbeType: Optional[str] = None  # 探测类型，网络延迟探测方式，如tcp
