# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResourceUsageInfo:
    """"""

    ResourceType: Optional[str] = None  # 资源类型，资源的分类标识
    ResourceUsageCount: Optional[int] = None  # 资源使用数量，该类型资源的唯一资源数(去重后)
