# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResourceUsageBaseInfo:
    """"""

    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳(秒)
    Name: Optional[str] = None  # 资源用量报告名称
    QueryCriteria: Optional[InspectionResourceUsageQueryCriteria] = None  # 查询条件，创建该资源用量报告时指定的查询参数
    ResourceUsageID: Optional[str] = None  # 资源用量ID
    Status: Optional[str] = None  # 状态，资源用量统计任务的当前执行状态
