# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ResourceStatusCountItem:
    """"""

    Count: Optional[int] = None  # 状态数量，该状态下的资源数量
    ResourceType: Optional[str] = None  # 资源类型，资源的分类标识
    Status: Optional[str] = None  # 状态，资源状态的标识
