# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RoleInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，标识角色所属的租户组织
    CreateTime: Optional[int] = None  # 创建时间，角色首次定义的Unix时间戳
    Name: Optional[str] = None  # 角色名称，用于在控制台显示
    Remark: Optional[str] = None  # 备注，用于补充说明角色用途和权限范围
    RoleID: Optional[str] = None  # 角色ID，系统生成的权限定义唯一标识符
    Stratum: Optional[str] = None  # 角色授权层级，取值：System、Region或Company
    Type: Optional[str] = None  # 角色类型，标识角色来源，取值：System或Custom
    UpdateTime: Optional[int] = None  # 更新时间，角色信息最后修改的Unix时间戳
