# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SetGPUUsedInfo:
    """"""

    Allocable: Optional[int] = None  # GPU可分配量，该类型GPU当前可用于分配的数量，计算方式为Count-Used-Locked
    Count: Optional[int] = None  # GPU总数，该类型GPU的总数量
    HDName: Optional[str] = None  # GPU硬件名称，物理GPU硬件设备名称
    Locked: Optional[int] = None  # GPU已锁定量，该类型GPU已锁定但尚未分配的数量，如虚拟机创建中
    MdevName: Optional[str] = None  # 虚拟GPU设备类型名称，该物理GPU支持的Mdev设备类型
    Used: Optional[int] = None  # GPU使用量，该类型GPU已分配给虚拟机的数量
