# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SGDetailInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID
    CompanyName: Optional[str] = None  # 租户名称
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱
    Name: Optional[str] = None  # 安全组名称，用于标识和区分不同的安全组
    ProjectID: Optional[str] = None  # 项目ID
    ProjectName: Optional[str] = None  # 项目名称
    Reason: Optional[str] = None  # 失败原因，创建或操作失败时记录具体原因
    Region: Optional[str] = None  # 地域ID，用于标识安全组所属的地理区域
    RegionAlias: Optional[str] = None  # 地域名称
    Remark: Optional[str] = None  # 备注，安全组的补充说明信息
    ResourceCount: Optional[int] = None  # 绑定资源数量，当前安全组已绑定的资源总数
    Rule: Optional[List[SGRuleInfo]] = None  # 安全组规则列表，包含该安全组定义的所有流量控制规则信息
    RuleCount: Optional[int] = None  # 规则数量，安全组当前配置的规则总数
    SGID: Optional[str] = None  # 安全组ID，安全组的唯一标识符
    Status: Optional[str] = None  # 资源生命周期状态，当资源状态非Available时返回资源状态
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
