# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SlaveRedisInfo:
    """"""

    Arch: Optional[str] = None  # 计算集群架构，从库实例计算架构
    ChargeType: Optional[str] = None  # 计费类型，取值Dynamic/Month/Year，分别对应HOUR/MONTH/YEAR
    CompanyID: Optional[int] = None  # 租户ID，从库实例所属租户
    ConfigID: Optional[str] = None  # 配置文件ID，从库实例配置模板ID
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳（秒）
    Email: Optional[str] = None  # 租户邮箱，租户联系邮箱
    Endpoints: Optional[List[RedisEndpoint]] = None  # 网络信息，从库实例访问地址列表
    ExpireTime: Optional[int] = None  # 过期时间，Unix时间戳（秒）
    HighAvailability: Optional[str] = None  # 高可用类型，Standalone或ActiveStandy
    MasterID: Optional[str] = None  # 主Redis实例ID，从库对应的主库ID
    Memory: Optional[int] = None  # 内存大小，单位MiB
    MemoryUsage: Optional[MemoryUsage] = None  # 内存使用情况，从库内存使用信息
    Name: Optional[str] = None  # 名称，从库实例名称
    ProjectID: Optional[str] = None  # 项目ID，从库实例所属项目
    ProjectName: Optional[str] = None  # 项目名称，从库实例所属项目名称
    Reason: Optional[str] = None  # 失败原因，从库创建失败原因
    RedisID: Optional[str] = None  # Redis实例ID，从库实例ID
    Region: Optional[str] = None  # 地域ID，从库实例所属地域
    Remark: Optional[str] = None  # 备注，从库实例备注信息
    Role: Optional[str] = None  # 角色，实例角色类型
    SetType: Optional[str] = None  # 计算集群类型，从库实例所属计算集群类型
    Status: Optional[str] = None  # 资源状态，实例状态字符串
    StorageSetType: Optional[str] = None  # 存储集群类型，从库实例数据盘所属存储集群类型
    SubnetID: Optional[str] = None  # 子网ID，从库实例所属子网ID
    SubnetName: Optional[str] = None  # 子网名称，从库实例所属子网名称
    Tags: Optional[List[UnifiedTag]] = None  # 标签，从库实例标签列表
    TerminationPolicy: Optional[int] = None  # 删除保护策略，0开启，1关闭
    Threads: Optional[int] = None  # 线程数量，Redis7.0有效
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳（秒）
    VPCID: Optional[str] = None  # VPCID，从库实例所属VPCID
    VPCName: Optional[str] = None  # VPC名称，从库实例所属VPC名称
    Version: Optional[str] = None  # Redis版本，从库实例版本
