# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SMCSubtask:
    """"""

    Name: Optional[str] = None  # 子任务名称，通常为磁盘分区名称或功能阶段名称，用于标识具体的迁移子任务
    Progress: Optional[float] = None  # 子任务完成进度，0-100的百分比值，表示该子任务的完成百分比
    Speed: Optional[str] = None  # 数据传输速率，用易读格式表示当前的传输吞吐量，如100MB/s或1Gbps
