# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SourceInfo:
    """"""

    SourceVMID: Optional[str] = None  # 源虚拟机ID，被克隆的源虚拟机标识
    VMSPID: Optional[str] = None  # 整机快照ID，克隆使用的快照标识
