# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SpecificationTemplate:
    """"""

    AllowedValues: Optional[str] = None  # 规格允许值，定义规格的可选值范围
    Description: Optional[str] = None  # 规格描述，说明规格的用途和含义
    ProductType: Optional[str] = None  # 产品类型
    ResourceType: Optional[str] = None  # 资源类型
    SetClassification: Optional[str] = None  # 集群分类，标识规格所属的集群分类
    SpecificationName: Optional[str] = None  # 规格名称
    TemplateID: Optional[str] = None  # 模板ID，规格模板的唯一标识符
    Unit: Optional[str] = None  # 单位，规格值的计量单位
    ValueFormat: Optional[str] = None  # 规格值格式，定义规格值的格式要求
    ValueType: Optional[str] = None  # 规格值类型，如string、int等
