# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Specification:
    """"""

    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳
    Default: Optional[str] = None  # 是否为默认规格，Yes表示默认，No表示非默认
    Dimension: Optional[Dimension] = None  # 规格维度信息
    ProductType: Optional[str] = None  # 产品类型
    Region: Optional[str] = None  # 地域ID
    ResourceType: Optional[str] = None  # 资源类型
    SetType: Optional[str] = None  # 集群类型，标识规格所属的集群类型
    SpecificationID: Optional[str] = None  # 规格ID，规格的唯一标识符
    SpecificationName: Optional[str] = None  # 规格名称
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳
    Value: Optional[str] = None  # 规格值，规格的具体配置值
