# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StorageClassItem:
    """"""

    StorageSetID: Optional[str] = None  # 存储集群ID，存储集群的唯一标识
    StorageSetName: Optional[str] = None  # 存储集群名称，存储集群的自定义名称
    StorageSetType: Optional[str] = None  # 存储集群类型，存储集群的类型标识
