# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class StorageSetTypeInfo:
    """"""

    Permission: Optional[str] = None  # 权限控制，该存储类型的访问权限，值为all表示所有租户可用，或以逗号分隔的租户ID列表
    Region: Optional[str] = None  # 地域ID，存储集群类型所属的物理区域
    SetArch: Optional[str] = None  # 存储集群架构，存储集群的硬件架构类型
    StorageType: Optional[str] = None  # 存储集群类型，存储集群的类型标识
    StorageTypeAlias: Optional[str] = None  # 存储集群类型别名，存储集群类型的自定义名称
