# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SubnetRouteInfo:
    """"""

    Destination: Optional[str] = None  # 目的地址
    NextHop: Optional[str] = None  # 下一跳标识，VIP/VM类型为资源ID，Custom类型为IP地址
    NextHopAddr: Optional[str] = None  # 下一跳的IP地址，实际的网络地址
    NextHopName: Optional[str] = None  # 下一跳名称，仅下一跳为VM/VIP时填充资源名称
    NextHopType: Optional[str] = None  # 下一跳类型，取值VIP/VM/Custom
    Remark: Optional[str] = None  # 备注，用于补充说明
    SubnetID: Optional[str] = None  # 子网ID
    SubnetName: Optional[str] = None  # 子网名称
