# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SuperNodeInfo:
    """"""

    AdjustableMaxCPU: Optional[int] = None  # 节点可调最大CPU数量
    AdjustableMaxMemory: Optional[int] = None  # 节点可调最大内存容量
    AdjustableMaxPods: Optional[int] = None  # 节点可调最大pod数量
    ArchType: Optional[str] = None  # 架构类型
    ClusterID: Optional[str] = None  # 集群Id
    ComputeclassType: Optional[str] = None  # 计算集群类型
    GPUInfos: Optional[List[SuperNodeGPUInfo]] = None  # 节点GPU信息
    InternalIP: Optional[str] = None  # 
    IsDefault: Optional[bool] = None  # 默认节点
    MaxCPU: Optional[int] = None  # 节点最大CPU数量
    MaxMemory: Optional[int] = None  # 节点最大内存容量
    MaxPods: Optional[int] = None  # 节点最大pod数量
    NodeName: Optional[str] = None  # 节点名称
    NodeStatus: Optional[str] = None  # 节点状态
    OSType: Optional[str] = None  # 系统类型
    Status: Optional[str] = None  # 状态
    StorageclassType: Optional[str] = None  # 存储集群类型
    SubnetIDs: Optional[List[str]] = None  # 子网Id 列表
    SubnetNames: Optional[List[str]] = None  # 子网名称列表
    Unschedulable: Optional[bool] = None  # 不可调度
    UsedCPU: Optional[float] = None  # 节点已使用CPU数量
    UsedMemory: Optional[float] = None  # 节点已使用内存容量
    UsedPods: Optional[float] = None  # 节点已使用pod数量
    VpcID: Optional[str] = None  # VpcID
    VpcName: Optional[str] = None  # VpcName
    YamlData: Optional[str] = None  # yaml数据
