# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class SuperNodeGPUInfo:
    """"""

    GPU: Optional[int] = None  # GPU的颗数
    GPUMdevName: Optional[str] = None  # GPU的规格
