# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TagResourceInfo:
    """"""

    Region: Optional[str] = None  # 地域ID，表示资源所在的物理区域
    RegionAlias: Optional[str] = None  # 地域别名，地域的用户友好显示名称
    ResourceID: Optional[str] = None  # 资源ID，全局唯一的资源标识符
    ResourceName: Optional[str] = None  # 资源名称，用户自定义的资源显示名称
    ResourceType: Optional[str] = None  # 资源类型，标识资源的种类，支持包括DISK、VM等多种资源类型
    TagCount: Optional[int] = None  # 标签数量，该资源绑定的标签总数
    Tags: Optional[List[Tag]] = None  # 标签列表，资源绑定的所有标签键值对信息
