# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TaskInfo:
    """"""

    BeginTime: Optional[int] = None  # 开始时间，任务实际开始执行的秒级Unix时间戳
    CreateTime: Optional[int] = None  # 创建时间，任务记录创建时刻的秒级Unix时间戳
    EndTime: Optional[int] = None  # 结束时间，任务执行完成的秒级Unix时间戳
    ErrCode: Optional[int] = None  # 错误码，任务执行返回码，0表示成功，非0表示失败
    Remark: Optional[str] = None  # 任务执行备注，记录执行过程中的关键信息或错误描述
    ResourceID: Optional[str] = None  # 资源ID，该任务操作的目标资源唯一标识符
    TargetID: Optional[str] = None  # 任务执行结果ID，任务成功后生成的结果资源标识，不同任务类型对应不同结果资源
    Task: Optional[str] = None  # 任务类型，该次执行的具体业务操作类型
    TaskID: Optional[str] = None  # 任务执行记录ID，单次任务执行的唯一标识符，用于追踪与审计
    TaskStatus: Optional[str] = None  # 任务执行状态，表示任务执行进度与结果，取值：Executing（执行中，任务正在处理）、Waiting（等待中，任务已创建但未开始）、Cancel（已取消，任务被手动取消）、Success（成功，任务执行完成且成功）、Failure（失败，任务执行失败）、Expired（已过期，任务超时未执行）
    TimerID: Optional[str] = None  # 定时器ID，关联本次执行记录的定时器唯一标识符
