# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TaskStepResource:
    """"""

    Execution: Optional[TaskExecution] = None  # 该资源在此任务中的最新执行情况，该资源在任务中的执行信息
    Name: Optional[str] = None  # 资源名称，资源名称
    Remark: Optional[str] = None  # 资源备注，资源描述信息
    ResourceID: Optional[str] = None  # 资源ID，步骤关联的资源ID
    Status: Optional[str] = None  # 资源状态，资源不存在时为Deleted，否则为资源RStatus字符串
