# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TopMap:
    """"""

    Name: Optional[str] = None  # 名称，资源或进程的名称
    Pid: Optional[str] = None  # 进程ID，进程标识符
    Size: Optional[str] = None  # 大小，资源大小或内存占用
    Status: Optional[str] = None  # 状态，资源或进程的当前状态
    Use: Optional[str] = None  # 使用量，资源使用量或占用率
