# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TrafficMirrorSimpleSource:
    """"""

    Available: Optional[bool] = None  # 是否可用，true表示该方向尚未被其他流量镜像占用可以使用，false表示已被占用
    Direction: Optional[str] = None  # 流量方向，拆分为inbound入方向或outbound出方向两条记录，当在某个流量镜像中选择all时会占用双向
    SrcDevice: Optional[str] = None  # 源设备ID，网卡资源的唯一标识符
    SrcDeviceName: Optional[str] = None  # 源设备名称，网卡资源的显示名称
