# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Transaction:
    """"""

    AccountID: Optional[int] = None  # 账号ID，交易操作的账号ID，与CompanyID相同
    AccountName: Optional[str] = None  # 账号名称，交易操作的账号名称，与AccountID对应
    BalanceSurplus: Optional[float] = None  # 余额，交易后的账户余额（外部账户），单位为元，精确到分
    CompanyID: Optional[int] = None  # 租户ID，交易所属的租户ID
    CompanyName: Optional[str] = None  # 租户名称，交易所属的租户名称，与CompanyID对应
    CreateTime: Optional[int] = None  # 创建时间，交易记录的创建时间戳
    Email: Optional[str] = None  # 租户邮箱，交易所属的租户邮箱，与CompanyID对应
    ExpenseAmount: Optional[float] = None  # 交易金额，支出的金额，单位为元，扣费和提现时此字段有值
    FreeBalanceSurplus: Optional[float] = None  # 内部账号余额，交易后的内部账号余额（赠金），单位为元，精确到分
    IncomeAmount: Optional[float] = None  # 收入金额，收入的金额，单位为元，充值和退款时此字段有值
    Region: Optional[str] = None  # 地域，交易所属的地域，充值提现类交易无地域属性
    RegionAlias: Optional[str] = None  # 地域别名，地域的显示名称，从DescribeRegion接口获取
    State: Optional[int] = None  # 状态，交易的状态编码，0表示成功
    TradeNO: Optional[str] = None  # 交易号，交易的业务流水号，对于订单关联的交易为订单号
    TransactionNO: Optional[str] = None  # 交易号，交易记录的唯一标识
    TransactionType: Optional[int] = None  # 交易类型，交易的类型编码，1表示扣费，2表示充值，3表示退款，4表示提现
