# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UsedSGIDInfo:
    """"""

    SGID: Optional[str] = None  # 安全组ID，引用IP组或端口组的安全组唯一标识符
    SGName: Optional[str] = None  # 安全组名称，引用IP组或端口组的安全组显示名称
