# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VCPUBinding:
    """"""

    PCPU: Optional[str] = None  # pCPU编号，宿主机的物理CPU索引或范围
    VCPU: Optional[int] = None  # vCPU编号，虚拟机的虚拟CPU索引
