# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VMMigrationReport:
    """"""

    CPUUtilization: Optional[float] = None  # CPU利用率，来源于资源标签CPUUtilization
    CompanyID: Optional[int] = None  # 租户ID
    CompletionTime: Optional[int] = None  # 任务完成时间，秒级Unix时间戳
    CreateTime: Optional[int] = None  # 任务创建时间，秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱
    JobID: Optional[str] = None  # DRS任务ID
    MemUsage: Optional[float] = None  # 内存使用率，来源于资源标签MemUsage
    MigrationInfo: Optional[VMMigrationInfo] = None  # 迁移详情
    Name: Optional[str] = None  # 虚拟机名称
    Remark: Optional[str] = None  # 虚拟机备注
    Usage: Optional[str] = None  # 虚拟机用途
    VMID: Optional[str] = None  # 虚拟机ID
