# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VmPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，计费模式，取值：Dynamic（按小时）、Month（按月）、Year（按年）
    Price: Optional[float] = None  # 价格，预估费用，单位：元
