# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VMWareVM:
    """"""

    CPU: Optional[int] = None  # 核心数，虚拟机的vCPU核心数量
    InventoryPath: Optional[str] = None  # 存储库路径，VMware虚拟机在存储库中的路径
    Memory: Optional[int] = None  # 内存容量，虚拟机的内存大小，单位：MiB
    Name: Optional[str] = None  # 虚拟机名称，VMware虚拟机显示名称
    PowerState: Optional[str] = None  # 电源状态，VMware虚拟机的运行状态
    VMID: Optional[str] = None  # 虚拟机ID，VMware虚拟机标识
