# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VMCInfo:
    """"""

    CloneInfo: Optional[CloneInfo] = None  # 新虚拟机信息，克隆生成的目标及其状态
    CreateTime: Optional[int] = None  # 创建时间，任务创建的秒级Unix时间戳
    SourceInfo: Optional[SourceInfo] = None  # 源虚拟机信息，克隆来源及其快照信息
    Status: Optional[str] = None  # 任务状态，克隆任务当前的执行状态
    VMCID: Optional[str] = None  # 任务ID，克隆任务的唯一标识
