# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VMSPInfo:
    """"""

    CPU: Optional[int] = None  # 核心数，快照时的vCPU核心数量
    ComputeSetType: Optional[str] = None  # 集群类型，快照所属的计算集群类型
    CreateTime: Optional[int] = None  # 创建时间，快照创建的秒级Unix时间戳
    IsCurrent: Optional[bool] = None  # 当前快照，标识是否为当前活动快照
    Memory: Optional[int] = None  # 内存容量，快照时的内存大小，单位：MiB
    Remark: Optional[str] = None  # 备注信息，对快照的补充说明
    SPID: Optional[str] = None  # 快照ID，快照的唯一标识
    SPName: Optional[str] = None  # 快照名称，快照的显示名称
    SPSize: Optional[int] = None  # 快照大小，快照占用的存储空间，单位：GiB
    SPStatus: Optional[str] = None  # 快照状态，快照当前的生命周期状态
    WithDisk: Optional[bool] = None  # 包含磁盘，标识快照是否包含磁盘数据
    WithMemory: Optional[bool] = None  # 包含内存，标识快照是否包含内存数据
