# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VPCDetailInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识用户所属的租户组织，用于实现多租户环境下的资源隔离和权限控制，系统根据此ID确定用户的资源访问范围
    CompanyName: Optional[str] = None  # 租户名称，资源所属租户名称
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱，资源所属租户的联系邮箱
    Name: Optional[str] = None  # VPC名称
    Network: Optional[str] = None  # 网段，VPC主网段的CIDR地址范围
    PeeringInfos: Optional[List[PeeringInfo]] = None  # 对等连接详情列表，包含与该VPC建立的所有对等连接及其状态
    ProjectID: Optional[str] = None  # 项目ID，资源所属项目分组标识
    ProjectName: Optional[str] = None  # 项目名称，资源所属项目名称
    Reason: Optional[str] = None  # 创建失败原因
    Region: Optional[str] = None  # 地域ID，用于标识资源所属的地理区域
    RegionAlias: Optional[str] = None  # 地域别名，地域的人性化显示名称
    Remark: Optional[str] = None  # 备注，用于补充说明
    State: Optional[str] = None  # VPC状态，资源生命周期状态，当资源状态非Available时返回资源状态
    SubnetCount: Optional[int] = None  # 子网数量，展示该VPC下已划分的子网总数
    SubnetInfos: Optional[List[SubnetInfo]] = None  # 子网详情列表，包含该VPC下所有子网的配置及状态信息
    Tags: Optional[List[UnifiedTag]] = None  # 资源标签列表，用于资源分类和检索
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
    VPCID: Optional[str] = None  # VPCID，虚拟私有网络的唯一标识符
