# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VPNTunnelInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，标识资源所属的租户组织，用于多租户资源隔离与权限控制
    ConnectState: Optional[str] = None  # 连接状态，IPSec隧道连接状态，创建/更新/删除中为空
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    DeleteTime: Optional[int] = None  # 删除时间，秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱，资源所属租户的联系邮箱
    IKEAuthenticationAlgorithm: Optional[str] = None  # IKE认证算法，IKE阶段使用的认证算法，取值：md5、sha1、sha256
    IKEDhGroup: Optional[int] = None  # IKE DH组，IKE阶段使用的Diffie-Hellman密钥交换组，取值范围：0、1、2、5、14、24（0为历史兼容值）
    IKEEncryptionAlgorithm: Optional[str] = None  # IKE加密算法，IKE阶段使用的加密算法，取值：3des、aes128、aes192、aes256
    IKEExchangeMode: Optional[str] = None  # IKE交换模式，仅当IKEVersion为v1时有效，IKEVersion为v2时为空
    IKELocalLabel: Optional[str] = None  # IKE本端标识，IKE协商时本端身份标识，空值表示使用IP地址作为标识
    IKERemoteLabel: Optional[str] = None  # IKE对端标识，IKE协商时对端身份标识，空值表示使用IP地址作为标识
    IKESALifetime: Optional[int] = None  # IKE SA生存时间，IKE安全关联的生存时间（秒）
    IKEVersion: Optional[str] = None  # IKE协议版本，Internet Key Exchange协议版本，取值：v1、v2
    IPSecAuthenticationAlgorithm: Optional[str] = None  # IPSec认证算法，IPSec阶段使用的认证算法，取值：md5、sha1、sha256
    IPSecEncryptionAlgorithm: Optional[str] = None  # IPSec加密算法，IPSec阶段使用的加密算法，仅当IPSecProtocol为ESP时有效，IPSecProtocol为AH时为空，取值：3des、aes128、aes192、aes256
    IPSecPFSDhGroup: Optional[int] = None  # IPSec PFS DH组，Perfect Forward Secrecy使用的Diffie-Hellman组，取值范围：0、1、2、5、14、24（0表示不启用PFS）
    IPSecProtocol: Optional[str] = None  # IPSec安全协议，IPSec使用的安全传输协议，取值：AH、ESP
    IPSecSALifetime: Optional[int] = None  # IPSec SA生存时间，IPSec安全关联的生存时间（秒）
    LocalSubnetIDs: Optional[List[str]] = None  # 本端子网ID列表，通过隧道互通的本端子网ID列表
    Name: Optional[str] = None  # VPN隧道名称，用于展示资源名称
    PreSharedKey: Optional[str] = None  # 预共享密钥，IPSec隧道协商使用的预共享密钥
    ProjectID: Optional[str] = None  # 项目ID，资源所属项目分组
    ProjectName: Optional[str] = None  # 项目名称，资源所属项目名称
    Region: Optional[str] = None  # 地域ID，用于标识资源所属的地理区域
    Remark: Optional[str] = None  # 备注，VPN隧道的描述信息
    RemoteSubnets: Optional[List[str]] = None  # 对端子网CIDR列表，通过隧道互通的对端网段列表
    RemoteVPNGWID: Optional[str] = None  # 对端网关ID，对端VPN网关唯一标识
    RemoteVPNGWIP: Optional[str] = None  # 对端网关IP，用于详情和列表展示
    RemoteVPNGWName: Optional[str] = None  # 对端网关名称，用于详情和列表展示
    State: Optional[str] = None  # 隧道状态，来自资源状态与底层隧道状态，创建/更新/删除中可能覆盖为资源状态
    Subnets: Optional[List[str]] = None  # 本端子网CIDR列表，用于详情和列表展示
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表，用于资源标记和分类管理
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
    VPCID: Optional[str] = None  # VPCID，VPN网关所属VPC
    VPNGWID: Optional[str] = None  # VPN网关ID，本地VPN网关唯一标识
    VPNGWIP: Optional[str] = None  # 本地VPN网关外网IP，用于详情和列表展示
    VPNGWName: Optional[str] = None  # 本地VPN网关名称，用于详情和列表展示
    VPNTunnelID: Optional[str] = None  # VPN隧道ID，VPN隧道唯一标识
