# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class WorkflowNode:
    """"""

    AuditMemberInfo: Optional[WorkflowNodeMemberInfo] = None  # 审批人信息，负责该节点审批的用户详细信息
    AutoAudit: Optional[bool] = None  # 是否自动审批，true表示该节点自动通过无需人工审批，false表示需要人工审批
    Name: Optional[str] = None  # 审批节点名称，用于标识审批环节的显示名称
    ObserverMemberInfos: Optional[List[WorkflowNodeMemberInfo]] = None  # 观察人信息列表，可以查看该节点审批进度但不参与审批决策的用户列表
