# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class AttachShareBlock:
    """"""

    AttachResourceID: Optional[str] = None  # 已挂载资源ID，挂载目标资源标识
    AttachResourceName: Optional[str] = None  # 已挂载资源名称，挂载目标资源名称
    AttachResourceType: Optional[str] = None  # 已挂载资源类型，挂载目标资源类型
    AttachStatus: Optional[str] = None  # 挂载状态，共享盘挂载状态
