# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class BaseExpiredResourceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，资源的付费方式
    CompanyID: Optional[int] = None  # 租户ID，标识该资源所属的租户
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳(秒)
    DeleteTime: Optional[int] = None  # 删除时间，Unix时间戳(秒)
    ExpireTime: Optional[int] = None  # 过期时间，Unix时间戳(秒)
    Name: Optional[str] = None  # 资源名称，资源的显示名称
    Region: Optional[str] = None  # 地域ID，标识该资源所属的地域
    Remark: Optional[str] = None  # 资源备注，资源的描述信息
    ResourceID: Optional[str] = None  # 资源ID，资源的唯一标识，包含资源类型前缀和14位随机字符
    ResourceType: Optional[str] = None  # 资源类型，指定资源的分类
    Status: Optional[str] = None  # 状态，资源的当前状态
    TerminateTime: Optional[int] = None  # 终止时间，Unix时间戳(秒)
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳(秒)
