# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ContainerStatus:
    """"""

    Container: Optional[str] = None  # 容器名
    PodName: Optional[str] = None  # pod名
    Ready: Optional[bool] = None  # 是否就绪
    Reason: Optional[str] = None  # 状态或原因
