# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ContainerLogInfo:
    """"""

    Body: Optional[str] = None  # 内容
    Time: Optional[int] = None  # 时间
