# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class CPUModelInfo:
    """"""

    CPUModel: Optional[str] = None  # CPU模型，CPU的具体型号标识，用于虚拟机迁移时的兼容性判断
    Disabled: Optional[bool] = None  # 是否被禁用，该CPU模型是否被管理员禁用，禁用后虚拟机无法使用该模型
    SupportedHosts: Optional[List[str]] = None  # 支持该CPU模型的物理机列表，列出集群中支持该CPU模型的所有物理机主机名
