# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class DTSPrecheckItem:
    """"""

    Passed: Optional[bool] = None  # 检查结果，标识该检查项是否通过，true表示通过，false表示未通过
    PreCheckName: Optional[str] = None  # 检查项名称，说明该预检查项检查的具体内容
    Reason: Optional[str] = None  # 失败原因，当Passed为false时说明未通过原因及建议处理方式
