# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ExternalStorageTypeInfo:
    """"""

    Region: Optional[str] = None  # 
    SetAlias: Optional[str] = None  # 
    SetArch: Optional[str] = None  # 
    SetID: Optional[str] = None  # 
    SetType: Optional[str] = None  # 
    SetUsage: Optional[str] = None  # 
    StorageCap: Optional[int] = None  # 
    StoragePhysicUsed: Optional[int] = None  # 
    StorageUsed: Optional[int] = None  # 
