# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ExternalDiskInfo:
    """"""

    AttachResourceID: Optional[str] = None  # 
    AttachResourceName: Optional[str] = None  # 
    AttachResourceType: Optional[str] = None  # 
    AttachShareBlockInfos: Optional[List[AttachExternalShareBlock]] = None  # 
    CompanyID: Optional[int] = None  # 
    CompnayName: Optional[str] = None  # 
    ComputeSetIDs: Optional[str] = None  # 
    CreateTime: Optional[int] = None  # 
    DiskID: Optional[str] = None  # 
    DiskStatus: Optional[str] = None  # 
    DiskType: Optional[str] = None  # 
    Email: Optional[str] = None  # 
    IQN: Optional[str] = None  # 
    LUNID: Optional[str] = None  # 
    MigrateBandWidth: Optional[int] = None  # 
    Name: Optional[str] = None  # 
    Percent: Optional[float] = None  # 迁移进度，外置存储盘迁移任务的完成百分比
    ProjectID: Optional[str] = None  # 
    ProjectName: Optional[str] = None  # 
    Reason: Optional[str] = None  # 
    Region: Optional[str] = None  # 
    RegionAlias: Optional[str] = None  # 
    Remark: Optional[str] = None  # 
    SetAlias: Optional[str] = None  # 
    SetArch: Optional[str] = None  # 
    SetID: Optional[str] = None  # 
    SetProvider: Optional[str] = None  # 
    SetType: Optional[str] = None  # 
    ShareAble: Optional[bool] = None  # 
    Size: Optional[int] = None  # 
    Tags: Optional[List[UnifiedTag]] = None  # 
    UsedForVirtSC: Optional[bool] = None  # 
