# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FlatNetworkRoute:
    """"""

    Destination: Optional[str] = None  # 目的地址CIDR，路由的目标网段
    FlatNetworkID: Optional[str] = None  # 扁平网络ID，路由所属的扁平网络唯一标识
    FlatNetworkName: Optional[str] = None  # 扁平网络名称，路由所属网络的名称
    NextHop: Optional[str] = None  # 下一跳地址，数据包转发的网关IP
    NextHopAddr: Optional[str] = None  # 下一跳IP地址，下一跳的具体IP地址
    NextHopName: Optional[str] = None  # 下一跳名称，下一跳网络或设备的名称
    NextHopType: Optional[str] = None  # 下一跳类型，路由的下一跳类型，如local表示本地路由
    Remark: Optional[str] = None  # 备注信息，路由的说明或用途描述
