# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FlatNetwork:
    """"""

    AvailableCount: Optional[int] = None  # 可用IP数量，剩余可分配的IP地址数
    CIDR: Optional[str] = None  # 网段CIDR，网络的IP地址范围
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    DHCPServerIP: Optional[str] = None  # DHCP服务器IP地址，DHCP服务监听的IP
    DNS: Optional[str] = None  # DNS配置，DNS服务器地址列表，多个地址用逗号分隔
    Description: Optional[str] = None  # 备注信息，网络的用途说明
    Device: Optional[str] = None  # 物理网卡设备名称，绑定的物理网络接口
    EnableDHCP: Optional[bool] = None  # 是否开启DHCP服务，启用后自动分配IP
    FlatNetworkID: Optional[str] = None  # 扁平网络ID，网络的唯一标识
    GatewayIP: Optional[str] = None  # 网关IP地址，网络的默认网关IP
    IPRanges: Optional[str] = None  # 可用IP范围，可分配的IP地址段
    IPVersion: Optional[str] = None  # IP协议版本，IPv4或IPv6
    Name: Optional[str] = None  # 扁平网络名称，用于标识网络资源
    Permission: Optional[str] = None  # 权限配置，all表示所有租户可用，租户ID列表表示仅指定租户可用
    PermissionMode: Optional[str] = None  # 权限模式，控制租户访问权限的模式，可选值：all（所有租户可用）、whitelist（白名单，仅指定租户可用）、blacklist（黑名单，仅指定租户不可用）
    Platform: Optional[bool] = None  # 是否为平台专用，true表示平台内部使用的网络
    Region: Optional[str] = None  # 地域ID，用于标识资源所属的地理区域
    RegionAlias: Optional[str] = None  # 地域名称
    Routing: Optional[str] = None  # 路由配置，默认路由或路由目标列表
    Status: Optional[str] = None  # 资源生命周期状态，当资源状态非Available时返回资源状态
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表，资源的标记和分类信息
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
    UsedCount: Optional[int] = None  # 已用IP数量，已分配的IP地址数
    Vlan: Optional[str] = None  # VLAN标识，网络隔离标记，可选，取值范围1-4094，不传或传0表示不设置VLAN
