# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class FSInfo:
    """"""

    Bandwidth: Optional[int] = None  # 带宽，磁盘吞吐量（MB/s）
    ChargeType: Optional[str] = None  # 计费类型，计费模式，取值范围：Dynamic（按小时计费）、Month（按月计费）、Year（按年计费）；兼容历史值：hour、month、year，别名映射：Dynamic→HOUR、Month→MONTH、Year→YEAR
    CompanyID: Optional[int] = None  # 租户ID，文件存储所属租户标识
    CompanyName: Optional[str] = None  # 租户名称，文件存储所属租户名称
    CreateTime: Optional[int] = None  # 创建时间，Unix 时间戳（秒级）
    DiskID: Optional[str] = None  # 磁盘ID，文件存储挂载的数据盘标识
    DiskSpace: Optional[int] = None  # 存储容量，单位GiB
    Email: Optional[str] = None  # 租户邮箱，文件存储所属租户联系邮箱
    Endpoints: Optional[List[FsEndpoint]] = None  # 网络信息，文件存储访问终端信息
    ExpireTime: Optional[int] = None  # 过期时间，Unix 时间戳（秒级）
    FSID: Optional[str] = None  # 文件存储实例ID，文件存储标识
    IOPS: Optional[int] = None  # IOPS，磁盘每秒输入输出操作次数
    Name: Optional[str] = None  # 名称，文件存储服务名称
    ProjectID: Optional[str] = None  # 项目组ID，文件存储所属项目组
    ProjectName: Optional[str] = None  # 项目组名称，文件存储所属项目组名称
    Reason: Optional[str] = None  # 失败原因，创建或回收失败的原因
    Region: Optional[str] = None  # 地域，文件存储所属地域
    RegionAlias: Optional[str] = None  # 地域别名，用于展示
    Remark: Optional[str] = None  # 备注，用于说明文件存储用途
    SetArch: Optional[str] = None  # 计算集群架构，取值范围：x86_64、AArch64
    Status: Optional[str] = None  # 状态，文件存储运行状态，取值范围：Running、Stopped、Starting、Stopping、Upgrading
    StorageSetArch: Optional[str] = None  # 存储集群架构，数据盘所在存储集群架构
    StorageSetType: Optional[str] = None  # 存储集群类型，数据盘所在存储集群类型
    StorageSetTypeAlias: Optional[str] = None  # 存储集群名称，数据盘所在存储集群名称
    SubnetID: Optional[str] = None  # 子网ID，文件存储所属子网标识
    SubnetName: Optional[str] = None  # 子网名称，文件存储所属子网名称
    Tags: Optional[List[UnifiedTag]] = None  # 标签，资源标签列表
    TerminationPolicy: Optional[int] = None  # 删除保护策略，取值范围：0（开启删除保护）、1（关闭删除保护）
    UpdateTime: Optional[int] = None  # 更新时间，Unix 时间戳（秒级）
    VMType: Optional[str] = None  # 计算集群类型，文件存储所在计算集群类型
    VMTypeAlias: Optional[str] = None  # 计算集群名称，文件存储所在计算集群名称
    VPCID: Optional[str] = None  # VPC ID，文件存储所属VPC标识
    VPCName: Optional[str] = None  # VPC名称，文件存储所属VPC名称
