# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class HostGPUUsedInfo:
    """"""

    Allocable: Optional[int] = None  # 可用GPU，剩余可分配数量
    Count: Optional[int] = None  # GPU总量，物理GPU总数
    HDName: Optional[str] = None  # GPU硬件名称，物理GPU设备名称
    Locked: Optional[int] = None  # 锁定GPU，已锁定待分配数量
    MdevName: Optional[str] = None  # vGPU规格名称，支持的虚拟GPU规格
    Used: Optional[int] = None  # 已用GPU，已分配数量
