# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InspectionInspectionInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户唯一标识ID，标识创建该巡检报告的租户
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳(秒)
    InspectionID: Optional[str] = None  # 一键巡检报告ID
    Name: Optional[str] = None  # 报告名称，巡检报告的显示名称
    Spend: Optional[int] = None  # 耗时(秒)，巡检任务执行所花费的时间
    Status: Optional[str] = None  # 报告状态，巡检任务的当前执行状态
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳(秒)
