# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InstallVLANConfig:
    """"""

    IPs: Optional[List[InstallIPConfig]] = None  # IP地址列表
    Name: Optional[str] = None  # VLAN名称
    Parent: Optional[str] = None  # 父接口
    VlanID: Optional[int] = None  # VLAN ID
