# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class InstallPhysicalConfig:
    """"""

    DHCP: Optional[bool] = None  # 是否使用 DHCP
    IPs: Optional[List[InstallIPConfig]] = None  # IP地址列表
    Interface: Optional[str] = None  # 物理网卡名称或 MAC 地址
    Master: Optional[str] = None  # 所属 Bond 名称
