# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class IP:
    """"""

    Address: Optional[str] = None  # IP地址，网卡IP地址
    Mask: Optional[str] = None  # 掩码，网卡子网掩码
