# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class IPAddress:
    """"""

    Ip: Optional[str] = None  # Ip地址
    Port: Optional[int] = None  # 端口
    Type: Optional[str] = None  # 地址类型，可为 advertise, public 等
