# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class ISOInfo:
    """"""

    Boot: Optional[bool] = None  # 是否从此盘引导，true表示从此盘引导
    ImageID: Optional[str] = None  # ISO镜像ID，ISO镜像标识
    ImageName: Optional[str] = None  # ISO镜像名称，ISO镜像展示名称
    Region: Optional[str] = None  # ISO所属地域，ISO磁盘所属地域
    SetArch: Optional[str] = None  # 存储集群架构，ISO磁盘所属存储集群架构
    SetType: Optional[str] = None  # 存储集群类型，ISO磁盘所属存储集群类型
    Size: Optional[int] = None  # 磁盘大小，单位GiB
    Status: Optional[str] = None  # 磁盘状态，ISO磁盘当前状态
    Type: Optional[str] = None  # ISO磁盘类型，ISO磁盘类型标识
