# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class K8SPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型
    Price: Optional[float] = None  # 价格
