# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class LbPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
    OrderType: Optional[str] = None  # 订单类型，用于说明价格对应的订单场景（如新购、升级、降级）
    Price: Optional[float] = None  # 价格，用于展示对应计费周期的价格信息
