# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class LbVSPolicyInfo:
    """"""

    CACertificateID: Optional[str] = None  # CA证书ID，SNI协议开启时的CA证书ID
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    Domain: Optional[str] = None  # 请求域名，转发规则关联的请求域名，值可为空表示仅匹配路径，若填写则遵循Nginx server_name规则（最长30字符，可使用*.example.com或mail.*一类通配格式）
    LBID: Optional[str] = None  # 负载均衡ID，用于标识所属负载均衡实例
    Path: Optional[str] = None  # 请求访问路径，转发规则关联的请求访问路径，如'/'，
    PolicyID: Optional[str] = None  # 转发规则ID，用于定位转发规则
    PolicyStatus: Optional[str] = None  # 转发规则状态，转发规则的状态，取值范围：Available（有效）、Deleted（已删除）
    RSInfos: Optional[List[LbRSInfo]] = None  # 真实服务器列表，转发规则关联的真实服务器列表
    RedirectPolicyID: Optional[str] = None  # HTTP重定向转发规则ID，HTTP重定向指向的转发规则ID
    SSLMode: Optional[str] = None  # SSL认证模式，SNI协议开启时的SSL模式，取值范围：simplex、duplex
    ServerCertificateID: Optional[str] = None  # 服务器证书ID，SNI协议开启时的服务器证书ID
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
    VSID: Optional[str] = None  # 虚拟服务器ID，用于标识所属监听器
