# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MetricFilter:
    """"""

    Condition: Optional[MetricFilterCondition] = None  # 过滤器的具体条件配置，定义过滤的键值对和操作方式
    Description: Optional[str] = None  # 过滤器的描述信息，说明该过滤器的作用和用途
