# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MetricInfo:
    """"""

    Categories: Optional[str] = None  # 指标分组类别，用于在界面上对监控指标进行分类显示和管理
    CompareType: Optional[str] = None  # 告警阈值对比类型，定义告警触发时的比较方式，如大于、小于、等于等
    Enums: Optional[List[Enums]] = None  # 枚举值列表，当指标为枚举类型时提供可选的枚举项
    Filters: Optional[List[MetricFilter]] = None  # 指标过滤器列表，用于对监控数据进行筛选和过滤的条件配置
    IsAlerting: Optional[bool] = None  # 是否支持告警功能，标识该具体指标是否可以用于配置告警规则
    Labels: Optional[List[str]] = None  # 指标标签列表，用于对监控指标进行分类和标记的标签信息
    Metric: Optional[str] = None  # Prometheus查询语句，用于从监控系统中获取该指标的实际数据
    MetricID: Optional[str] = None  # 监控指标的唯一标识符，用于在系统中唯一标识一个监控指标
    Name: Optional[str] = None  # 指标的中文名称和含义描述，用于在界面上显示给用户理解
    RangeMax: Optional[str] = None  # 指标数据的最大有效值，用于数据验证和界面显示范围限制
    RangeMin: Optional[str] = None  # 指标数据的最小有效值，用于数据验证和界面显示范围限制
    Unit: Optional[str] = None  # 指标数据的计量单位，如百分比、字节、次数等
    UseYCallback: Optional[bool] = None  # 是否需要单位转换回调处理，标识在显示该指标数据时是否需要进行单位转换
