# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class MySQLParamTplInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID，模板所属租户
    CreateTime: Optional[int] = None  # 创建时间，Unix时间戳（秒）
    Email: Optional[str] = None  # 租户邮箱，模板所属租户邮箱
    ID: Optional[str] = None  # 模板ID，参数模板ID
    Name: Optional[str] = None  # 名称，模板名称
    Region: Optional[str] = None  # 地域ID，模板所属地域
    Remark: Optional[str] = None  # 描述，模板描述信息
    Type: Optional[str] = None  # 类型，模板类型
    UpdateTime: Optional[int] = None  # 更新时间，Unix时间戳（秒）
    Version: Optional[str] = None  # 版本，MySQL版本
