# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class NatGwPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，取值范围：Dynamic、Month、Year；兼容历史值：hour、month、year，别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR
    Price: Optional[float] = None  # 价格，用于展示计费周期对应的价格信息（单位：元）
