# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class Network:
    """"""

    NICs: Optional[List[NIC]] = None  # 虚拟网卡详情，节点网卡信息
    PhyProductInfos: Optional[List[PhyProductInfo]] = None  # 物理网卡详情，节点网卡信息
