# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class OSMediaInfoV2:
    """"""

    CompanyID: Optional[int] = None  # 租户ID
    CompanyName: Optional[str] = None  # 租户名称
    CreatedAt: Optional[int] = None  # 创建时间
    Description: Optional[str] = None  # 描述
    Email: Optional[str] = None  # 租户邮箱
    ErrorMessage: Optional[str] = None  # 错误信息
    FileSize: Optional[int] = None  # 文件大小(字节)
    ImageID: Optional[str] = None  # 镜像ID
    IsDefault: Optional[bool] = None  # 是否默认系统镜像
    MediaID: Optional[str] = None  # 系统镜像ID（Taishan生成）
    Name: Optional[str] = None  # 系统镜像名称
    OSDistribution: Optional[str] = None  # 操作系统发行版（如：CentOS、OpenEuler）
    OSName: Optional[str] = None  # 操作系统完整名称（如：CentOS 7.4 x86_64）
    ProjectID: Optional[str] = None  # 项目ID
    ProjectName: Optional[str] = None  # 项目名称
    Region: Optional[str] = None  # 地域
    SHA256: Optional[str] = None  # SHA256校验和
    Status: Optional[str] = None  # 状态
    Tags: Optional[List[UnifiedTag]] = None  # 标签
    Type: Optional[str] = None  # 系统镜像类型: ISO
    URL: Optional[str] = None  # 系统镜像URL地址
    UpdatedAt: Optional[int] = None  # 更新时间
