# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class OSDStat:
    """"""

    DiskType: Optional[str] = None  # 磁盘类型，OSD磁盘类型
    HostIP: Optional[str] = None  # 宿主机IP，OSD所在主机IP地址
    HostName: Optional[str] = None  # 主机名，OSD所在主机名称
    OSDID: Optional[str] = None  # OSDID，OSD唯一标识
    OSDName: Optional[str] = None  # OSD名称，OSD显示名称
    Size: Optional[int] = None  # 大小，OSD容量大小
    Status: Optional[str] = None  # 状态，OSD当前状态
    StorageType: Optional[str] = None  # 存储类型，用于标识存储类型
    Used: Optional[int] = None  # 使用量，已使用容量
