# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PartitionTemplateBtrfsSubvol:
    """"""

    MountPoint: Optional[str] = None  # 挂载点
    Name: Optional[str] = None  # 子卷名称
    Options: Optional[str] = None  # 挂载选项
