# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PartitionTemplateRAIDConfig:
    """"""

    Device: Optional[str] = None  # RAID设备名
    FSType: Optional[str] = None  # 文件系统类型
    Level: Optional[str] = None  # RAID级别: 0,1,5,6,10
    Members: Optional[List[str]] = None  # 成员磁盘
    MountPoint: Optional[str] = None  # 挂载点
