# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PermissionInfo:
    """"""

    Action: Optional[str] = None  # API操作名，用于标识权限动作
    Permission: Optional[bool] = None  # 权限结果，标识是否拥有该action权限
