# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PFInfo:
    """"""

    Code: Optional[str] = None  # 网卡型号标准编号，网卡型号标识
    DeviceName: Optional[str] = None  # 网卡名，操作系统设备名
    Driver: Optional[str] = None  # 驱动，网卡驱动名称
    NICStatus: Optional[NICStatus] = None  # 网卡状态，当前状态信息
    PCI: Optional[str] = None  # PCI位置，网卡PCI地址
    Product: Optional[str] = None  # 网卡型号，网卡型号名称
    UsedVFs: Optional[List[VFInfo]] = None  # 已使用的VF网卡列表
    VFLogicCount: Optional[int] = None  # 逻辑限制的VF数量，VFLogicCount<=VFPhyCount，VFLogicCount为0时以VFPhyCount为准
    VFPhyCount: Optional[int] = None  # 物理限制的VF数量，网卡物理上限
    Vendor: Optional[str] = None  # 网卡厂商，网卡厂商名称
