# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PFSummary:
    """"""

    PFCode: Optional[str] = None  # 物理网卡型号编号，物理网卡型号的标准编号，格式为厂商ID-设备ID
    Product: Optional[str] = None  # 网卡型号，物理网卡的具体型号
    VFCount: Optional[int] = None  # VF总量，该物理网卡可提供的虚拟功能（Virtual Function）总数
    VFUsed: Optional[int] = None  # VF已使用数量，该物理网卡已分配给虚拟机的VF数量
    Vendor: Optional[str] = None  # 网卡厂商，物理网卡的制造商名称
