# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PhysicalDiskPartition:
    """"""

    Mountpoint: Optional[str] = None  # 挂载点，分区挂载路径
    Partition: Optional[str] = None  # 分区名，磁盘分区名称
    Size: Optional[int] = None  # 大小，单位GiB
    Used: Optional[int] = None  # 已用大小，单位GiB
