# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PlatformStorageDiskInfo:
    """"""

    DiskID: Optional[str] = None  # 磁盘ID，平台通用存储云盘ID
    DiskSpace: Optional[int] = None  # 磁盘大小，云盘容量，单位GiB
    DiskStatus: Optional[str] = None  # 磁盘状态，云盘当前状态
    SetArch: Optional[str] = None  # 集群架构，云盘所属集群架构
    SetType: Optional[str] = None  # 集群类型，云盘所属集群类型
