# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class PortGroupInfo:
    """"""

    CompanyID: Optional[int] = None  # 租户ID
    CreateTime: Optional[int] = None  # 创建时间，秒级Unix时间戳
    Email: Optional[str] = None  # 租户邮箱
    Name: Optional[str] = None  # 端口组名称，用于标识端口组
    PortGroupID: Optional[str] = None  # 端口组ID，端口组的唯一标识符
    ProjectID: Optional[str] = None  # 项目ID
    ProjectName: Optional[str] = None  # 项目名称
    Reason: Optional[str] = None  # 失败原因，创建或操作失败时记录具体原因
    Region: Optional[str] = None  # 地域ID，用于标识端口组所属的地理区域
    RegionAlias: Optional[str] = None  # 地域名称
    Remark: Optional[str] = None  # 备注，端口组的补充说明信息
    Rules: Optional[str] = None  # 端口组规则，端口组包含的协议与端口组合，格式为协议:端口或协议:端口范围
    Status: Optional[str] = None  # 资源生命周期状态，当资源状态非Available时返回资源状态
    Tags: Optional[List[UnifiedTag]] = None  # 标签列表
    UpdateTime: Optional[int] = None  # 更新时间，秒级Unix时间戳
    UsedSGCount: Optional[int] = None  # 已用安全组数量，引用该端口组的安全组规则总数
    UsedSGIDInfos: Optional[List[UsedSGIDInfo]] = None  # 已用安全组列表，包含引用该端口组的安全组信息
