# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class QuotaUsage:
    """"""

    FactorType: Optional[str] = None  # 配额因子，计量维度
    ProductType: Optional[str] = None  # 产品类型
    Quota: Optional[int] = None  # 配额总量
    Region: Optional[str] = None  # 地域ID
    RegionAlias: Optional[str] = None  # 地域别名，地域的显示名称
    ResourceType: Optional[str] = None  # 资源类型
    Unit: Optional[str] = None  # 配额单位
    Usage: Optional[int] = None  # 已使用配额量
