# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class RegionConfigCategoryInfo:
    """"""

    Category: Optional[str] = None  # 类别标识，地域配置类别的唯一键
    CategoryName: Optional[str] = None  # 类别名称，地域配置类别的显示名称，支持国际化
    CategoryPosition: Optional[int] = None  # 类别排序位置，用于前端展示排序
    ConfigInfos: Optional[List[RegionConfigInfo]] = None  # 类别下的地域配置项列表
