# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class TrafficShaping:
    """"""

    AverageBandwidth: Optional[int] = None  # 平均带宽，单位Mbps，限制平均网络吸吐量
    Enable: Optional[bool] = None  # 是否启用，流量整形功能的开关
