# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class UserAccessInfo:
    """"""

    Amount: Optional[float] = None  # 总余额，账户可支配资金总额，单位为元
    AmountCredit: Optional[float] = None  # 外部余额，通过充值获得的余额，单位为元
    AmountFree: Optional[float] = None  # 内部余额，系统发放的免额额度，单位为元
    Audit: Optional[int] = None  # 审批开关，标识租户资源变更是否需人工审批
    CompanyID: Optional[int] = None  # 租户ID，账号所属租户标识
    CompanyStatus: Optional[str] = None  # 租户状态，标识账号所属租户当前是否可用
    CreateTime: Optional[int] = None  # 创建时间，账号首次建立的Unix时间戳
    Email: Optional[str] = None  # 账号邮箱，登录与通知邮箱
    GrantLevels: Optional[List[str]] = None  # 授权等级列表，标识账号可管理的层级范围
    MemberID: Optional[int] = None  # 成员ID，当前账号唯一标识
    MemberName: Optional[str] = None  # 成员名称，账号展示名称用于管理界面显示
    OAuth2UniqueID: Optional[str] = None  # OAuth2唯一标识ID，用于绑定外部SSO系统的用户身份
    Phone: Optional[str] = None  # 手机号，用于安全通知或验证码接收
    PrivateKey: Optional[str] = None  # API私钥，用于请求签名，需妥善保管
    Privileges: Optional[str] = None  # 权限级别，标识账号在租户内的管理范围
    PublicKey: Optional[str] = None  # API公钥，用于请求签名校验与鉴权
    Status: Optional[str] = None  # 账号状态，标识账号当前可用性
    UpdateTime: Optional[int] = None  # 更新时间，账号信息最后一次修改的Unix时间戳
    UserEmail: Optional[str] = None  # 用户邮箱，用于关联用户主体邮箱
    UserName: Optional[str] = None  # 用户名称，兼容字段用于展示
