# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VFInfo:
    """"""

    PCI: Optional[str] = None  # PCI位置，VF网卡PCI地址
    RelatedNIC: Optional[str] = None  # 关联网卡，关联网卡标识
    RelatedVM: Optional[str] = None  # 关联虚拟机，关联虚拟机标识
