# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VipPriceInfo:
    """"""

    ChargeType: Optional[str] = None  # 计费类型，取值范围：Dynamic（动态）、Month（按月计费）、Year（按年计费），兼容hour/month/year，计费类型别名映射：Dynamic->HOUR、Month->MONTH、Year->YEAR，hour->HOUR、month->MONTH、year->YEAR
    OrderType: Optional[str] = None  # 订单类型，标识订单的操作类型
    Price: Optional[float] = None  # 价格，单位元
