# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class VMMigrationInfo:
    """"""

    Message: Optional[str] = None  # 迁移信息
    MigrationTime: Optional[int] = None  # 完成时间
    SourceNode: Optional[str] = None  # 执行job时原节点
    Status: Optional[str] = None  # 迁移建议状态，取值NotMigrated/Migrated/Changed
    TargetNode: Optional[str] = None  # 执行job时目标节点
