# Code generated by sdk-generator. DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, List, Any, Dict


@dataclass
class WithdrawTradeInfo:
    """"""

    AccountID: Optional[int] = None  # 账号ID，与CompanyID相同
    AccountName: Optional[str] = None  # 账号名称，与CompanyName对应
    CompanyID: Optional[int] = None  # 租户ID
    CompanyName: Optional[str] = None  # 租户名称
    CreateTime: Optional[int] = None  # 创建时间
    Email: Optional[str] = None  # 租户邮箱
    SerialNo: Optional[str] = None  # 提现单号，提现的序列号
    SrcAccountType: Optional[str] = None  # 源账户类型，FREE表示赠金账户，REAL表示现金账户
    TradeNo: Optional[str] = None  # 交易单号，提现生成的交易唯一标识
    WithdrawAmount: Optional[float] = None  # 提现金额，单位为元，精确到分
